### ISSUE TITLE
API backwards compatibility update, reinstate old addRecipient API as deprecated

### ISSUE THREAD

**Issue by amanteaux** [bbottema/simple-java-mail#101]
In version 4.4.x, the method Email.addRecipient(String, String, RecipientType) has been deleted whereas it was not even deprecated before.

Would it be possible to put back this method as deprecated in the 4.x.x branch and plan to remove it in the 5.x.x major release?
It would really make Simple Java Mail users feel more confident about this library.
If possible, breaking changes should append as little as possible and should not be taken lightly.

**Comment by bbottema** [comment]
You're absolutely right. I hadn't even thought of it until you mentioned it. I'll add them back deprecated asap

**Comment by amanteaux** [comment]
Thank you a lot!

**Comment by bbottema** [comment]
Released in 4.4.5

**Comment by amanteaux** [comment]
Wow that was quick!
This is perfect, thank you!
