### ISSUE TITLE
mailer.sendMail() has no second argument in version 4.4.5

### ISSUE THREAD

**Issue by lacivert** [bbottema/simple-java-mail#106]
In [website](http://www.simplejavamail.org/#/features), section **Sending with SSL and TLS** the examples look completely wrong:

```
mailer.sendMail(email, TransportStrategy.SMTP_PLAIN); // default if omitted
mailer.sendMail(email, TransportStrategy.SMTP_SSL);
mailer.sendMail(email, TransportStrategy.SMTP_TLS);
```

Because sendMail() method doesn't have a suitable 2nd argument like this. Either the website should be corrected or this method should be re-implemented (I suppose)

**Comment by bbottema** [comment]
Fixed. Thanks for the heads-up!

**Comment by lacivert** [comment]
Thanks. I guess `email.addNamedToRecipient()` method's name is changed as well? I can't use that either.
