### ISSUE TITLE
Trusted hosts should be space-delimited

### ISSUE THREAD

**Issue by cbarcenas** [bbottema/simple-java-mail#110]
When setting `mail.smtp.ssl.trust` to a list of trusted domains, Simple Java Mail [currently comma-delimits the list of domains](https://github.com/bbottema/simple-java-mail/blob/master/src/main/java/org/simplejavamail/mailer/internal/mailsender/MailSender.java#L330-L345). This behavior is invalid; JavaMail [expects a space-separated list of hosts](https://github.com/javaee/javamail/blob/86e3eb827ed42c84dde6180da50ec32191930ad4/mail/src/main/java/com/sun/mail/util/SocketFetcher.java#L373).

**Comment by bbottema** [comment]
Released as 5.0.0.rc1-SNAPSHOT. Add [OSS' snapshots repo](https://stackoverflow.com/questions/7715321/how-to-download-snapshot-version-from-maven-snapshot-repository/7717234#7717234) to find it in Maven.
