### ISSUE TITLE
MailSender doesn't correctly set JavaMail properties for SMTPS connections

### ISSUE THREAD

**Issue by cbarcenas** [bbottema/simple-java-mail#111]
Several of the configuration methods in `MailSender` incorrectly set JavaMail properties under the `mail.smtp` prefix when `smtps` mail transport (`TransportStrategy.SMTP_SSL`) is used. I'm pretty sure the `mail.smtps` prefix should be used instead.

Examples: [[1]](https://github.com/bbottema/simple-java-mail/blob/a62d54e03efdb88d11c2ec1c6eb53d1aa6320409/src/main/java/org/simplejavamail/mailer/internal/mailsender/MailSender.java#L218-L220) [[2]](https://github.com/bbottema/simple-java-mail/blob/a62d54e03efdb88d11c2ec1c6eb53d1aa6320409/src/main/java/org/simplejavamail/mailer/internal/mailsender/MailSender.java#L324) [[3]](https://github.com/bbottema/simple-java-mail/blob/a62d54e03efdb88d11c2ec1c6eb53d1aa6320409/src/main/java/org/simplejavamail/mailer/internal/mailsender/MailSender.java#L326) [[4]](https://github.com/bbottema/simple-java-mail/blob/a62d54e03efdb88d11c2ec1c6eb53d1aa6320409/src/main/java/org/simplejavamail/mailer/internal/mailsender/MailSender.java#L343)

The cleanest fix, I think, is to implement additional abstract property name getters under the `TransportStrategy` enum.

**Comment by bbottema** [comment]
Indeed, quoting javaee:

> Note that if you're using the "smtps" protocol to access SMTP over SSL, all the properties would be named "mail.smtps.*".
> - https://javaee.github.io/javamail/docs/api/com/sun/mail/smtp/package-summary.html

I agree, these properties will need to come from the `TransportStrategy` enum.

**Comment by cbarcenas** [comment]
Now that I think about it, why don't we scrap the per-property interface and instead add a single `propertyNamePrefix()` method to each enum type?

**Comment by bbottema** [comment]
I like the flexibility it gives me in case the property is completely different per transport strategy. Of course this will never happen with this decades old specification, so it is kind of moot.

However, I like this design, it's clear enough. And I've already updated it.

**Comment by cbarcenas** [comment]
Cool, I'm pretty indifferent either way

**Comment by bbottema** [comment]
Actually, this was rather tricky, since the transport strategy is an optional parameter in favor of a preconfigured provided Session object.

In one type of scenario an exception was in order, in a second skipping defaults and in a third skipping properties logging they were assumed to be preconfigured.

**Comment by bbottema** [comment]
Released as 5.0.0.rc1-SNAPSHOT. Add [OSS' snapshots repo](https://stackoverflow.com/questions/7715321/how-to-download-snapshot-version-from-maven-snapshot-repository/7717234#7717234) to find it in Maven.
