### ISSUE TITLE
Bump to JavaMail 1.6 and get rid of outdated JARs in lib/ 

### ISSUE THREAD

**Issue by cbarcenas** [bbottema/simple-java-mail#113]
Might as well bump the `pom.xml` to JavaMail 1.6.x.

Also, seem to be even older versions of JavaMail creeping around the `lib/` directory. Are these used anywhere?

**Comment by bbottema** [comment]
Haha, no. They are for convenience only (many years ago it was a little difficult to find the right version). I think it can be removed now...

**Comment by bbottema** [comment]
Released as 5.0.0.rc1-SNAPSHOT. Add [OSS' snapshots repo](https://stackoverflow.com/questions/7715321/how-to-download-snapshot-version-from-maven-snapshot-repository/7717234#7717234) to find it in Maven.
