### ISSUE TITLE
Test connection without sending email

### ISSUE THREAD

**Issue by stevenvanloon** [bbottema/simple-java-mail#116]
Hi,

At this moment, I test whether a connection to the smtp server is valid or not, by executing this code:

```
public void testConnection() {
	try {
		Mailer mailer = createMailer();
		Session session = mailer.getSession();
		Transport transport = session.getTransport("smtp");
		try {
			transport.connect();
		} finally {
			transport.close();
		}
	} catch (MessagingException e) {
		... handle error ...
	}
}
```
That's why I need access to the Session object:

> _"Providing access to Session instance for emergency fall-back scenario. Please let us know why you need it."_

Is there another way to do this without actually sending an email and without using the Session object?

Thanks,
Best regards,
Steven.

**Comment by bbottema** [comment]
Not yet, but thanks for reporting. I think it's an interesting feature!

**Comment by bbottema** [comment]
Implemented for version 5.0.0. Should also work with (authenticated) proxy!

**Comment by stevenvanloon** [comment]
Looks good!

**Comment by bbottema** [comment]
Released as 5.0.0.rc1-SNAPSHOT. Add [OSS' snapshots repo](https://stackoverflow.com/questions/7715321/how-to-download-snapshot-version-from-maven-snapshot-repository/7717234#7717234) to find it in Maven.

**Comment by mrj** [comment]
The docs and source don't say how to use the testConnection method. Is a MessagingException thrown?

**Comment by bbottema** [comment]
@mrj Indeed, I will update the documentation and Javadoc to indicate this. Thanks!
