### ISSUE TITLE
Accepts email address "John Doe <john.doe@abc.com>" but sets incorrect header when sending

### ISSUE THREAD

**Issue by jatcwang** [bbottema/simple-java-mail#128]
I'm using version 4.4.5

According to the RFC `John Doe <john.doe@abc.com>` is a valid email address.

The email validator does recognize that it is a valid email, but when it comes to actually setting the email headers, it (I assume) incorrectly wraps it in angle brackets again, resulting in the address `<John Doe <john.doe@abc.com>>`

The location which this happens is in 
`MimeMessageHelper` line 108. See attached image.

![image](https://user-images.githubusercontent.com/4957161/36184970-9138b530-1182-11e8-94f4-cdeded52e2e3.png)

**Comment by bbottema** [comment]
That is by design, to achieve the best compatibility with clients receiving the email
.

Are you facing a problem?

**Comment by jatcwang** [comment]
I guess I'd expect an address that has passed validation by `EmailAddressValidator` to send fine, but currently it's throwing an exception in `InternetAddress#parse` when I actually try to send the email.

It seems like github has swallowed some of the characters I typed in the opening post. I have updated it

**Comment by bbottema** [comment]
Can you post a sample code where you provide the address? A failing junit test would suffice too.

**Comment by jatcwang** [comment]
Here you go @bbottema. https://github.com/jatcwang/repro-simplejavamail

Reproduced on 4.4.5, 5.0.0 doesn't seem to have this issue. (check git commit history)

I initially pulled in 4.4.5 for my project because v5 was still in beta, but now I can just upgrade and this shouldn't be a problem for me anymore.

Feel free to close this ticket if you're not planning to fix v4 series.
