### ISSUE TITLE
Interception of errors for processing

### ISSUE THREAD

**Issue by Tsyklop** [bbottema/simple-java-mail#134]
Hello! I have a Java EE server from which I send emails.

I need catching error like AuthenticationFailedException, MailSendexception. But I can't catching it with `try { }catch() { }` block.

More info: User can add own smtp server. And i need check it. But i can't check error, if they arise and show user what incorrect because i can't catching error. 

Could you make that methods throwing exceptions?

I trying testing data getting from user with `mailer.testConnection()`. And i can`t send responce to user with success or data incorrect.

Thanks.

**Comment by bbottema** [comment]
Exceptions are currently wrapped in a `MailException` so you can catch that and then look into the cause with [`.getCause()`](https://docs.oracle.com/javase/tutorial/essential/exceptions/chained.html). You can inspect the entire chain that way.

**Comment by bbottema** [comment]
Did you have any luck getting the right _cause_ Exception from the chain?

**Comment by Tsyklop** [comment]
@bbottema Oh. no questions! Thanks, you help me
