### ISSUE TITLE
trustingAllHosts is private

### ISSUE THREAD

**Issue by MartinVerges** [bbottema/simple-java-mail#135]
trustingAllHosts in the builder used to be public but it's private since https://github.com/bbottema/simple-java-mail/commit/eaa767778fa97f4f889de23c884af9abdba2d93c#diff-2ccc25806b11b5b4c660efb12c8a4d1aR362

should it be public?

**Comment by bbottema** [comment]
Indeed, seems like an oversight on my part. Thanks for the heads up.

**Comment by bbottema** [comment]
Fixed in 5.0.2.
