### ISSUE TITLE
Class not being able to be found when using Java 10

### ISSUE THREAD

**Issue by Willim7** [bbottema/simple-java-mail#143]
I tried sending an email and when I tried to run the code it threw a ClassNotFoundExpection. I have everything imported via Maven my pom.xml which looks like the following:

```
    <groupId>me.willis.myplugin</groupId>
    <artifactId>MyPlugin</artifactId>
    <version>1.0-SNAPSHOT</version>

    <repositories>
        <repository>
            <id>spigot-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
    </repositories>


    <dependencies>
        <!--Spigot API-->
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.12.2-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <!--Bukkit API-->
        <dependency>
            <groupId>org.bukkit</groupId>
            <artifactId>bukkit</artifactId>
            <version>1.12.2-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.simplejavamail</groupId>
            <artifactId>simple-java-mail</artifactId>
            <version>5.0.3</version>
        </dependency>
        <!--Google Authentication-->
        <dependency>
            <groupId>com.warrenstrange</groupId>
            <artifactId>googleauth</artifactId>
            <version>1.1.2</version>
        </dependency>
    </dependencies>

</project>
```
The error that showed up was the following:
`java.lang.NoClassDefFoundError: org/simplejavamail/email/EmailBuilder`

The code I was using:
```
        Email email = EmailBuilder.startingBlank()
                .to("RandomEmail@gmail.com")
                .withSubject("test")
                .withPlainText("hello")
                .buildEmail();

        Mailer mailer = MailerBuilder
                .withSMTPServer("smtp.gmail.com", 587, "MyEmail@gmail.com", "MyPassword")
                .withTransportStrategy(TransportStrategy.SMTP_TLS)
                .withSessionTimeout(10 * 1000)
                .clearEmailAddressCriteria()
                .withDebugLogging(true)
                .buildMailer();

        mailer.sendMail(email);
    }
```

**Comment by bbottema** [comment]
Did you get it working yet? Because this doesn't make sense to me, really.

**Comment by renatohendges** [comment]
I'm having the same problem, I downloaded simple-java-mail-5.0.3.jar, add to the build path, but the java.lang.NoClassDefFoundError: org/simplejavamail/email/ EmailBuilder, error appears, i use Oxygen.3a Release (4.7.3a)
Sorry for the google translator, I'm brazilian

**Comment by Willim7** [comment]
I am not sure what the problem is, I just tried out JavaMail to see if everything would work properly but the same thing happens a class is having issues being found. This is weird, I am using JDK 10 that might be the issue?

**Comment by bbottema** [comment]
So have you tried an earlier JDK?

**Comment by Willim7** [comment]
Hey, I switched everything to Java 8 and every class seems to be able to be found, weird must be something with Java 10 that might be a bug when it comes to compiling/shading classes with Maven. However I did end up getting an error which is:

`org.simplejavamail.mailer.MailerException: Email is not valid: missing sender`

The code I am using is the same as the code stated in my first post, just wondering what I am doing wrong, thank you!

**Comment by ethfun** [comment]
@Willim7 
I also Meet this issue

**Comment by bbottema** [comment]
> `org.simplejavamail.mailer.MailerException: Email is not valid: missing sender`
> 
> The code I am using is the same as the code stated in my first post, just wondering what I am doing wrong, thank you!

This is easier to explain at least. You have not provided a From or ReplyTo address. Either is necessary for the server to bounce mails back to, to identify you in case of an authenticated SMTP server and more to the point, to identify yourself to the receiver (you can't anonymously send an email as such).

Also see:
- https://stackoverflow.com/questions/4367358/whats-the-difference-between-sender-from-and-return-path
- https://tools.ietf.org/html/rfc4021#section-2.1.2
- https://tools.ietf.org/html/rfc2822#section-3.6.2
- https://tools.ietf.org/html/rfc822 (page 21)

**Comment by bbottema** [comment]
> Hey, I switched everything to Java 8 and every class seems to be able to be found, weird must be something with Java 10 that might be a bug when it comes to compiling/shading classes with Maven. However I did end up getting an error which is:
> 
> `org.simplejavamail.mailer.MailerException: Email is not valid: missing sender`
Strange indeed, I will look into this.

**Comment by bbottema** [comment]
A [patch was released](https://blogs.apache.org/maven/date/20180406) related to Java 10, but that was about getting the plugin to execute. Regardless, some other changes are included so I'll try this version and release a SNAPSHOT for you to try.

**Comment by bbottema** [comment]
@Willim7, can you please check if the problem persists with **6.0.0.beta-SNAPSHOT**. You'll need to [add the snapshot repo](https://stackoverflow.com/a/7717234/441662) for this.

**Comment by bbottema** [comment]
I've made the Outlook dependencies optional and so it is not shaded anymore. Shading is completely removed now.

**Comment by bbottema** [comment]
I've made the Outlook dependencies optional and so it is not shaded anymore. Shading is completely removed now.

@Willim7 I've updated and deployed the snapshot in the repository. It would be very helpful if you could check if the problem still persists with 6.0.0.beta-SNAPSHOT (you'll need to [add the snapshot repo](https://stackoverflow.com/a/7717234/441662)).

**Comment by bbottema** [comment]
@Willim7 , @ethfun, any update from your side?

**Comment by ethfun** [comment]
@bbottema ， yeah,  I Fixed the issue already , thank you for reminding !

**Comment by bbottema** [comment]
@ethfun But was it fixed with the beta I provided :D

**Comment by ethfun** [comment]
no ,  I missed the sender address ,  I just added a From address that you told us to solved this issue.

PS:  use JDK 8

**Comment by bbottema** [comment]
Ok well, since I'm not getting a response from @Willim7, I'll close this issue in the next week. There's nothing more to do for me right now.
