### ISSUE TITLE
OSGI support

### ISSUE THREAD

**Issue by castortech** [bbottema/simple-java-mail#147]
I provided a few days ago a pull-request to add OSGI info to the manifest. While this did part of the job, I did encounter a number of issues afterwards. The most important one the issue reported here:  #117. To fix it, I had to change the EMailConverter so that the call would be made from the default class loader and add the mimetypes. Another concern is the need to import the outlook parsers, even if not used (which in turn forces the loading of POI).

Before making changes and preparing a PR I would like to get your take on: adding a configuration to perform the classloader switch and having a more configurable way to avoid an automatic dependency on the outlook stuff.

Thanks

**Comment by bbottema** [comment]
> I had to change the EMailConverter so that the call would be made from the default class loader and add the mimetypes.
> (..)
> I would like to get your take on: adding a configuration to perform the classloader switch

I'm not sure what problem you are encountering and how switching class loaders fixes it. #117 is about mimetypes supported by the underlying Java Mail framework. Can you elaborate?

> and having a more configurable way to avoid an automatic dependency on the outlook stuff.

Good point. Fixed that in #150 just now, it's completely optional now.

**Comment by castortech** [comment]
The issue is that OSGI uses specific class loaders to manage code visibility and some code is not very friendly to this. Often switching the class loader to the class classloader is sufficient but here it is not.

So in this case I had to change the mimeMessageToEML method to force load a command map. This might be improved after some further debugging, but clearly the call to writeTo has to be wrapped in an OSGI environment.

See the modified code:
` public static String mimeMessageToEML(@Nonnull final MimeMessage mimeMessage) {
	final ByteArrayOutputStream os = new ByteArrayOutputStream();
	try {
		ClassLoader oldLoader = Thread.currentThread().getContextClassLoader();

		try {
			Thread.currentThread().setContextClassLoader(EmailConverter.class.getClassLoader());
			MailcapCommandMap mc = (MailcapCommandMap) CommandMap.getDefaultCommandMap();
			String[] mimeTypes = mc.getNativeCommands("multipart/*");
			if (mimeTypes == null || mimeTypes.length < 1) {
				mc.addMailcap("text/html;; x-java-content-handler=com.sun.mail.handlers.text_html"); 
				mc.addMailcap("text/xml;; x-java-content-handler=com.sun.mail.handlers.text_xml"); 
				mc.addMailcap("text/plain;; x-java-content-handler=com.sun.mail.handlers.text_plain"); 
				mc.addMailcap("multipart/*;; x-java-content-handler=com.sun.mail.handlers.multipart_mixed"); 
				mc.addMailcap("message/rfc822;; x-java-content-handler=com.sun.mail.handlers.message_rfc822");		
			}				
			checkNonEmptyArgument(mimeMessage, "mimeMessage").writeTo(os);
			return os.toString(UTF_8.name());
		} finally {
			Thread.currentThread().setContextClassLoader(oldLoader);
		}
	} catch (IOException | MessagingException e) {
		// this should never happen, so we don't acknowledge this exception (and simply bubble up)
		throw new RuntimeException(e.getMessage(), e);
	}
}`

What I am suggesting is to provide a clean way to allow an extension to wrap this call and maybe others that I have not found yet. Right now I can't extend and overwrite the method since its just a bunch of static, so a different approach has to be envisioned that allows the changes without necessarily forcing it on everyone and requiring a constant fork of the code.

**Comment by bbottema** [comment]
Hmm, that's a pretty nasty requirement.

There's one general approach for this I guess, which is to utilize AOP by defining an interceptor that wraps the method.

**Comment by bbottema** [comment]
If you have concrete suggestions I'm all ears, but for now I'm closing this issue as invalid (the problem seems to be OSGI not this library). However, I'm grateful for whatever work you put into this so far.
