### ISSUE TITLE
[Help] How to properly embed images?

### ISSUE THREAD

**Issue by abhi18av** [bbottema/simple-java-mail#152]
Hi @bbottema 

I'm really enjoying using this library so far - thanks 👍 

However, I'm unable to really use the Embedded Images feature - could you please guide me here?

I'm using `ammonite` shell for scala language - which is not really the issue here since it's perfectly compatible but I don't quite understand how to the `withEmbeddedImage` method 

```scala


import $ivy.`org.simplejavamail:simple-java-mail:5.0.3`
import org.simplejavamail.converter.EmailConverter;
import org.simplejavamail.email.Email;
import org.simplejavamail.email.EmailBuilder;
import org.simplejavamail.email.EmailPopulatingBuilder;
import org.simplejavamail.mailer.Mailer;
import org.simplejavamail.mailer.MailerBuilder;
import org.simplejavamail.mailer.config.TransportStrategy;


{

  var email = EmailBuilder.startingBlank()
          .from("abhinav", "abhinav@fourtek.com")
          .to("abhinav", "abhi18av@gmail.com")
          .withSubject("hey")
          .withHTMLText("<b>We should meet up!</b> <img src='cid:devnagri'>")
          .withPlainText("Please view this email in a modern email client!")
//          .withEmbeddedImage("devnagri", "/Users/eklavya/Downloads/devnagri-black.png")
          .withEmbeddedImage("devnagri", new File("/Users/eklavya/Downloads/devnagri-black.png"))
          .withHeader("X-Priority", 5)
          .buildEmail();


  var mailer = MailerBuilder
    .withSMTPServer("smtp.gmail.com", 587, "abhinav@fourtek.com", "123@123#")
    .withTransportStrategy(TransportStrategy.SMTP_TLS)
    .withSessionTimeout(10 * 1000)
    .buildMailer();

}

mailer.sendMail(email)


```

Please let me know what I'm doing wrong, I feel the issue lies here 

```scala
//          .withEmbeddedImage("devnagri", "/Users/eklavya/Downloads/devnagri-black.png")
          .withEmbeddedImage("devnagri", new File("/Users/eklavya/Downloads/devnagri-black.png"))
```

**Comment by bbottema** [comment]
Hi @abhi18av, so how it works is your provide either raw data as `byte[]` and provide the additional mimetype details, or you provide a [DataSource](https://docs.oracle.com/javase/7/docs/api/javax/sql/DataSource.html) that handles everything.

So you have a file on your disk that you want to use. You can either read the file yourself and then pass it directly to Simple Java Mail:

```
// read the file from disk yourself
byte[] imageData = ...;
.withEmbeddedImage("devnagri", imageData, 'image/png');
```
Or you can acquire it as a datasource somehow (manually or by using a library such as apache io or something):
```
DataSource imageDataSource = new FileDataSource(new File('path-to-image.png'));
.withEmbeddedImage("devnagri", imageDataSource);
```
I've not actually tested this code, but this is the gist of it. Let me know if anything is still unclear!
