### ISSUE TITLE
Possible error in the example

### ISSUE THREAD

**Issue by lucasjoao** [bbottema/simple-java-mail#153]
The [site](http://www.simplejavamail.org/#/configuration) has this example:
``` java
// trust all hosts for SSL connections, don't validate keys
currentMailerBuilder.trustingAllSSLHosts(true);
```
However I don't found this method in API, only `trustingAllHosts`. So the example has a problem?

**Comment by bbottema** [comment]
Yep, you're right, the documentation is behind! Thanks for the heads up, I'll have it fixed with the next release...

**Comment by bbottema** [comment]
In fact, aside from the type, there was a wrong example where `withSMTPPort` (`withSMTPServerPort`) was used instead of `withProxyPort`.

**Comment by bbottema** [comment]
As 6.0.0-rc1 was released, the new website is now live!

**Comment by bbottema** [comment]
6.0.0 has released as well, finally.
