### ISSUE TITLE
Suggestion - test connection async

### ISSUE THREAD

**Issue by lucasjoao** [bbottema/simple-java-mail#154]
Using the api I found one situation where I need make the `testConnection` async in the same way that is possible send a email async.

Today I solved this making the call to `testConnection` async, but I was thinking if will not be better the api provide this solution? What do you think @bbottema?

**Comment by bbottema** [comment]
In your situation, how are you handling exceptions in case `testConnection()` fails?

**Comment by lucasjoao** [comment]
Probably I will use callback to show some message to the user. Did I answer your question @bbottema? :thinking:

**Comment by bbottema** [comment]
Closing as suplicate of #148.
