### ISSUE TITLE
Can't verify Identity of server With Trust all hosts.

### ISSUE THREAD

**Issue by MrThreepwood** [bbottema/simple-java-mail#155]
I currently have my mailer builder setup to trust all hosts (a temporary work around, or so I thought, to see if mailing was working otherwise). However, even with this setup:

```
MailerBuilder
            .withSMTPServer("smtp.mailgun.com", 2525, Env.smtpUsername, Env.smtpPassword)
            .withTransportStrategy(TransportStrategy.SMTP_TLS)
            .withSessionTimeout(10 * 1000)
            .withDebugLogging(Env.debug)
            .trustingAllHosts(true)
            .buildMailer()
```

I'm getting the exception: 

`
Caused by: javax.mail.MessagingException: Could not convert socket to TLS;
  nested exception is:
	java.io.IOException: Can't verify identity of server: smtp.mailgun.com
	at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:2140)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:738)
	at javax.mail.Service.connect(Service.java:388)
	at javax.mail.Service.connect(Service.java:246)
	at javax.mail.Service.connect(Service.java:195)
	at org.simplejavamail.mailer.internal.mailsender.MailSender.sendMailClosure(MailSender.java:265)
`

I'm not entirely sure what's going on here.

**Comment by bbottema** [comment]
Can you verify that your mailer's session has the following property set?

```
Mailer yourMailer = MailerBuilder
            ...
            .buildMailer()

String sslTrust = yourMailer.getSession().getProperty("mail.smtp.ssl.trust");
System.out.println(sslTrust);
```

Should be "*".

**Comment by bbottema** [comment]
Have you tried the other ports?

> Mailgun supports sending via SMTP. Our servers listen on ports 25, 465 (SSL/TLS), 587 (STARTTLS), and 2525. - ([source pdf](https://media.readthedocs.org/pdf/mailgun-documentation/kristen-java-ex-docs/mailgun-documentation.pdf))

Also, have you tried it with the traditional JavaMail API and a custom session object (so without Simple Java Mail)? I'm wondering if that works (I'm expecting it doesn't if the other ports don't perform better).

**Comment by ScottPeterJohnson** [comment]
May or may not be helpful: I had a somewhat similar error getting the mailer to trust my localhost mailserver with bogus certificate.
`.withProperty("mail.smtp.ssl.checkserveridentity", "false")` sufficed to fix it.

**Comment by xcjiang** [comment]
same issue here, fixed by adding **.withProperty("mail.smtp.ssl.checkserveridentity", "false")**

**Comment by bbottema** [comment]
> same issue here, fixed by adding **.withProperty("mail.smtp.ssl.checkserveridentity", "false")**

Again, that's not a fix, but an insecure work-around.

**Comment by bbottema** [comment]
Ok, I finally decided to get set up with MailGun myself and test the original case.

I used the following code, like that from the first post:

```
Mailer mailer = MailerBuilder
	.withSMTPServer("smtp.mailgun.org", 2525, USERNAME, PASSWORD)
	.withTransportStrategy(TransportStrategy.SMTP_TLS)
	.trustingAllHosts(true)
	.buildMailer();

Email email = EmailBuilder.startingBlank()
	.from("email-I-registered-with-MailGun")
	.to("email-I-registered-with-MailGun")
	.withSubject("Mailgun test")
	.withPlainText("Mailgun body test")
	.buildEmail();

mailer.sendMail(email);
```
This worked fine for me, using Simple Java Mail 5.0.7. Also port 587 worked fine.

So I don't know what is going on with the other reports here. Perhaps you are using a different JavaMail dependency than Simple Java Mail is developed with (should be javax.mail:1.6.0). Otherwise I can only imagine it's a configuration issue with MailGun and how you set up your domains.

Unless there's a compelling argument that Simple Java Mail actually is bugged, I'm closing this issue for now.

**Comment by bbottema** [comment]
Related to https://github.com/bbottema/simple-java-mail/issues/221, which might solve this issue.
