### ISSUE TITLE
Can not parse email with blank email address headers

### ISSUE THREAD

**Issue by pyq** [bbottema/simple-java-mail#159]
For some incoming emails, it could be with header **Return-Path: <>**. This is possible for auto-replies emails.
This library always throws **MimeMessageParseException** when parsing those emails. 

[related code](https://github.com/bbottema/simple-java-mail/blob/master/src/main/java/org/simplejavamail/converter/internal/mimemessage/MimeMessageParser.java#L168)

**Comment by bbottema** [comment]
How do you propose I check if the value is empty (it's actually an invalid value according to the specs).

**Comment by bbottema** [comment]
I just implemented a simple empty check which checks for null, "" and "<>". Did this for Return-Path as well as Return-Receipt-To and Disposition-Notification-To.

Will be in release 6.0.0.

**Comment by bbottema** [comment]
Released in 6.0.0-rc1!

**Comment by bbottema** [comment]
6.0.0 has released as well, finally.
