### ISSUE TITLE
High CPU usage & geometrically increasing delay with increasing length of the recipient address

### ISSUE THREAD

**Issue by jusiponen** [bbottema/simple-java-mail#16]
Measured with *simple-java-mail-v2.1* and *javax.mail-1.5.1*

    05-05-2015 16:53:48: Sending email: rekry@fi.xyz.dom -> iitakeskus-kauppakeskus-rav.paallikko@fi.xyz.dom (3 attachments)
    05-05-2015 16:53:48: These attachments were sent:
    05-05-2015 16:53:48: Attachment 1 / 3 filename '108782_-_Sally-Ellen_Example.pdf', content type 'application/pdf'
    05-05-2015 16:53:48: Attachment 2 / 3 filename '108782_Sally-Ellen_Example_108782_-_Ansioluetteloni.pdf', content type 'application/pdf'
    05-05-2015 16:53:48: Attachment 3 / 3 filename '108782_Sally-Ellen_Example_108782_-_Hakemuskirje.pdf', content type 'application/pdf'
    05-05-2015 16:55:57: DEBUG Mailer - starting mail session (host: null, port: null, username: null, authenticate: null, transport: SMTP_PLAIN)
    
    05-05-2015 16:57:31: Sending email: rekry@fi.xyz.dom -> i-itakeskus-kauppakeskus-rav.paallikko@fi.xyz.dom (3 attachments)
    05-05-2015 16:57:31: These attachments were sent:
    05-05-2015 16:57:31: Attachment 1 / 3 filename '108782_-_Sally-Ellen_Example.pdf', content type 'application/pdf'
    05-05-2015 16:57:31: Attachment 2 / 3 filename '108782_Sally-Ellen_Example_108782_-_Ansioluetteloni.pdf', content type 'application/pdf'
    05-05-2015 16:57:31: Attachment 3 / 3 filename '108782_Sally-Ellen_Example_108782_-_Hakemuskirje.pdf', content type 'application/pdf'
    05-05-2015 17:01:20: DEBUG Mailer - starting mail session (host: null, port: null, username: null, authenticate: null, transport: SMTP_PLAIN)
    
    05-05-2015 17:16:47: Sending email: rekry@fi.xyz.dom -> ki-itakeskus-kauppakeskus-rav.paallikko@fi.xyz.dom (3 attachments)
    05-05-2015 17:16:47: These attachments were sent:
    05-05-2015 17:16:47: Attachment 1 / 3 filename '108782_-_Sally-Ellen_Example.pdf', content type 'application/pdf'
    05-05-2015 17:16:47: Attachment 2 / 3 filename '108782_Sally-Ellen_Example_108782_-_Ansioluetteloni.pdf', content type 'application/pdf'
    05-05-2015 17:16:47: Attachment 3 / 3 filename '108782_Sally-Ellen_Example_108782_-_Hakemuskirje.pdf', content type 'application/pdf'
    05-05-2015 17:25:24: DEBUG Mailer - starting mail session (host: null, port: null, username: null, authenticate: null, transport: SMTP_PLAIN)

*Summary*

Email address | Addr. Length | Start (hh:mm:ss) | Finish (hh:mm:ss) | Time taken | Delta
------------- | ------------ | ------------- | -------------- | ---------- | -----
iitakeskus-kauppakeskus-rav.paallikko@fi.xyz.dom | 48 | 16:53:48 | 16:55:57 | 0:02:09 | n/a
i-itakeskus-kauppakeskus-rav.paallikko@fi.xyz.dom | 49 | 16:57:31 | 17:01:20 | 0:03:49 | 0:01:40
ki-itakeskus-kauppakeskus-rav.paallikko@fi.xyz.dom | 50 | 17:16:47 | 17:25:24 | 0:08:37 | 0:04:48
hki-itakeskus-kauppakeskus-rav.paallikko@fi.xyz.dom | 51 | DID NOT MEASURE -- This is the address that brought this problem to attention |

I haven't verified with plain Java Mail if the problem persists.

**Comment by bbottema** [comment]
I think these might be regex related when validating the email addresses. In the next release (not scheduled yet), by default regex email address validation will be turned off.

**Comment by jusiponen** [comment]
Regexes sounds plausible, given the CPU/time double-whammy.

Any way to turn those checks off at runtime (let's assume we have validated all addresses previously)?

**Comment by bbottema** [comment]
Not yet. In the next release it will be turned off [by default](https://github.com/bbottema/simple-java-mail/issues/3) with the option to turn it on. Currently no workaround.

**Comment by jusiponen** [comment]
Ok, I'll take the sources and compile a private version for now.

Thanks!

**Comment by bbottema** [comment]
I just released [simple-java-mail 2.2](http://search.maven.org/#artifactdetails%7Corg.codemonkey.simplejavamail%7Csimple-java-mail%7C2.2%7Cjar) to maven central. Can you please have a go with it and see if the issue still persists?
