### ISSUE TITLE
Improve support for converting emails to Outlook messages

### ISSUE THREAD

**Issue by bbottema** [bbottema/simple-java-mail#162]
Simple Java Mail supports reading Outlook messages to EML, MimeMessage and Email, but not back to Outlook messages. This should be possible with some changes to https://github.com/bbottema/outlook-message-parser.

**Comment by bbottema** [comment]
It seems Java options are very limited. The one library that seems to be able to do something, is very limited and obstructed by the difficult Outlook file spec.

This doesn't seem a viable path right now.

**Comment by imranrajjad** [comment]
Do you plan to add support for voting buttons? As in Send and Read Voting response?

**Comment by bbottema** [comment]
As far as I know this is not an open source RFC spec, but Outlook proprietary format. Simple Java Mail can only read outlook message (limited capability, as provided by [outlook-message-parser](https://github.com/bbottema/outlook-message-parser)), but not create and send them, only the general email as defined by the [Multipurpose Internet Mail Extensions (MIME)](https://en.wikipedia.org/wiki/MIME) internet standard, which includes a bunch of RFCs, including Calendar.

**Comment by imranrajjad** [comment]
@bbottema moving forward, can the Calender implementation be taken as a base example to implement this support? Unfortunately this is way beyond me but I can surely dedicate someone from myside to extend the API if we are pushed in the right direction.

**Comment by bbottema** [comment]
I don't think this is going to be possible, as this behavior is not part of any MIME specification and as such not supported by the underlying low-level Java mailing framework Jakarta Mail. But more to the point: voting buttons are a tracking feature of Outlook specifically, backed by an Exchange server which keeps track of the votes. This is all managed through Outlook itself (as a email and exchange client, rather than an email viewer).

So it doesn't make sense to do this from Java or anything other than Outlook itself.

**Comment by imranrajjad** [comment]
>voting buttons are a tracking feature of Outlook specifically, backed by an Exchange server which keeps track of the votes

Well I do not wish to track anything, only send an email with Voting buttons and read the response when the recipient selects a voting option, leaving the tracking completely to the exchange server. Anyway, thanks for the feedback
