### ISSUE TITLE
Support international email addresses

### ISSUE THREAD

**Issue by DaveJarvis** [bbottema/simple-java-mail#166]
# Background
Add support for internationalized email addresses. See:

* https://tools.ietf.org/html/rfc3490
* https://tools.ietf.org/html/rfc5322
* https://tools.ietf.org/html/rfc6532
* https://tools.ietf.org/html/rfc6530
* https://www.w3.org/TR/html5/forms.html#valid-e-mail-address
* https://github.com/w3c/html/issues/845

# Replicate
```
final EmailPopulatingBuilder builder = EmailBuilder.startingBlank();
builder.from("аджай@экзампл.рус");
// ...
final Email email = builder.buildEmail();
final Mailer mailer = MailerBuilder.buildMailer();
// ...
mailer.sendMail(email);
```

Also, try these:

* French: François.Jacob@château.net
* Chinese: 用户@例子.广告
* Hindi: अजय@डाटा.भारत
* Ukrainian:  квіточка@пошта.укр
* Greek: θσερ@εχαμπλε.ψομ
* German: Dörte@Sörensen.example.com

# Expected Results
Email is sent.

# Actual Results
```
 org.simplejavamail.mailer.MailerException: Invalid FROM address: Email{
	id=null
	fromRecipient=Recipient{name='Александр Михайлович Лесной', address='аджай@экзампл.рус', type=null},
	replyToRecipient=null,
	bounceToRecipient=null,
	text='Hello, world! Voilà ! Le vieux château. À bientôt ! 一蓮托生',
	textHTML='',
	subject='Message subject line',
	recipients=[Recipient{name='null', address='username@localhost', type=To}]
}
	at org.simplejavamail.mailer.Mailer.validate(Mailer.java:276)
	at org.simplejavamail.mailer.Mailer.sendMail(Mailer.java:238)
	at org.simplejavamail.mailer.Mailer.sendMail(Mailer.java:230)
	at ca.bc.gov.educ.isd.notification.service.impl.EmailPayloadImpl.deliver(EmailPayloadImpl.java:171)
	at ca.bc.gov.educ.isd.notification.service.impl.EmailPayloadImpl.send(EmailPayloadImpl.java:96)
	at ca.bc.gov.educ.isd.notification.service.impl.EmailNotificationServiceBean.send(EmailNotificationServiceBean.java:25)
	at ca.bc.gov.educ.isd.notification.service.impl.EmailNotificationServiceBean.send(EmailNotificationServiceBean.java:9)
	at ca.bc.gov.educ.isd.notification.EmailNotificationServiceTest.send(EmailNotificationServiceTest.java:263)
	at ca.bc.gov.educ.isd.notification.EmailNotificationServiceTest.testEmailSend_OnRecipientBodySubjectI18N_ShouldDeliverMessageToRecipient(EmailNotificationServiceTest.java:69)
```

# Workaround

Tried to disable validation as follows:

```
MailerBuilder.withEmailAddressCriteria(EnumSet.noneOf(EmailAddressCriteria.class))
```

This failed because the API does not permit setting the criteria to `null`, which is the entering condition for the `validate` method:

https://github.com/bbottema/simple-java-mail/blob/master/src/main/java/org/simplejavamail/mailer/Mailer.java#L287

Since `MailerGenericBuilder` assigns the email address criteria [during construction](https://github.com/bbottema/simple-java-mail/blob/master/src/main/java/org/simplejavamail/mailer/MailerGenericBuilder.java#L154) and the methods to assign the validation enum set are tagged `@Nonnull`, it seems there is no way to avoid triggering validation (with or without an enum set).

This appears to be a minor oversight.

**Comment by bbottema** [comment]
Thanks for the bug report. This is a tough one, because the email validation library used doesn't support special symbols.

https://github.com/bbottema/email-rfc2822-validator/issues/9

I'm not sure how to proceed here.

**Comment by DaveJarvis** [comment]
If there was a global control for these conditions, as per #167, then this would not be an issue. I could use the Java Mail API directly to perform email address validation and then continue using the SimpleJavaMail API for the remaining work.

**Comment by bbottema** [comment]
Nice, in al my Java Mail adventures I've not come across Java Mail's SAD! I'll study it carefully.

To get back to the issue, you can actually turn off email validation so only the injection checks remain. This is [standard API](http://www.simplejavamail.org/#/features):

```java
currentMailerBuilder
   .clearEmailAddressCriteria()
   (..)
```

**Comment by bbottema** [comment]
> Since MailerGenericBuilder assigns the email address criteria during construction and the methods to assign the validation enum set are tagged @Nonnull, it seems there is no way to avoid triggering validation (with or without an enum set).
>
> This appears to be a minor oversight.

In light of this statement, let me double check my previous suggestion.

**Comment by DaveJarvis** [comment]
Fixing issue #167 will make this issue no longer relevant. Closing.

**Comment by bbottema** [comment]
Current 9.x usage (verified against 9.3.2):

```java
Mailer mailer = MailerBuilder
    .withSMTPServer("smtp.example.com", 587)
    .clearEmailValidator()
    .buildMailer();
```

The old email-address criteria API was replaced when 7.0 switched validation to JMail. `clearEmailValidator()` clears only the configurable address policy; required sender/recipient checks, encoded-word protection, and CRLF scanning remain active. See the [7.0 validation migration](https://www.simplejavamail.org/migration-notes-7.0.0.html#email-validation) and [current validation documentation](https://www.simplejavamail.org/features.html#section-email-validation).
