### ISSUE TITLE
withAttachment throws exception on 0-byte attachment

### ISSUE THREAD

**Issue by jcracknell** [bbottema/simple-java-mail#169]
I would argue that an empty file is a valid attachment.

**Comment by DaveJarvis** [comment]
I cannot confirm this bug. Here's the code from my unit test:

```
        createPayload().addAttachment("filename.txt", new byte[0]);
```

This successfully sends an email with a 0-byte attachment:

![attachment-01](https://user-images.githubusercontent.com/2131950/46099438-a1884280-c17b-11e8-9526-827e76641f37.png)
![attachment-02](https://user-images.githubusercontent.com/2131950/46099439-a1884280-c17b-11e8-9b84-95b718dedf14.png)
![attachment-03](https://user-images.githubusercontent.com/2131950/46099440-a1884280-c17b-11e8-8771-7bf1a0a93259.png)

**Comment by jcracknell** [comment]
I should have clarified - with an empty byte array:
https://github.com/bbottema/simple-java-mail/blob/82ee53600b8e88b14fd04673a957deb520c6ddf4/src/main/java/org/simplejavamail/email/EmailPopulatingBuilder.java#L1205

**Comment by bbottema** [comment]
So please provide an code example where the error occurs.

**Comment by jcracknell** [comment]
I'm using this from a scala project, but `withAttachment(string, byte[], string)` pretty clearly checks for an empty array:

```
scala> :paste
// Entering paste mode (ctrl-D to finish)

org.simplejavamail.email.EmailBuilder.startingBlank()
.withAttachment("empty.txt", Array.empty[Byte], "text/plain")

// Exiting paste mode, now interpreting.

java.lang.IllegalArgumentException: data is required
  at org.simplejavamail.internal.util.Preconditions.checkNonEmptyArgument(Preconditions.java:15)
  at org.simplejavamail.email.EmailPopulatingBuilder.withAttachment(EmailPopulatingBuilder.java:1211)
  ... 44 elided
```

It could be worth throwing on an empty byte array, but it seems like it's just burdening users with unnecessary edge cases to handle.

**Comment by bbottema** [comment]
I'm not sure what the problem is here, either you wish to attach something or you don't. Invoking the attachment API without actual attachment (empty data) seems like an error to me.

**Comment by DaveJarvis** [comment]
While logically it appears to be an error, there may be circumstances whereby an empty attachment is valid. Also, technically speaking, sending an empty attachment does not violate the RFCs, as far as I know.

That said, given the number of errors people encounter while sending attachments, it is probably best left as an exception case, pending a strong use case.

**Comment by jcracknell** [comment]
My particular usage scenario was generating a CSV attachment from an empty record set. I resolved the issue by adding a byte order mark to the output (`'\uFEFF'`) so that it was no longer empty.
