### ISSUE TITLE
it only sends mail, doesn't read it.

### ISSUE THREAD

**Issue by kaigouthro** [bbottema/simple-java-mail#172]
you need to change the name to simple-jave-mail"ER"...

that's my issue.

do the same aesome job of making sending mail easy
and apply that to imap... then you'll be my heroes

**Comment by bbottema** [comment]
Haha. Well maybe one day I'll move it forward into mail reading, for now I want Simple Java Mail to be stable and well tested. Upcoming version 6.0.0 is a big one, after that I might just go down that route.
