### ISSUE TITLE
Simple Java Mail needs a logo

### ISSUE THREAD

**Issue by bbottema** [bbottema/simple-java-mail#176]
I'm just going to leave this here.

Simple Java Mail is now over 12 years old and I think it should have its own logo finally. Something flat and simple, something like the [Postman logo](https://www.getpostman.com/img/v2/logo-glyph.png).

I have no idea how one would visualize what it is that Simple Java Mail does (quite a lot nowadays), but its power has always been **ease of use**. If anything, it's ergonomic if such a thing is even possible in technical libraries.

Ideas/suggestions very welcome.

**Comment by DaveJarvis** [comment]
There are a number of automated AI-driven online tools that are mostly free. It's easy enough to use them to generate an idea and then trace them in Inkscape to generate a scalable vector graphic.

**Comment by bbottema** [comment]
I'm also not averse to buying a stock photo. Here, someone is happy about their emails:

![java-mail](https://media.istockphoto.com/vectors/email-vector-icon-isolated-on-transparent-background-email-logo-vector-id1042599762)

**Comment by DaveJarvis** [comment]
In that case, consider putting forward a project on https://99designs.ca/.

**Comment by bbottema** [comment]
> In that case, consider putting forward a project on https://99designs.ca/.

I've had some positive (and affordable) experience with [DesignCrowd](https://www.designcrowd.com/) as well. Here's a good [write-up on the differences](https://99designs.nl/blog/crowdsourcing/99designs-vs-designcrowd-whats-the-difference/).

**Comment by bbottema** [comment]
Closing as not needed right now. I quite like the current text-based logo from simplejavamail.org. It will do for now.
