### ISSUE TITLE
Microsoft Exchange Server

### ISSUE THREAD

**Issue by dokala** [bbottema/simple-java-mail#18]
Can we send mails using microsoft exchange server, if yes, please suggest a sample. thanks Aravind

**Comment by bbottema** [comment]
If the exchange server supports standard SMTP, then sure. I think the Exchange server [needs to be configured](https://support.microsoft.com/en-us/kb/265293?wa=wsignin1.0) for SMTP first?

**Comment by dokala** [comment]
Hi,
MS exchange server is not smtp support., I tried ews-java-api., it is giving connection reset error when email message has been try to send... Please suggest.
Regards,
Aravind

**Comment by bbottema** [comment]
I don't have experience with Exchange or ews-java-api. This library will work with any server that properly implements the SMTP specification.
