### ISSUE TITLE
Add option to Ignore invalid receiver addresses

### ISSUE THREAD

**Issue by zwqdavid007** [bbottema/simple-java-mail#180]
If one of email address is invalid, it will cause the entire message to fail.
Is there a way filter the invalid address, and send the email success?

**Comment by bbottema** [comment]
Actually, I was already adding a flag on MailerBuilder for ignoring failed email validation, when I realized that's the same as turning validation off completely.

To answer your question, yes that's already possible:
```java
currentMailerBuilder
   .clearEmailAddressCriteria()
   (..)
```
