### ISSUE TITLE
Update JavaMail dependency to 1.6.2, adding support for authenticated HTTP web proxy

### ISSUE THREAD

**Issue by bbottema** [bbottema/simple-java-mail#186]
In JavaMail 1.6.0 HTTP proxy support was added and in 1.6.2 authentication was added [as well](https://javaee.github.io/javamail/docs/CHANGES.txt). Simple Java Mail should support this in the builder API as well.

JavaMail has moved btw: 
Project home: https://eclipse-ee4j.github.io/javamail/ 
Code home: https://github.com/eclipse-ee4j/javamail

The following [properties](https://javaee.github.io/javamail/docs/api/com/sun/mail/smtp/package-summary.html) are concerned:

| property | type | description |
| -- | -- | -- |
| mail.smtp.proxy.host | string | Specifies the host name of an HTTP web proxy server that will be used for connections to the mail server. |
| mail.smtp.proxy.port | string | Specifies the port number for the HTTP web proxy server. Defaults to port 80. |
| mail.smtp.proxy.user | string | Specifies the user name to use to authenticate with the HTTP web proxy server. By default, no authentication is done. |
| mail.smtp.proxy.password | string | Specifies the password to use to authenticate with the HTTP web proxy server. By default, no authentication is done. |

SOCKS authentication is still not supported by JavaMail, so Simple Java Mail's [SOCKS](http://www.jguru.com/faq/view.jsp?EID=227532) (v5) authentication is still relevant.

**Comment by Flashky** [comment]
Oh god, I need this so much 👍 

Thank you for your efforts!
Besides this, I have a question about license, if I'm my project I'm using your SimpleJavaMail library, do I have to  mention the license? or just if I modify it?

At least, for now I mention you on my README.md to give you credit for this awesome library. :)

**Comment by bbottema** [comment]
Hi @Flashky, please refer to https://tldrlegal.com/license/apache-license-2.0-(apache-2.0) on the right side under _Must_.

**Comment by bbottema** [comment]
Updated javax.mail version for upcoming  release 6.0.0.
