### ISSUE TITLE
Send multiple emails per session connection

### ISSUE THREAD

**Issue by petarov** [bbottema/simple-java-mail#198]
Hi! This is more of a question rather than an issue.

I'm working on an implementation that has to send many emails using one and the same SMTP server. I saw that async sending is already supported which is pretty cool! However, I was looking for a way to send many emails synchronously over an already established TCP connection.

Browsing the MailSender code I stumbled on [this part](https://github.com/bbottema/simple-java-mail/blob/c0838ccefdef1a88c595fca1d92f3d5375531e27/modules/simple-java-mail/src/main/java/org/simplejavamail/mailer/internal/mailsender/MailSenderImpl.java#L261). I think this opens a new connection for each email, right? Does it make sense to improve this, so that it reuses the transport/session to send several messages synchronously?

**Comment by bbottema** [comment]
Hi @petarov, it could be an improvement, but I'm unaware of any performance issues with creating new connections for emails. Do you have more experience with this (sending emails in large bulks)?

**Comment by petarov** [comment]
Thanks for the feedback @bbottema! I'd like to reuse the connection so that that same underlying tcp socket gets used for sending bulk (hundreds  to thousands of emails) of data. I'm generally trying to squeeze as much performance as possible for a product I'm working.

That being said, I don't have any data to compare the performance at the moment, but I'll try to prepare some and come back to you with numbers for a better overview.

**Comment by petarov** [comment]
Ok, here are a bunch of, let's call them _naïve_, tests using SimpleMail and just plain JavaMail with [Transport.sendMessage()](https://docs.oracle.com/javaee/6/api/javax/mail/Transport.html#sendMessage(javax.mail.Message,%20javax.mail.Address[])). I've used [FakeSMTP](http://nilhcem.com/FakeSMTP/) as an SMTP server to perform the tests. Test email size = 15Kb.

It can be observed in SMTP protocol handshake that the `JavaMail+sendMessage` variant does not close the connection, but rather keeps sending emails after `EHLO` was initially sent. The results from my tests are below. The client code's running on a macOS machine and the SMTP server on a remote Linux server.

The elapsed time results as a mean are irrelevant, but the difference does seem to be around 2x in favour of `JavaMail+sendMessage`.

Method | Emails Count | Elapsed Time
------------ | -------------|-------------
SimpleMail | 100 | 40,71 seconds
JavaMail+sendMessage | 100 | 21,11 seconds
SimpleMail | 1000 | 404.71 seconds (6m 45s)
JavaMail+sendMessage | 1000 | 198.70 seconds (3m 18s)
SimpleMail | 10,000 | 3921,03 seconds (1h 5m 22s)
JavaMail+sendMessage | 10,000 | 1954,81 seconds (32m 35s)

Of course, I might have missed something on the code side, so [here's the repo](https://github.com/petarov/simplemail-javamail-tests), if you'd like to take a look.

And finally, I actually think that 2x is not that much of an issue for my use case (~500 max), so this issue could be closed. I can live with SimpleMail working as it is at the moment. 😉

**Comment by bbottema** [comment]
Can you please add a third approach of JavaMail send message without reusing the connection? I'm curious to know how much overhead Simple Java Mail adds.

**Comment by petarov** [comment]
Sure, so I tested 4 variants.

**Variant 1** - SimpleMail. (Default Mailer, no threading parameters.)
**Variant 2** - Transport.send()
```java
Transport.send(msg);
```
**Variant 3** - Transport+getInstance()+connect()+sendMessage(). 
```java
        try (Transport t = session.getTransport()) {
            t.connect();
            t.sendMessage(msg, msg.getAllRecipients());
        } finally {
            // do nothing
        }
```
**Variant 4** - transportInstance.sendMessage(). Same as [JavaMail+sendMessage](https://github.com/bbottema/simple-java-mail/issues/198#issuecomment-480415609) in my tests above. Transport instance is created once and it's used for each email being sent.
```java
        if (!transport.isConnected())
            transport.connect();
        transport.sendMessage(msg, msg.getAllRecipients());
```

### Results

\#  | Method | Emails Count | Elapsed Time
--|------------ | -------------|-------------
1 |SimpleMail | 100 | 38,64 seconds
2 |SimpleMail+10 Threads | 100 | 0,14 seconds
3 |Transport.send()| 100 |  38,16 seconds
4 |Transport+getInstance()+connect()+sendMessage()| 100 |  38,79 seconds
5 |transportInstance.sendMessage()| 100 |  19,22 seconds

No doubt, SimpleMail + threads is the fastest variant, if threading is desired. 😎

**Comment by bbottema** [comment]
Excellent work, thank you!

**Comment by bbottema** [comment]
Hi @petarov, I've been re-implementing how threads are handled for #207. Any change you could run your tests on branch [207-configurable-threadpoolexecutor](https://github.com/bbottema/simple-java-mail/tree/207-configurable-threadpoolexecutor) to see if the performance didn't degrade somewhere?

**Comment by petarov** [comment]
Hi @bbottema, Sounds great! I'll try to do that this weekend and let you know.

**Comment by petarov** [comment]
Ok, I had a few problems adjusting the dependencies, but here we go. I did several runs per email count test and I believe there are no deviations from what tests showed in version `5.1`.

\#  | Method | Emails Count | Elapsed Time
--|------------ | -------------|-------------
1 |SimpleJavaMail RUN 1| 100 | 38,64 seconds
2 |SimpleJavaMail RUN 2| 100 | 39,37 seconds
3 |SimpleJavaMail RUN 3| 100 | 40,71 seconds
4 |SimpleJavaMail+10 Threads RUN 1| 100 | 0,25 seconds
5 |SimpleJavaMail+10 Threads RUN 2| 100 | 0,30 seconds
6 |SimpleJavaMail+10 Threads RUN 2| 100 | 0,26 seconds

**Comment by bbottema** [comment]
Excellent, thank you so much.

**Comment by bbottema** [comment]
I've been looking into reusing Transport connections, but I'm not yet happy with my options. Basically what we need is a generic object pool for reusing creation-expensive objects. There are a [bunch](https://github.com/chrishantha/object-pool-benchmarks) of those, but I rather not resort to a 3rd party library for this.

Got any ideas?

**Comment by bbottema** [comment]
One snag is that for each email, there's a change the session should be mutated (to configure bounceToEmail). A session is generally reusable, but not in that case.

Maybe I need to find a way to set this property when actually sending it, so that it doesn't end up in the session instance at all...

**Comment by bbottema** [comment]
As usual, I'm confusing myself more and more.

I think I don't need an object pool, but a cache with an upperbound

**Comment by petarov** [comment]
Good question @bbottema. Could you elaborate on reusing the Transport connections part? Are they really a good candidate for pooling? I see this more as a single continuous batch operation, so if you mean a new module with implementation dedicated only to a sending Emails in a single-threaded fashion, that sounds to me pretty cool already. 

As to object pooling solution, I'm mostly using Google [Guava's Cache](https://github.com/google/guava/wiki/CachesExplained#applicability) in my projects, although from the [synopsis on Stormpot's performance](http://chrisvest.github.io/stormpot/performance.html) it does look somewhat more advanced than Guava to me. As far as I could glance in [BlazePool's implementation](https://github.com/chrisvest/stormpot/blob/master/src/main/java/stormpot/BlazePool.java), there're no synchrnoized code blocks on read/write. Guava's Cache is backed by a `ConcurrentMap`, so that might be an overkill for single-threaded batch processing. 

Strangely enough, I think the `QueuePool` got deleted from Stormpot, but I couldn't find out why. 🙂 

```
One snag is that for each email, there's a change the session should be mutated (to configure bounceToEmail). A session is generally reusable, but not in that case.
```
Good point. If possible, I'd personally just discard that feature at first, until someone explicitly say they need it.

**Comment by bbottema** [comment]
Actually, I found a way around that limitation, by using an `SMTPMessage` instead of a `MimeMessage`, which is a subclass of `MimeMessage` and overrides bounceTo (envelope-from) of the Session (so we can just leave that empty now).

I'm reluctant to rely on a large general-purpose library just for its caching support, so that's why I didn't go with Guava. I'm now on my way with a first implementation though using Stormpot and will start testing soon!

From Stormpot's documentation, there should still be a QueuePool implementation next to BlazePool. Anyway, I have to stick with 2.4.1, because 3.0.0 will require Java 8+, which I'm not ready to have as a requirement for Simple Java Mail.

**Comment by petarov** [comment]
> I do intend to allow for multiple Transport connections though (hence Stormpot), because that can improve performance significantly if your mailserver can handle it 

Alright, that sounds pretty good. 

> Anyway, I have to stick with 2.4.1, because 3.0.0 will require Java 8+, which I'm not ready to have as a requirement for Simple Java Mail.

As someone that has to support commercial Java 1.6 software, I can understand that. However, I'd encourage you to not delay the Java 8 push, if you can help it. Cheers 🍺

**Comment by bbottema** [comment]
Closed in favor of #214, which covers more use cases.

**Comment by bbottema** [comment]
Hi @petarov, I finished the batch module, which now supports everything you can think of.

Without the Batch Module, Simple Java Mail behaves as it did before, with a single Transport connection being created for each email. With the Batch Module included however, it defaults to 4 Transport connections that can be reused and even pre-started (kept warmed up). You can even configure a cluster of servers each with 4 Transport connections or any other number. 

You can even define multiple clusters if you plan on using different routes for different types of email (like internal mail and external mail).

It's in the develop branch, so you might wanna give it a spin. I would love to be able to mention some mind blowing statistics in the 6.0.0 release!! The updated website with documentation is now simply statically compile HTML files, [here](https://github.com/simple-java-mail/angular-app/tree/develop/dist).

**Comment by bbottema** [comment]
Hey @petarov, advanced and improved batch processing is released in  6.0.0-rc1! Check out the renewed website...

**Comment by petarov** [comment]
Hi @bbottema, that's great to hear! I hope to get some free time on the weekend to try it out. Hopefully I can also do some tests and upgrade to 6.0.0 till the end of the month. 😉

**Comment by petarov** [comment]
Hi @bbottema 

I finally got around to do [some tests](https://github.com/petarov/simplejavamail-javamail-tests). It looks pretty good and I'll be integrating version `6.0.1` in my project next week. 

### Test Parameters

  * simplejavamail `6.0.1`
  * javax.mail `1.6.2`
  * 100 emails sent to a remote SMTP server
  * Average remote SMTP server ping `50 ms.`

### Results

\#  | Method | Emails Count | Average Elapsed Time
--|------------ | -------------|-------------
1 |SimpleJavaMail with 10 threads | 100 | 0,12 seconds
2 |SimpleJavaMail with Connection Pool* | 100 | 16,6 seconds
3 |transportInstance.sendMessage()| 100 |  19,22 seconds

`*` Connection Pool Parameters

  - `withConnectionPoolCoreSize` = 4
 - `withConnectionPoolMaxSiz` = 4

I can only say, well done! 👍

**Comment by bbottema** [comment]
Is that 0,12 seconds correct?

**Comment by petarov** [comment]
Hmm, now that you've mentioned it, I've noticed that the threaded version did not send any mails to the SMTP server. There's this exception thrown in `AsyncResponse.onException()`.

```java
java.lang.IllegalStateException: Cluster contains no pools to draw from
        at org.bbottema.clusteredobjectpool.core.ResourceClusters.cycleToNextPool(ResourceClusters.java:182)
        at org.bbottema.clusteredobjectpool.core.ResourceClusters.claimResourceFromCluster(ResourceClusters.java:122)
        at org.simplejavamail.internal.batchsupport.BatchSupport.acquireTransport(BatchSupport.java:112)
        at org.simplejavamail.mailer.internal.util.TransportRunner.runOnSessionTransport(TransportRunner.java:71)
        at org.simplejavamail.mailer.internal.util.TransportRunner.sendMessage(TransportRunner.java:47)
        at org.simplejavamail.mailer.internal.SendMailClosure.executeClosure(SendMailClosure.java:78)
        at org.simplejavamail.mailer.internal.AbstractProxyServerSyncingClosure.run(AbstractProxyServerSyncingClosure.java:56)
        at org.simplejavamail.internal.batchsupport.AsyncOperationHelper$1.run(AsyncOperationHelper.java:74)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

```

Maybe it's a misunderstanding on my side with the configuration, although I've checked the docs.

```java
        MailerRegularBuilderImpl builder = MailerBuilder
                .withSMTPServer(smtpHost, smtpPort)
                .withTransportStrategy(TransportStrategy.SMTP)
                .withSessionTimeout(10 * 1000)
                .clearEmailAddressCriteria()
                .withDebugLogging(true)
                .withThreadPoolSize(10);
```

Am I missing something?

**Comment by bbottema** [comment]
Threads or not should have no bearing on how the connection pool is used, so it's probably a bug. I suspect something about the cluster key propagating properly among threads.

I'll have to dive into it soon.

**Comment by bbottema** [comment]
Hmm, I tried to run through the code, but everything seems perfect. Each operation encapsulated in a thread by the same mailer has the same operational config with the same clusterkey. And it doesn't matter if the send-closure is run directly or from within those threads. I'll have to try with FakeSMTP I guess.

**Comment by bbottema** [comment]
Actually, a thought occurred to me. This can only occur if the pool was shut down and then reused. On shut down, the connection pools are discarded, but the cluster key remains. If you then try to reuse the cluster key, this exception is thrown.

Is it possible, you are shutting down the connection pool [here](https://github.com/petarov/simplejavamail-javamail-tests/blob/master/src/main/java/com/company/Main.java#L77), before the threads are done sending? That would explain the 0,12 seconds ;)

**Comment by petarov** [comment]
Yeah, that was a bummer. The test did not wait on the `AsyncResponse` futures to complete. It seems my older tests were also compromised by this. I totally overlooked it. 

It looks much more realistic now at `4,47 sec.`. I've updated the table above. 😉 

Still, I'm unsure when/how to call `mailer.shutdownConnectionPool()`. If I invoke `mailer.shutdownConnectionPool().get()` when all messages get sent, it just seems to block indefinitely.  Any advice on that?

**Comment by bbottema** [comment]
I can imagine two methods for shutting down:

- The current one that waits for shutdown or times out with exception
- A new one that waits for shutdown or forces a shutdown

Regarding your question on how to use the current one: if your threads are done, it should definitely not block indefinitely. That's would probably be a bug.

One possibility is that while sending an email in a thread fails, the claimed Transport is not released back into the pool. Then the pool blocks indefinitely because it waits for all resources to free up.

**Comment by petarov** [comment]
> Did you verify all mails sent without issue?

Yep, they are all being sent successfully. I did a simple 10 emails tests. All received and no exception was reported by `AsyncResponse.onException()`.

Interestingly enough, if I just create a new mailer and invoke `mailer.shutdownConnectionPool().get()` without sending any Emails, it also blocks indefinitely. 🤔

**Comment by bbottema** [comment]
Yep it's a bug. The combined Futures of all pools being shutdown are aggregated into a FutureTask which itself is never run (the pools do shutdown, but the future task doesn't perform the wait closure) so it never completes and hence `.get()` block indefinately. Whoops.

**Comment by bbottema** [comment]
Actually were are a bunch of issues where executor services were not shut down properly, the aggregate pools shutdown future task not executing (and implemented wrong).

I'm fixing all these issues under #246.

**Comment by bbottema** [comment]
6.0.2 released, all shutting down issues should be gone now!

**Comment by bbottema** [comment]
With that out of the way, could you please add a test with both multiple threads and a connection pool? Also please post the system details (cpu, memory etc.) of both the client and server system. This would give a more complete idea of the performance and I'll include it on the website as a rough reference performance!

**Comment by petarov** [comment]
Ok, it all looks good in `6.0.2` so far. 

Here's the input you requested, but I'm not sure if this is something to put on the website. I expect the results will definitely very when using a real SMTP server. It's your call. 😉 

### Test Parameters

  * simplejavamail `6.0.2`
  * javax.mail `1.6.2`
  * 100 emails sent to a remote SMTP server with average ping `~50 ms.`
  * Client - `macOS Catalina, 8 CPU, 16 GB RAM, AdoptOpenJDK 11`
  * Server - `CentOS Linux, 6 CPU, 12 GB RAM, OpenJDK 1.8`, [FakeSMTP](http://nilhcem.com/FakeSMTP/) as server*

### Results

 Test | Emails Count | # 1 |# 2 | # 3 | Average Elapsed Time
------------ | -------------|---------------|--------|-----------|-------------
SimpleJavaMail with 10 threads | 100 | 4.41 |   4.56 |     4.71 | 4.56 sec.
SimpleJavaMail with Connection Pool | 100 | 16.64|   16.50|     16.91| 16.68 sec.
JavaMail Transport | 100 | 19.60|   18.82|     19.93| 19.45 sec.

* Both threaded and connection pool tests were done with the default parameters in the `MailerRegularBuilderImpl` builder. No customizations of the thread pool or connection pool sizes.

* FakeSMTP ran in memory mode, no mails were saved on disk, using `java -jar fakeSMTP-2.0.jar -m -s -b -p <port>`

**Comment by bbottema** [comment]
Ok, maybe I'm misunderstanding, but I still miss a test with both multiple threads and a connection pool (as a combo).

**Comment by petarov** [comment]
Just did an update of my comment above. TBH, I'm a bit unsure of the exact specifics of how the threads and connection pools are working together, but the performance does seem to improve as I increase the number of threads and connection pool max size. So, it is more or less what I would have expected.

A cluster run would be a challenge. Can't promise anything, but perhaps if time permits.

**Comment by bbottema** [comment]
Yeah, don't feel pressured at all, you did so much already.

**Comment by bbottema** [comment]
So we ran into this bug, which I think makes all your tests invalid? (crap)
