### ISSUE TITLE
Website is broken

### ISSUE THREAD

**Issue by ratuka** [bbottema/simple-java-mail#199]
On http://www.simplejavamail.org/#/debugging you mention the following:

Mailer mailer = new Mailer(...);
mailer.setTransportModeLoggingOnly(true);

But there is no such method because of the builders :)  Maybe you can mention MailerGenericBuilder.withTransportModeLoggingOnly() here.

**Comment by bbottema** [comment]
Ahh, thanks! I'll get it sorted out.

**Comment by bbottema** [comment]
Documentation updated.
