### ISSUE TITLE
Question / Request

### ISSUE THREAD

**Issue by C4J** [bbottema/simple-java-mail#203]
Odd as it may seem I would like to have program that will be able to poll for messages in the inbox and save the attachments found in the email to a folder.

Does the API have this capability.

In case your wondering I would like to transfer messages between systems by attaching an xml at the sending side and saving it for processing at the receiving end.

**Comment by bbottema** [comment]
Hi! 

Simple Java Mail is an SMTP wrapper, so it only supports sending emails, not receiving emails which is POP3/IMAP. Not yet anyway.
