### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory

### ISSUE THREAD

**Issue by rahu1-1** [bbottema/simple-java-mail#209]
Does anyone know how to fix this? This is my code:
```
Email email = EmailBuilder.startingBlank()
	.from("Rahul", "xxxxx")
	.to("Rahul", "xxxxx")
	.withSubject("Sending emails through java")
	.withPlainText("This is an email send from java")
	.buildEmail();

MailerBuilder
	.withSMTPServer("smtp.host.com", 25, "username", "password")
	.buildMailer()
	.sendMail(email);
```

**Comment by rahu1-1** [comment]
This is my code 

Email email = EmailBuilder.startingBlank()
			    .from("Rahul Verma", "rverm1@ocdsb.ca")
			    .to("Rahul", "rahulvermazxmn@gmail.com")
			    .withSubject("Sending emails through java")
			    .withPlainText("This is an email send from java")
			    .buildEmail();

			MailerBuilder
			  .withSMTPServer("smtp.host.com", 25, "username", "password")
			  .buildMailer()
			  .sendMail(email);

**Comment by bbottema** [comment]
Simple Java Mail has one single mandatory dependency which is the API library for library-agnostic logging. So at the very very least, you need to have slf4j-api on the classpath. Then to actually get output, you would also want to add an implementation library, suchs as [Log4j](https://logging.apache.org/log4j/2.x/), [Logback](https://logback.qos.ch/), [SLF4J's own Simple](https://www.slf4j.org/manual.html) impl, or [JUL](https://www.logicbig.com/tutorials/misc/java-logging/slf4j-with-jul.html).

```
<dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>1.7.21</version>
</dependency>
```
You can find [config examples](http://www.simplejavamail.org/#/debugging) on the Simple Java Mail website.
