### ISSUE TITLE
Update from javax.mail:1.6.0 to jakarta.mail:1.6.3

### ISSUE THREAD

**Issue by unly** [bbottema/simple-java-mail#213]
Hi,

we want to use `simple-java-mail` internally within our company as well as in an Eclipse Foundation open source project. It works great for our purpose but unfortunately we need to be compliant with various policies. One of the dependencies of this project is `com.sun.mail:javax.mail` which is no longer supported from it's original repository and has moved to the Eclipse Foundation (https://github.com/eclipse-ee4j/javamail). Would it be an option to switch to `com.sun.mail:jakarta.mail:1.6.3`? A dependency from an unsupported project violates our policies. Having the Eclipse projects as a dependency would help us a lot.

cc @eriksven @selobosi

**Comment by bbottema** [comment]
Simple Java Mail is already on the Eclipse Jakarta Mail version for the upcoming 6.0.0 release, solving both #184 and #186. However, 6.0.0 is not ready yet (but it's getting really close _finally_).

I'm fine moving to Eclipse Jakarta Mail for the 5.x.y release as well if that solves your problem; I don't see any downsides to that (would result in release 5.2.0).

**Comment by unly** [comment]
You somehow lost me with the versioning :smiley:. The two tickets #184 and #186 refer to your commit https://github.com/bbottema/simple-java-mail/commit/01255b7abe46ec740a6b90f0f4703649ea494b0f and this updated the `com.sun.mail:javax.mail` to `1.6.2`. But you also mentioned that you could see a move to `com.sun.mail:jakarta.mail:1.6.3` in a later release like `5.2.x`. So this got me confused with the `6.0.0` you were talking about.

Besides my confusion with the versioning I don't see a problem either (that's why I proposed it in the first place :smiley:) and it would be great to have it in a future release.

**Comment by bbottema** [comment]
Yes so 5.2.0 (currently unplanned) would be a new minor version I will prepare now for you. 6.0.0 is the next planned major version which already includes the switch to Jakarta mail to solve those two issues I referenced.

Sorry for the confusion :)

**Comment by bbottema** [comment]
I removed all the version nonsense as I had myself confused as well it seems. I will release 5.2.0 soon with Jakarta Mail.

**Comment by bbottema** [comment]
I just realized some of the dependencies also will need to be upgraded.

**Comment by unly** [comment]
Great 👍 sounds good. Waiting for a release with the new dependencies.

**Comment by bbottema** [comment]
I've released 5.2.0 which concludes the switch to Jakarta Mail.

**Comment by eriksven** [comment]
Perfect, thank you!
