### ISSUE TITLE
Bug: Current DKIM header canonicalization can lead to invalid DKIM

### ISSUE THREAD

**Issue by tadcos** [bbottema/simple-java-mail#215]
In DKIMSigner class header Canonicalization is hard coded to SIMPLE (RELAXED should be better, or we could let the user choose). This may lead to Invalid Dkim, see https://wordtothewise.com/2016/12/dkim-canonicalization-or-why-microsoft-breaks-your-mail/

dkimSigner.setHeaderCanonicalization(Canonicalization.SIMPLE);

**Comment by bbottema** [comment]
Hmm, interesting. I wonder if I should make relaxed the default, assuming most users won't know about this gotcha. Does that make sense? I'm not really into DKIM that much to be able to judge that properly though :/

**Comment by tadcos** [comment]
Yes, I would suggest to use relaxed as the default, that would avoid
invalid dkim in some situations. I also notice that all the advertising
mails that I receive use this value.

Le jeu. 25 juil. 2019 à 20:50, Benny Bottema <notifications@github.com> a
écrit :

**Comment by bbottema** [comment]
Ok, if you feel up to it, I would accept a PR on master. Else I will pick it up in some time.

**Comment by bbottema** [comment]
@toKrause do you have any strong feelings on this (or safety-warning)?

**Comment by bbottema** [comment]
Released in 5.3.0. I'll revert it if @toKrause comes up with something.
