### ISSUE TITLE
TransportListener via Session

### ISSUE THREAD

**Issue by koen-serry** [bbottema/simple-java-mail#216]
I was wondering if there's any workaround for adding a TransportListener to the Transport via the session? Since I'd like to have both positive and negative feedback from the underlying smtp server.

**Comment by bbottema** [comment]
Uhh, I was not aware of this TransportListener. Can you link some additional documentation for me?

More to the point, what feedback are you missing? The library let's you know when it failed or succeeded right (exception or no exception).

**Comment by bbottema** [comment]
Any update @koen-serry?

**Comment by koen-serry** [comment]
Here you go https://javaee.github.io/javamail/docs/api/javax/mail/event/TransportListener.html

**Comment by bbottema** [comment]
Yeah I found that by now ;)

My other question remains unanswered which really is about why you would need access to the underlying JavaMail API; doesn't Simple Java Mail provide enough feedback?

**Comment by koen-serry** [comment]
Well the event allows you to get access to all the details of the session that is shielded by the api as it is now. Certainly if things don't work as they should it is helpful to be able to have access to all the underlying objects

**Comment by bbottema** [comment]
Would you like to configure this at email level or at mailer level?

**Comment by koen-serry** [comment]
I think it would make sense on a mailer level since you're generally either concerned about your smtp server or not at all.

**Comment by bbottema** [comment]
Ok, so I'm close to picking this up. There is one issue though, in 6.0.0, support for server clustering was added. So you can have several mailer instances all adding to a cluster, resulting in the effect that any mailer used to send an email delegates to the cluster instead (meaning, `mailer1.sendEmail(email)` doesn't guarantee _server1_ is used to send the email).

How then to manage server feedback using transport listeners?

**Comment by bbottema** [comment]
Closing as it is not clear to me what problem it solves that cannot be solved with the current facilities.
