### ISSUE TITLE
Bug: MimeMessageParser rejects attachments with duplicate names

### ISSUE THREAD

**Issue by nicolasbelisle** [bbottema/simple-java-mail#219]
MimeMessageParser uses a Map for the attachments:

> 484 : public Map<String, DataSource> getAttachmentList()

However an email can have 2 attachments with the same name. The Map will just replace any existing attachment.

**Comment by bbottema** [comment]
Is this a real use case?

**Comment by nicolasbelisle** [comment]
Yes. Real email that went through MimeMessageParser (v. 5.1.7).

**Comment by nicolasbelisle** [comment]
Essentially replacing the Map with a List<Map.Entry) does the job 
It's already called "attachmentList" ;-)
parsedComponents.attachmentList.put(cid, cidEntry.getValue());
to 
parsedComponents.attachmentList.add(new AbstractMap.SimpleEntry(cid, cidEntry.getValue()));

BTW, you can add attachments with the same name in Gmail.
Reference https://github.com/nicolasbelisle/simple-java-mail/commit/47a47f3c32c6caa5d55fe9da19cf8732860bb101 (There's a few other fixes in this commit however).

**Comment by bbottema** [comment]
Ok, you made a good case. If feel up to it, I'll accept a PR on master! Or else I'll pick it up in due time.

**Comment by bbottema** [comment]
Fixed and released in 5.2.1!

**Comment by DasTier1** [comment]
Seems to be still there in Simple Java Mail 6.5.0:
package org.simplejavamail.converter.internal.mimemessage;
MimeMessageParser :
Line 508 :  public Map<String, DataSource> getAttachmentList() {
            return this.attachmentList;
        }
