### ISSUE TITLE
Simple Java Mail from MimeMessage

### ISSUE THREAD

**Issue by neil-ceschi** [bbottema/simple-java-mail#22]
I would need to handle files saved in .eml format, easily convertible into MimeMessage. It would be great to build SimpleMail from MimeMessage!
Thanks a lot!

**Comment by bbottema** [comment]
If you provide an implementation that fills an `Email` instance completely using a `MimeMessage`, I will integrate it into Simple Email.

**Comment by bbottema** [comment]
The truth is, MimeMessage is a ambiguous  type tree structure. The `Email` class works exactly why `MimeMessage` doesn't: it has a simple interface and it allows you do define an email in exactly one way. MimeMessage on the other hand is a messy heap of nonsense and extracting data from that is a lot harder than putting data into it.

**Comment by bbottema** [comment]
On the other hand, [Apache seems to have an implementation](https://commons.apache.org/proper/commons-email/apidocs/src-html/org/apache/commons/mail/util/MimeMessageParser.html) already. I might just use that.

**Comment by bbottema** [comment]
I implemented a MimeMessage parser based on Apache's version. I had to modify a few a few things: headers were not parsed in Apache's version and attachments and embedded images were not properly distinguished (they ignored `Part.INLINE` and `Part.ATTACHMENT` predispositions).

I'll release a new version somewhere this week when I have the time. Releasing always takes me  more time than implementing an actual fix :/

Usage:
```java
Email email = new Email(yourMimeMessage);
// the other way around is now possible too!
MimeMessage mimeMessage = Mailer.produceMimeMessage(yourEmail, yourSession /* or null */);
```
The following should be true then:
```java
Email emailSource = new Email();
/* populate email... */
Email emailTarget = new Email(mailer.produceMimeMessage(emailSource, null));

emailSource.equals(emailTarget);
```

**Comment by bbottema** [comment]
Release in v3.0.0!
