### ISSUE TITLE
How to know if the mail has been send successfully or not?

### ISSUE THREAD

**Issue by TacticalTwerking** [bbottema/simple-java-mail#228]
**Nice lib for java programing** 
But i was wondering it is possible to add a CallBack or Listener for the **Mail Sending Process** to know the final result and catch exceptions ?

After reading the whole page on http://www.simplejavamail.org , i wasn't able to find any information relate to it , thanks

**Comment by bbottema** [comment]
Hi, that's right, it's not in the currently released version. But, it is in the next version that is getting real close to being released! Once 6.0.0 is released, the documentation will be updated accordingly.

Meanwhile, please refer to #148 for details.

**Comment by bbottema** [comment]
Released in 6.0.0-rc1! Check the renewed docs for details...

**Comment by bbottema** [comment]
6.0.0 has released as well, finally.
