### ISSUE TITLE
Timeouts not working for synchronous sendMail calls. 

### ISSUE THREAD

**Issue by leonharj** [bbottema/simple-java-mail#229]
Is there a reason why for synchronous calls no timeouts are configured?
The workaround is to set the timeouts via properties. 

`MailSender.send(final Email email, final boolean async)`
...
`if (async)`
...
`configureSessionWithTimeout(...)`

I'm using SimpleJavaMail:5.4.0

**Comment by bbottema** [comment]
If I remember correctly, this was a bug I encountered while implementing advanced batch support for 6.0.0. I'll dive into the 5.x.y code for you somewhere this week to confirm.

**Comment by bbottema** [comment]
I've confirmed the bug and can inform you it's fixed in the upcoming 6.0.0. I'll have a minor update out soon for version 5.

**Comment by bbottema** [comment]
v5.5.0 released with fix.
