### ISSUE TITLE
Wrap up the release, start using the new parent POM, CircleCI pipeline, javadoc.io integration and writeup migration notes

### ISSUE THREAD

**Issue by bbottema** [bbottema/simple-java-mail#233]
- [x] start using the new parent POM
- [x] fix config issues with Javadoc/Jacoco
- [x] configure enforcer plugin and solve (transitive) dependency version clashes
- [x] Solve spotbugs errors from using the new parent POM
- [x] CircleCI pipeline
- [x] writeup migration notes
- [x] fix build warnings and javadoc problems
- [x] see if package javadoc is needed
- [x] see what can be done about the test coverage
- [x] update release notes
- [x] javadoc.io integration, badges

**Comment by derrohrbach** [comment]
I have one question: How can I get access to a prerelease? Do i have to build it myself or do you distribute jars/have a repository. If i have to build it myself, where can i get help or find instructions?

**Comment by bbottema** [comment]
Hi @derrohrbach, just check out the develop branch and run mvn install if you wish to build it yourself.

I also already released a candidate release snapshot, 6.0.0-rc1-SNAPSHOT. To get this as a Maven dependency you need to add the [OSS Sonatype snapshots repo]([add the snapshot repo](https://stackoverflow.com/a/7717234/441662)) in your POM or settings.conf.

**Comment by bbottema** [comment]
Preparing for release 6.0.0-rc1 on branch [preparing-6.0.0-rc1](https://github.com/bbottema/simple-java-mail/tree/preparing-6.0.0-rc1)...

**Comment by bbottema** [comment]
6.0.0-rc1 released!!

**Comment by bbottema** [comment]
6.0.0 has released as well, finally.
