### ISSUE TITLE
Be able to fix the sent date for a new email

### ISSUE THREAD

**Issue by Glassalau** [bbottema/simple-java-mail#235]
I was wondering if it was possible to set the sent date with the date is given inside the headers. Actually "produceMimeMessage()" in org.simplejavamail.converter.internal.mimemessage.MimeMessageHelper always set the sent date with a new date.

I would like to choose my mail's sent date when sending it with the sendMail() method in org.simplejavamail.mailer.Mailer.

[MimeMessageHelper.java:94](https://github.com/bbottema/simple-java-mail/blob/develop/modules/simple-java-mail/src/main/java/org/simplejavamail/converter/internal/mimemessage/MimeMessageHelper.java)
`setHeaders(email, message);`
`message.setSentDate(new Date());`

Best regards,

Glassalau

**Comment by bbottema** [comment]
Hello @Glassalau, that's a nice enhancement. I'll include it in the upcoming 6.0.0 release!

**Comment by bbottema** [comment]
Released in 6.0.0-rc1.

**Comment by bbottema** [comment]
6.0.0 has released as well, finally.
