### ISSUE TITLE
Update SLF4J and JavaMail dependencies

### ISSUE THREAD

**Issue by zimmi** [bbottema/simple-java-mail#24]
The groupId for JavaMail changed, see [this stackoverflow answer from the lead developer of JavaMail](http://stackoverflow.com/a/22021656).
So the new maven coordinates right now are:

```xml
<dependency>
    <groupId>com.sun.mail</groupId>
    <artifactId>javax.mail</artifactId>
    <version>1.5.5</version>
</dependency>
```

The SLF4J dependency also got a bit stale, the most recent version right now is:

```xml
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-api</artifactId>
    <version>1.7.13</version>
</dependency>
```

Thanks a lot for this library, it really makes my life easier. :)

**Comment by bbottema** [comment]
Will be fixed in v2.5,

**Comment by zimmi** [comment]
Awesome, thanks! :)

**Comment by bbottema** [comment]
Release should be available in maven central now. Thanks for the help!

**Comment by zimmi** [comment]
@bbottema Is maven central just a bit slow today or was there an error? I'm not [finding it](http://search.maven.org/#search|ga|1|g%3A%22org.codemonkey.simplejavamail%22%20AND%20a%3A%22simple-java-mail%22).

**Comment by bbottema** [comment]
It's [there now](http://search.maven.org/#artifactdetails%7Corg.codemonkey.simplejavamail%7Csimple-java-mail%7C2.5%7Cjar).
