### ISSUE TITLE
Unnecessary log4j2.xml in artifact jar file

### ISSUE THREAD

**Issue by TimC71** [bbottema/simple-java-mail#242]
Including simple-java-mail-x.x.x.jar into library may cause log module ignore project level log4j configuration file, because there is a log4j2.xml in simple-java-mail-x.x.x.jar which may conflict with project level log4j configuration file.
<img width="264" alt="Untitled" src="https://user-images.githubusercontent.com/35205865/72034873-3bbcbd00-32d1-11ea-8cb1-8912a5bb5365.png">

**Comment by bbottema** [comment]
yikes, that's not supposed to be there.

**Comment by bbottema** [comment]
Fix released in 6.0.0-rc4. Thanks for the report.

**Comment by bbottema** [comment]
6.0.0 has released as well, finally.
