### ISSUE TITLE
Illegal reflective access - Warning

### ISSUE THREAD

**Issue by hyperxpro** [bbottema/simple-java-mail#244]
Getting error while running SimpleJavaMail. Is this normal?

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.mail.util.SocketFetcher (file:/C:/Users/Hyper/.m2/repository/com/sun/mail/jakarta.mail/1.6.3/jakarta.mail-1.6.3.jar) to method sun.security.util.HostnameChecker.getInstance(byte)
WARNING: Please consider reporting this to the maintainers of com.sun.mail.util.SocketFetcher
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by bbottema** [comment]
Hmm, it's not related to Simple Java Mail itself it seems, but to the underlying Jakarta Mail framework.

[Here's](https://github.com/eclipse-ee4j/mail/issues/391) another bug report like this one.

[Here's](http://vsryjty.blogspot.com/2019/02/javaxmailmessagingexception-connection.html) another very old similar bug report from 2012 (!), which suggests it may happen when you are having some proxy issue.

If you try to connect with Jakarta Mail directly (without Simple Java Mail), do you get the same error?

**Comment by hyperxpro** [comment]
> Hmm, it's not related to Simple Java Mail itself it seems, but to the underlying Jakarta Mail framework.
> 
> [Here's](https://github.com/eclipse-ee4j/mail/issues/391) another bug report like this one.
> 
> And [here's](http://vsryjty.blogspot.com/2019/02/javaxmailmessagingexception-connection.html) another very old similar bug report from 2012 (!), which suggests it may happen when you are having some proxy issue.
> 
> If you try to connect with Jakarta Mail directly (without Simple Java Mail), do you get the same error?

I am new user so not sure what this library uses underneath. How you tell how to connect without Jakarta Mail Framework?

**Comment by bbottema** [comment]
Well, that's the traditional way of mailing in Java. Jakart Mail (previous Sun JavaMail), is Java's native mail RTF implementation used by everyone and all frameworks such as Spring, Apache Commons Email.

There's literally a ton of documentation of it, but it's pretty low level (hence why I made Simple Java Mail).

**Comment by bbottema** [comment]
But honestly, I have no idea what this error is about, I have not encountered it before. Seems like it is network related somehow.

Perhaps you're better off asking this question at the [Jakarta Mail forum/issue tracker](https://eclipse-ee4j.github.io/mail/). It's hosted on the Eclipse Foundation platform, which hosts a bunch of projects. You can find the forums there or report a bug.
