### ISSUE TITLE
MimeMessageParser doesn't handle multiple attachments with the same name correctly

### ISSUE THREAD

**Issue by GnTeezer** [bbottema/simple-java-mail#249]
`ParsedMimeMessageComponents` uses a `TreeSet` with a `NaturalEntryKeyComparator` to store the attachment list. 

This means that if we parse an email has multiple attachments with the same name we only get one as each attachment with the same name replaces the previous one.

https://github.com/bbottema/simple-java-mail/blob/c6abd4f633418b5bfeffbdc04887dd31f0460865/modules/simple-java-mail/src/main/java/org/simplejavamail/converter/internal/mimemessage/MimeMessageParser.java#L543

**Comment by bbottema** [comment]
Fix released in 6.0.4.
