### ISSUE TITLE
JavaDocs are useless because they are incomplete

### ISSUE THREAD

**Issue by zilti** [bbottema/simple-java-mail#254]
Example: `org.simplejavamail.api.email.EmailPopulatingBuilder`, containing all the methods to actually create a mail, is missing from the JavaDocs.

**Comment by bbottema** [comment]
Thanks for bringing this to my attention. The Javadoc is there in the code, but since 6.0.0 the Javadoc plugin for Maven was configured differently (and wrong).

I'll release with the Javadoc included ASAP!

**Comment by bbottema** [comment]
Actually, the Javadoc is there in the aggregate Javadoc: https://www.javadoc.io/doc/org.simplejavamail/maven-master-project/latest/org/simplejavamail/api/email/EmailPopulatingBuilder.html

So at least there's that, but I'll fix it for the separate module jars as well.

**Comment by zilti** [comment]
Oh, it is in `maven-master-project`, alright, good to know! Yes, I resorted to looking into the source code and was happy to find that the documentation is actually there.

**Comment by bbottema** [comment]
I'm a little confused now. If I look in Maven central (and my own target folders), Javadoc is there. What exactly is the problem?

**Comment by bbottema** [comment]
I don't see the original problem anymore (I think I was looking in the wrong place initially?). Need confirmation on the problem before I can do anything. Closing for now.
