### ISSUE TITLE
Please indicate clearly that this is only for sending

### ISSUE THREAD

**Issue by oliviercailloux** [bbottema/simple-java-mail#258]
I just lost quite a bit of time reading all the wonderful things that SJM can do for me on its [web site](http://www.simplejavamail.org/). Only to realize, after having been convinced that it does have a well-designed API, and seems robust enough, that it does not read e-mail.

Too late to [change the name](#172), but please at least indicate this important scope restriction clearly, right from the start. For example: “Simple Java Mail is a library for sending e-mails with a super clean API. It's the easiest to use (Java) mailing library in the world. (Simple Java Mail does not (yet) take care of the reading part.)”

(Hoping that read support will be added soon!)

**Comment by bbottema** [comment]
You have a fair point. The GitHub project clearly states in the project tag "Simple API, Complex Emails (JavaMail smtp wrapper)", but this is not mentioned like this on the simplejavamail website.

I'll make sure to add it soon.

> that it does not read e-mail

Just a nitpick, but Simple Java Mail does read email (EML files, .msg), but it doesn't connect and fetch emails from a server.

**Comment by bbottema** [comment]
Done.
