### ISSUE TITLE
Mailer.getSession() - Why am i needing this

### ISSUE THREAD

**Issue by LBoraz** [bbottema/simple-java-mail#261]
Hi, i need to call mailer.getSession() because i need to call EmailBuilder.copying(mimeMessage)
and to build a MimeMessage i need a Session.

Why i don't have a session?
Because i receive the raw MimeMessage (as an InputStream) from an external system so i want to use the session provided by the Mailer.

If there's another way to create an Email from an existing InputStream (representing a MimeMessage) let me know. 

Silencing logs from MailerImpl is an option.

**Comment by bbottema** [comment]
Can you share the (pseudo) code for doing this conversion? I suspect you can do this with just an empty Session object: `Session.getDefaultInstance(new Properties())`

**Comment by LBoraz** [comment]
Hi, this is more or less what i do:

```
// loaded on a per-message basis, 
// every message may have a different set of credentials, transport strategy, endpoint, and so on
var smtpConfiguration = null; 
// this comes from an external system - let's say something wrote it previously to an S3 bucket
var documentStream = null;  
// creates the Mailer for the given configuration
Mailer mailer = mailerFactory.createMailer(smtpConfiguration);
// creates a MimeMessage from the document stream - using the session from the Mailer
MimeMessage mimeMessage = new MimeMessage(mailer.getSession(), documentStream);
// creates an Email from the MimeMessage
Email email = EmailBuilder.copying(mimeMessage).buildEmail();
// send email - AssertionError could happen now
mailer.sendMail(email);
```

I guess that if the full session is not really needed then i think your suggestion of just passing an empty session is valid for me.

**Comment by bbottema** [comment]
Indeed, have you tried it yet? I'm assuming for now that it would work so I'm closing this report. Again thanks for taking the time to raise your use case!
