### ISSUE TITLE
Problem with async

### ISSUE THREAD

**Issue by ransarot** [bbottema/simple-java-mail#263]
Hi, I have a problem, when I try to use the async treatment I have a problem with this message:
 org.simplejavamail.internal.modules.ModuleLoaderException: Batch module not found, make sure it is on the classpath (https://github.com/bbottema/simple-java-mail/tree/develop/modules/batch-module)

But i have core-module and batch-module.jar in my build. (I have 6.0.3 version but I've updated to 6.0.4 today)

My source:

this.mailer = MailerBuilder
		          .withSMTPServer(envProperties.getEnvValueOf("mail.smtp.host"), Integer.parseInt(envProperties.getEnvValueOf("mail.smtp.port")), envProperties.getEnvValueOf("mail.smtp.account"), envProperties.getEnvValueOf("mail.smtp.pass"))
		          .withTransportStrategy(TransportStrategy.SMTPS)
		          .async()
		          .buildMailer();

Email email = EmailBuilder.startingBlank()
			          .to(to, to)
			          .from("[Name]", from)
			          .withReplyTo("[name]", from)
			          .withSubject(subject)
			          .withHTMLText(body)
			          .signWithDomainKey(privateKeyDKIMBytes, "[domain]", "[selector]") // DKIM
			          .buildEmail();
			this.mailer.sendMail(email);

Thanks!

**Comment by bbottema** [comment]
Simple Java Mail simply checks if a class can be found from the Batch module jar. If it can't find it, it really isn't on the class path. Please double check your run configuration, because there is not much I can do about it on my end.

**Comment by ClundXIII** [comment]
@ransarot make sure to include the batch module from maven as well:

```
<dependency>
    <groupId>org.simplejavamail</groupId>
    <artifactId>batch-module</artifactId>
    <version>6.0.4</version>
</dependency>
```

batch-module is apparently not a default dependency of simple-java-mail. (I just had the same Problem). @bbottema Maybe this should be documented in the readme?

**Comment by bbottema** [comment]
Well, this is documented alongside every feature on the website as well as on every java method Javadoc. But I guess an extra note on the README can't hurt.
