### ISSUE TITLE
Switch from AssertionError to IllegalStateException

### ISSUE THREAD

**Issue by LBoraz** [bbottema/simple-java-mail#264]
Is it possible to remove the AssertionErrors thrown by the Mailer, for example in case of empty MimeMessage body? I think it should be converted to an Exception. I understand what you are trying to do there, but as java applications normally don't catch Errors this leads applications to crash/fail for what it should really be a ValidationException (most likely recoverable, at least in my use-case).

**Comment by bbottema** [comment]
Sounds reasonable. I'll change it, thanks for the suggestion.

**Comment by bbottema** [comment]
I'm having second thoughts about this.

Assertion errors indicate the system has reached an unsupported and more importantly an _unknown_ state and continuing could mean anything else the application does could be garbage.

Essentially I cannot assume it is recoverable, in fact as a library designer I have to assume the opposite. It is an error precisely so that the system halts.

**Comment by LBoraz** [comment]
yes, i know the intention is to signal an impossibility to continue and from your point of view you can't know if the application will be able to recover, but maybe that's exactly why the choice should be left to the application. 

I think (but of course my perspective on this is limited to my use-case) that most people will end up catching the AssertionError like i did, in order to recover.

Just to add context, imagine this sequence (from my use-case)
worker node receives a mime-message from an external system -> it tries to "forward" it somewhere else using the library -> the library throws an AssertionError -> the worker node dies (because the Error kills the process) -> health checks trigger the start up of a new worker node to replace the dead one -> the worker tries to consume again the same "broken" message -> worker node never recovers (because normally java.lang.Errors are not handled)

https://docs.oracle.com/javase/7/docs/api/java/lang/Error.html

Let me know what you think

**Comment by bbottema** [comment]
Released in 6.1.0
