### ISSUE TITLE
When sending async mail in custom flume sink, the batch module shows not found.

### ISSUE THREAD

**Issue by yosaku01** [bbottema/simple-java-mail#269]
When I create a custom sink in flume 1.9.0 and send an async alert mail with simple java mail 6.0.4,
The log shows  the error message:

org.simplejavamail.internal.modules.ModuleLoaderException: Batch module not found, make sure it is on the classpath (https://github.com/bbottema/simple-java-mail/tree/develop/modules/batch-module)

And I have put the batch-module 6.0.4 library in the flume lib directory. The problem still happened.
But when I send alert mail in a java application, the error did not happen.

**Comment by bbottema** [comment]
This can only be a classpath issue (on your end). I don't know how the classpath is managed using flume, but it seems the batch-module jar is not added to it. There's nothing I can do on my end to fix it.
