### ISSUE TITLE
JavaDoc shows raw HTML for Recipient class

### ISSUE THREAD

**Issue by codyburleson** [bbottema/simple-java-mail#27]
From the GitHub README link to the JavaDoc, then click on Recipient class, the raw HTML shows up in the frame (all the other classes render properly).

![recipientclass](https://cloud.githubusercontent.com/assets/7317733/13192010/ba276cfc-d72d-11e5-8a9d-31d27a7aae8f.jpg)

**Comment by bbottema** [comment]
The entire javadoc doesn't work properly in GitHub. I don't how to host that properly here. The only way it can work is by hosting it somewhere else...

**Comment by codyburleson** [comment]
OK, I get it. No problem. I love what you've started here.

**Comment by bbottema** [comment]
Actually, I expected to find it on [javadoc.io](http://www.javadoc.io/), but it's not picking up the release in maven central for some reason. I'll mail the maintainer there.

**Comment by bbottema** [comment]
Yay: http://www.javadoc.io/doc/org.codemonkey.simplejavamail/simple-java-mail/2.5.1

I will update the Readme shortly

**Comment by codyburleson** [comment]
Awesome! Thank you.

And thanks again for building this package. I set up on SSH through Gmail in a jiffy.

I had to go into my Gmail account and turn on the setting "Allow for less secure apps” (something like that), and then it worked.

- Cody

**Comment by bbottema** [comment]
> I had to go into my Gmail account and turn on the setting "Allow for less secure apps” (something like that), and then it worked.

Yeah, I have two-factor login turned on for gmail and have to create a special [per-app password](https://security.google.com/settings/security/apppasswords) to make mailing work.

**Comment by bbottema** [comment]
Updated the javadoc references on the manual page!
