### ISSUE TITLE
signWithSmime issue

### ISSUE THREAD

**Issue by lmpampaletakis** [bbottema/simple-java-mail#272]
Hi I am trying to send a signed email. I follow the documentation but the mail is not signed.

```
 Pkcs12Config myKeyInfo = Pkcs12Config.builder()
                .pkcs12Store(Mail.class.getClassLoader().getResourceAsStream("mystore.jks"))
                .storePassword("***".toCharArray())
                .keyAlias("alias")
                .keyPassword("***".toCharArray())
                .build();
```

``` 
Email emailToBeSigned = currentEmailBuilder.
    .(..)
    .signWithSmime(myKeyInfo)
    .buildEmail();

mailer.sendMail(emailToBeSigned);

```
Also there is no error printed

**Comment by bbottema** [comment]
How do you know it is not signed? This basic scenario has been well tested using junit tests and without any error, I'm a little skeptical.

**Comment by bbottema** [comment]
With no further user input it is impossible for me to analyze. Considering the test suite focused on the S/MIME functionality, until I get more details form this user, I'm assuming human error. I'll be happy to reopen once I have something to go on...
