### ISSUE TITLE
Encrypted email to multiple recipients

### ISSUE THREAD

**Issue by lamgibrcom** [bbottema/simple-java-mail#274]
Hi all,
I'm struggling to understand if this kind of sending it's supported already and in case how to use the API  properly.
The scenario is quite simple : sending a single encrypted email with many recipient using for each of them the public cert to encrypt the message (s/mime).

Thanks

**Comment by bbottema** [comment]
The number of recipients doesn't matter: each recipient gets the same email which is encrypted or just signed with an s/mime key. To decrypt or verify the received email, each client needs to have the same respective s/mime key.

Perhaps one the [smime junit tests](https://github.com/bbottema/simple-java-mail/blob/develop/modules/simple-java-mail/src/test/java/org/simplejavamail/internal/smimesupport/TestSmimeSelfSigned.java#L133) (reading an encrypted email) gives you a better idea of what is going on.

**Comment by lamgibrcom** [comment]
"If you use a different key for each sender, then indeed you would use a for each to loop through them to build the emails, similarly to how the emails are built here (or with your own X509Certificate object)."

Yes that's the actual implementation , i was looking how to avoid this loop because i think is not efficient in this way (imagine if you have a very long list...)  then I get this point because I rad that is possible to encrypt many digest with different certificates into the same email and send just one then the client is able to match the one for the private key owned, unfortunately i didn't find any implementation of that way...

**Comment by bbottema** [comment]
Oohh that is very interesting. Doesn't that simply mean the content of the email is duplicated for each recipient? Could potentially swamp the network...

**Comment by lamgibrcom** [comment]
Well.... of course it's a duplication in terms of payload... but it depends really on what's inside the S/MIME  maybe at then end it could be lighter than most of the attachments we use to send via email.....
Anyway it's always an evaluation of cost/ben in same case like mine where the system it's used just to send email notification (2 rows of plan text like 2Kb) i think is more convenient to move the overhead from the runtime execution (loop through the mail list) to the mx server (to manage less than 1 MB ...) 
But i'm still evaluating because probably this vantage is not 100% true considering that need a loop in any case to encrypt the content with each certificate..... at moment it's just to explore if this option it's supported ootb by JavaSimpleMail lib.

**Comment by bbottema** [comment]
Indeed, a loop will will alway be necessary. The only benefit I can think of with this library would be that it loops for you by giving it a s/mime key along with each recipient.

**Comment by bbottema** [comment]
But right now this doesn't seem much of a use case (yet). Closing for now. Perhaps it will come up again
