### ISSUE TITLE
MimeMessageParser doesn't compile

### ISSUE THREAD

**Issue by iBernd81** [bbottema/simple-java-mail#278]
Yesterday I checked out this amazing project. But it seems there is a problem with IntelliJ and the class `org.simplejavamail.converter.internal.mimemessage.MimeMessageParser.java`.

Lines 140 and 142 won't compile without casting the method `parseContent(currentPart)` to `String`.

What doing I wrong?

**Comment by bbottema** [comment]
I see. The project is meant to be compiled for java 7, I saw this issue popping up starting from Java 8.

**Comment by bbottema** [comment]
I added the missing casts for Java 8, with warning suppressions for the casts in Java 7.
