### ISSUE TITLE
Email parsing fails if there are any special characters in the incoming From header from maligun.

### ISSUE THREAD

**Issue by ajmalrehman** [bbottema/simple-java-mail#282]
Dear team, 
For my case the email FROM header has email address is something like this **"tëst Mail <noreply@testmail.com>"**. while parsing using function 
EmailAddressParser.getAddressParts(address, EmailAddressCriteria.DEFAULT,true); it returns null. I understand that the email should be RFC28222 format. Is it possible for you guys to send me a customized code that allow special character in the email address?.

**Comment by bbottema** [comment]
Hello @ajmalrehman, regarding special characters in email addresses, please see https://github.com/bbottema/email-rfc2822-validator/issues/9. The email address you mention is not valid and not directly supported.

If you're running into issues with Simple Java Mail not able to send emails, you can turn off validation:

```java
currentMailerBuilder
    .clearEmailAddressCriteria() // turn off validation
```
If however you are fine with normalizing your email address (eg. remove diacritics replacing special characters with their base character), you can use Java's Normalizer:

```java
String yourEmail = "tëst Mail <noreply@testmail.com>";

yourEmail= Normalizer.normalize(yourEmail, Normalizer.Form.NFD);
yourEmail= yourEmail.replaceAll("[^\\p{ASCII}]", "");

// yourEmail is now "test Mail <noreply@testmail.com>"
```

**Comment by ajmalrehman** [comment]
@bbottema  Normalizing email does solve the problem if email has diacritics but if there is special characters like single quote e.g M-W’s Word of the Day <mwwotd@wotd.m-w.com>, Normalizer removes the special character i.e single quote e.g.M-Ws Word of the Day <mwwotd@wotd.m-w.com>. In this case EmailAddressParser.getAddressParts(address, EmailAddressCriteria.DEFAULT,true) does work properly. But I want to have "M-W’s Word of the Day" in original form after parsing . any suggestion how to achieve this?

**Comment by bbottema** [comment]
With the following the email address remains untouched:

```java
String yourEmail = "mwwotd@wotd.m-w.com";

yourEmail= Normalizer.normalize(yourEmail, Normalizer.Form.NFD);
assertThat(yourEmail).isEqualTo("mwwotd@wotd.m-w.com");
yourEmail= yourEmail.replaceAll("[^\\p{ASCII}]", "");
assertThat(yourEmail).isEqualTo("mwwotd@wotd.m-w.com");

// test passes
```

**Comment by ajmalrehman** [comment]
Can I extract the Display name from email Address?  e.g  from: 
String email =" tëst Mail <noreply@testmail.com>"
adress[0] = tëst Mail
adress[1]= <noreply@testmail.com>

**Comment by bbottema** [comment]
```java
@Test
public void testIllegalCharacters() {
	// normalize address:
	String yourEmail = "w's ëäó <mwwotd@wotd.m-w.com>";
	
	yourEmail= yourEmail.replaceAll("[^\\p{ASCII}]", "");
	assertThat(yourEmail).isEqualTo("w's eao <mwwotd@wotd.m-w.com>"); // check result
	
	// ok, now we have a normalized address, extract parts:
	assertThat(EmailAddressParser.getAddressParts(yourEmail, RECOMMENDED, true))
			.containsExactly(
					"w's eao", 
					"mwwotd", 
					"wotd.m-w.com"
			);
}
```
