### ISSUE TITLE
rambler.ru smtp is not working

### ISSUE THREAD

**Issue by kaoruuuu** [bbottema/simple-java-mail#301]
Hello, 

since yesterday i'm trying to get simple java mail for rambler.ru server.
Can anyone try it to connect to a rambler.ru mail or have a solution?

PS: with another mail provider it works

with best regards

**Comment by bbottema** [comment]
I'm closing this as this is a mail server related question and not a mail client related question. Also I don't speak russian. [stackoverflow.com](https://stackoverflow.com/) is probably a better place to ask this.
