### ISSUE TITLE
Problem with S/MIME decryption.

### ISSUE THREAD

**Issue by Coster** [bbottema/simple-java-mail#302]
Analogous to problem #252, I also wanted to decrypt an EML file using the appropriate certificate and extract the attachments. According to cgruber0's request, I have an almost identical setup and fail with seemingly the same error. 

I have two messages one encrypted only, the other encrypted and implicitly signed. Both I can not decrypt using this coding. 

The mails originate from Outlook and were created from there and sent to another Outlook subscriber. In Outlook both messages can be opened and read without any problems including a file attachment.

Code:
```java
InputStream key_a = new FileInputStream(new File("cert.pfx"));
InputStream key_b = new FileInputStream(new File("cert.pfx"));

SmimeKeyStore smimeKeyStore = new SmimeKeyStore(key_a, "pw".toCharArray());
String alias = smimeKeyStore.getPrivateKeyAliases().iterator().next();

Pkcs12Config myKeyInfo  = Pkcs12Config.builder()
                        .pkcs12Store(key_b)
                        .storePassword(pw)
                        .keyAlias(alias)
                        .keyPassword(pw)
                        .build();

InputStream inputStream = new FileInputStream("pipeline_mail_sample_1.eml");
Email message = EmailConverter.emlToEmail(inputStream, myKeyInfo);
```
Consolen output:

getSmimeMode:     PLAIN
getSmimeMime:     null
getSmimeType:     null
getSmimeName:     null
getSmimeMicalg:   null
getSmimeSignedBy: null
smime.p7m

Perhaps one more initial thought. How can I track if the Pkcs12Config is used correctly - partly I have intentionally stored wrong passwords and there is no error or anything. 

Or have I misunderstood the structure? Is it not possible to import and decrypt encrypted mail by file?

**Comment by bbottema** [comment]
Released in 4.7.5

**Comment by bbottema** [comment]
Are you able to provide me with your setup? Your last question seems like something I would want to log more clearly.

**Comment by bbottema** [comment]
Any update?

**Comment by bbottema** [comment]
Closing due to missing input.
