### ISSUE TITLE
Bridge to Annonymous Proxy not created

### ISSUE THREAD

**Issue by Fritsch166** [bbottema/simple-java-mail#305]
![grafik](https://user-images.githubusercontent.com/12083481/107590877-a0032c00-6c09-11eb-8855-24a2566395b9.png)

It seems to me that there won't be created a socks5 bridge to a annonymous proxy (proxy without authentification)?
Is there a bug  in the code?

               <dependency>
			<groupId>org.simplejavamail</groupId>
			<artifactId>simple-java-mail</artifactId>
			<version>6.4.4</version>
		</dependency>
		<dependency>
			<groupId>org.simplejavamail</groupId>
			<artifactId>authenticated-socks-module</artifactId>
			<version>6.4.4</version>
		</dependency>

**Comment by bbottema** [comment]
This is by design, as the underlying Jakarta Mail library is able to handle proxies without authentication by itself. Only when the proxy requires authentication, we need to compensate for Jakarta's lacking capability.
