### ISSUE TITLE
Add support for SMTP pipelining

### ISSUE THREAD

**Issue by t101jv** [bbottema/simple-java-mail#308]
https://tools.ietf.org/html/rfc2920

For our email sending, we have noticed that the latency is being dominated by the outgoing SMTP send. We are currently using the simple-java-mail library, but are considering evaluating https://github.com/HubSpot/NioSmtpClient so that we can optimize the SMTP connection by taking advantage of it's pipelining feature.

**Comment by bbottema** [comment]
Interesting, I had never heard of pipelining before...

That said, have you looked into using Simple Java Mail's batch-module? With it you get a [connection pool](https://www.simplejavamail.org/configuration.html#section-reusing-connections) with reusable Transport connections that don't close. Even having a pool of one connection that doesn't close can double your performance as up to half of the time spent on sending an email is simply opening up a Transport connection.

**Comment by bbottema** [comment]
At first glance, as Simple Java Mail builds upon Jakarta Mail (previously JavaMail), it seems impossible to configure support at this level. Simple Java Mail doesn't handle the actually server commands such as EHLO and Jakarta Mail has no support for pipelining, and looking around a bit, it doesn't seem to be on the radar either. I'll do a bit more research, but I'm afraid I'll have to wait for Jakarta to make a move here.

**Comment by t101jv** [comment]
That should be fine, we are going to try tuning our connection pool size and lifecycle and see where that gets us.

**Comment by bbottema** [comment]
Any update on your performance?

**Comment by t101jv** [comment]
We haven't had the capacity to fix it yet. I've changed teams as well. I'll let them know they can follow up here if necessary.

**Comment by bbottema** [comment]
In that case I'll close the issue until further notice. But looking forward to your performance update.

**Comment by bbottema** [comment]
If you know more by now, I'm still curious as to your findings.

**Comment by t101jv** [comment]
I haven't worked on the announcements team for almost two years and have left the company as well. I'd refer you to Zubair Khan who is the current lead on the team, but i don't see him on LinkedIn and have no way to contact him otherwise.

**Comment by bbottema** [comment]
WIll be continued in #699.
