### ISSUE TITLE
Session auth behaving differently on different machines

### ISSUE THREAD

**Issue by jollygreenegiant** [bbottema/simple-java-mail#309]
I'm seeing a difference in SimpleJavaMail's behavior on different machines I run it on, and I'm looking to get some more info on that so I can debug my issue.

I'm writing a program designed for my dad (a Windows user) to email a list of customers.  Long story short, the program I've written works properly and successfully sends emails on the Mac that I wrote the program on and the Windows machine I'm testing it on, but does not work when we try to run it on his machine.

On my machine, where the program runs successfully, I get this log output before it successfully sends the emails:
[successfulAuth.txt](https://github.com/bbottema/simple-java-mail/files/6205076/successfulAuth.txt)

On his machine, where the program fails, I get this log output, after which the program sends nothing because it cannot authenticate:
[failedAuth.txt](https://github.com/bbottema/simple-java-mail/files/6205083/failedAuth.txt)

On the successful auth, I'm getting a mix of 
`DEBUG SMTP: protocolConnect returning false, host=smtp.bananatag.com, user=Cameron, password=<null>`, which I assume comes from the username of the computer it's running on,
and 
`DEBUG SMTP: protocolConnect login, host=smtp.bananatag.com, user=*my dad's email address*, password=<non-null>`

where it is successfully able to authenticate with my dad's email address and non-null password to his email server, but on the one that fails, the only auth attempt it ever makes is
`DEBUG SMTP: protocolConnect returning false, host=smtp.bananatag.com, user=john, password=<null>`, it never uses the hardcoded username and password that the successful machine uses.

This is the code used to send the emails:
```
    val recipients = listOf(customers.filter { it.email != "" }[1])

    val props = Properties()
    props["mail.smtp.host"] = "smtp.bananatag.com"
    props["mail.smtp.port"] = 587
    props["mail.smtp.starttls.enable"] = true
    props["mail.smtp.auth"] = true

    val session = Session.getDefaultInstance(props, object: Authenticator() {
        override fun getPasswordAuthentication(): PasswordAuthentication {
            return PasswordAuthentication(*email hardcoded here*, *password hardcoded here*)
        }
    })

    val mailer = MailerBuilder
        .usingSession(session)
        .withDebugLogging(true)
        .withThreadPoolSize(10)
        .withThreadPoolKeepAliveTime(5000)
        .withConnectionPoolCoreSize(2)
        .withConnectionPoolMaxSize(10)
        .withConnectionPoolClaimTimeoutMillis(60000)
        .withConnectionPoolExpireAfterMillis(1800000)
        .async()
        .buildMailer()

    recipients.forEachIndexed { idx, customer ->
        val email = *email is built here*

        val asyncResponse = mailer.sendMail(email, true)
    }
```

I would love to get some information about why this might be behaving differently on different machines, and how I might be able to go about fixing it.  Thank you!

**Comment by bbottema** [comment]
I don't know why it would behave differently, unless the underlying Jakarta Mail library behaves differently.

However in the auth failed txt, I don't actually see any failure. In the failed txt I see you are using _user=john_ and in the successful one _user=your dads email_ (or Cameron). Are you sure you are using the same credentials on both systems?

Aside from the OS being different, the network could be different too, although in this case I would expect timeouts or things of that sort.

One other thing I noticed from your log files is that at the end, the SMTP server returns a different list of supported extensions, which is very odd:

![image](https://user-images.githubusercontent.com/2115718/112486985-ad6d1380-8d7c-11eb-885a-26b32480c014.png)

Is it possible you are routed to a different SMTP server from the other network, because of regional optimization or something? Something you often see with cloud based mail server solutions.

**Comment by jollygreenegiant** [comment]
Yeah the credentials should be identical.  I'm running identical versions of the app using that code snippet I showed above on both machines.  It looks like it's pulling credentials from the machine it's running on (that's where it's getting `Cameron` (me) and `john` (my dad) from, I'm not giving it that), but I can't figure out why on my machines, it picks up the hardcoded credentials from that code snippet, but on his machine it seems to ignore them.  

This works for me on both a Mac and a Windows machine, so I don't think it's an OS difference.  He and I live ~100 miles apart, so I'm not sure if that would affect regional routing or anything.  Would it be worth trying a different mail host?  He has one through bananatag that I'm using here, but I could also try his GoDaddy one.  I know very little about the intricacies of mail servers and that kind of thing, so I'm not sure what, if any, difference that would make.

**Comment by bbottema** [comment]
There's not much that I can do here. It shouldn't be possible to behave differently depending OS, the JVM makes sure of that. The only thing that can influence the behavior from outside of the application are things like system variables, credentials, property files. Unless I get something more concrete to go on, I'm closing this for now...
