### ISSUE TITLE
double name attachments doesn't work

### ISSUE THREAD

**Issue by DasTier1** [bbottema/simple-java-mail#310]
Seems to be still there in Simple Java Mail 6.5.0:
package org.simplejavamail.converter.internal.mimemessage;
MimeMessageParser : Line 508 : 
```
public Map<String, DataSource> getAttachmentList() {
   return this.attachmentList;
}
```

WIll not work with two attachments named e.g.:
TSOL0038
TSOL0038.AUF

i.e. no suffix in one case.
This case is used for electronic billing for healthcare in Germany.
Works fine with different suffixes.

#249

**Comment by bbottema** [comment]
On MimeMessageParser:508 I have a different line. Are you sure you're testing with 508? Perhaps you could provide me with a sample email EML that has this problem?

**Comment by bbottema** [comment]
Hey I release 6.5.1 which might have something to do with this. Would you mind giving that version a try?

**Comment by bbottema** [comment]
Any update?

**Comment by DasTier1** [comment]
Now it works perfect!
Goord work!
Thank you!
