### ISSUE TITLE
Email Validator

### ISSUE THREAD

**Issue by dshurt** [bbottema/simple-java-mail#32]
Version: 2.1

Issue: The Email validation goes into an infinite loop while trying to build the pattern matcher for the following email address: ewiuhdghiufduhdvjhbajbkerwukhgjhvxbhvbsejskuadukfhgskjebf@gmail.net (Obviously a random test case but, the behavior is surprising)

Trace: EmailValidationUtil  line: 55

Version: 3.0 worked (this maybe due to the default behavior to skip the validator)

**Comment by bbottema** [comment]
I think you have the versions mixed up? Validation was turned back on in 3.0.0.

I copied this issue to the project that manages the email validation.

**Comment by dshurt** [comment]
Yeah, I may not have read the release notes correctly.    So if the validation is back on in 3.0.0 and it works then issue is already resolved.  It may only affect that version (2.1)

I'll close this and then you can leave the email validator issue open if someone want to look into it more.

Thanks for your help.  I appreciate the work you've done on this library.

**Comment by bbottema** [comment]
I'll check the specific address you provided tomorrow and see if it solved.

**Comment by bbottema** [comment]
I verified this address is not a problem anymore since release v3.0.0.
