### ISSUE TITLE
Markenwerk S/MIME Utils seem to have shut down :(

### ISSUE THREAD

**Issue by cbollmeyer** [bbottema/simple-java-mail#334]
Hi, 

seems the Markenwerk S/MIME project (https://github.com/markenwerk/java-utils-mail-smime) has been archived and they also ignored the three pull requests you made, so 1.0.8 seems to be the last version there is. Which is a little unfortunate as the S/MIME module relies on that library and we have the situation that (some) signed-only mails seem not to be recognized correctly, but get an S/MIME state of NEITHER, which apparently hinders further processing of signed attachments. Are there any plans to either fork that project (I've seen there already is a fork, but it's still at 1.0.8 too) or replace that code somehow?

In any case, thanks for that great library, in particular the Outlook parser!

-- Ch.

**Comment by bbottema** [comment]
Indeed there are plans to fork it officially. I already obtained permission from the current maintainer (who archived it, which was also a fork) and the past developers of the original code to change the license to Apache v2.

So the ball is completely in my court, but for past weeks I have been preoccupied completely. I surely plan to bring the library further but I don't have a time span for you at the moment. Sorry for that.
