### ISSUE TITLE
Getting a response from SMTP server

### ISSUE THREAD

**Issue by edoarsla** [bbottema/simple-java-mail#336]
Love the simplicity of the API, but am having a hard time getting the server response.  I primarily want to get the message-id that was issued by the SMTP server.

When debug is enabled, I see the last line of debug is:
250 2.0.0 OK <CH0PR11MB5411F51EEE798B9E71C8D021DFDC9@CH0PR11MB5411.namprd11.prod.outlook.com> [Hostname=CH0PR11MB5411.namprd11.prod.outlook.com]

Any pointers on how I can get this data?

Thank you

**Comment by bbottema** [comment]
From the documentation website:

![image](https://user-images.githubusercontent.com/2115718/133621505-9f120ec6-b034-4431-83a6-c2aae2290b2b.png)

**Comment by edoarsla** [comment]
Thank you for a speedy reply!

I did use that, but here's what I see:
From debug:
`250 2.0.0 OK <CH0PR11MB5411830E23F2554124D54555DFDC9@CH0PR11MB5411.namprd11.prod.outlook.com> [Hostname=CH0PR11MB5411.namprd11.prod.outlook.com]`

From `email.getId()`
`<1089376785.1.1631799412931@[192.168.1.33]>`

Looks like `email.getId` returns a locally assigned id that is sent to the SMTP server.  But the server creates a new id.  So far this has been the case with Outlook and GMail.

I'm trying to capture that server created id, so that I can co-relate it with potential email responses.

Thank you again!!

**Comment by bbottema** [comment]
As far as I know, the SMTP server should **not** change the message ID at all.

**Comment by bbottema** [comment]
Here's an interesting bit: https://social.technet.microsoft.com/Forums/en-US/132df54c-871b-4e9d-98c9-5b5caa993322/custom-message-id-replaced-by-outlook-smtp-server?forum=exchangesvrclients

**Comment by edoarsla** [comment]
That is interesting.  The nature of my goal prevents me from making changes in the SMTP server config (sending on behalf of 3rd party clients without access to their server config).

I agree with the premise that SMTP should not change the ID.
However, given that there are circumstances where it may, and granted this is beyond the scope of this library - are you familiar with the way that a server response could be captured - for example maybe using `ConnectionListener` or `TransportListener`.

Since the SMTP ID is getting logged using debug, I'm hoping there may be a way to capture it - even if it's collecting that debug data and then parsing it out.

Thanks again.

**Comment by edoarsla** [comment]
Ok.  Here's a way to capture raw server response - in case it helps someone else:

```
        try
        {
            final ByteArrayOutputStream baos = new ByteArrayOutputStream();
            final String utf8 = StandardCharsets.UTF_8.name();
            final PrintStream serverResponseStream = new PrintStream( baos, true, utf8 );
            mailer.getSession().setDebugOut( serverResponseStream );

            mailer.sendMail( email );
            log.warn( "\n>>>>>>>>>>>>>\n\n{}\n\n<<<<<<<<<<<<<<\n", baos.toString( utf8 ) );
        }
        catch ( UnsupportedEncodingException e )
        {
            e.printStackTrace();
        }
```

**Comment by bbottema** [comment]
That's horrible! :D

I'll have a look for a better alternative when I get some time. For now I understand you have found an acceptable workaround.

**Comment by bbottema** [comment]
I don't think there's anything I can do here. This is non-standard behavior to begin with, undefined in any spec as far as I can see  and second the output would be different for each SMTP server that goes rogue.

Closing this until it makes more sense to build in a workaround.
