### ISSUE TITLE
Working With S/MIME Question

### ISSUE THREAD

**Issue by johndoeaman** [bbottema/simple-java-mail#337]
Hi I'm quite new on this email with java, I want to send an email with S/MIME so it will produce a check sign (verified) on gmail. I've got my email certificate a pfx file from Actalis, but don't know where to start.
I've manually tested it by applying it through Outlook and it succeed. Now, I wanted to try it programmatically.

Any help would be appreciated, thanks in advance.

**Comment by bbottema** [comment]
Ok so Simple Java Mail is pretty straightforward: you can [encrypt and you can sign](https://www.simplejavamail.org/features.html#section-sending-smime), or both.

![image](https://user-images.githubusercontent.com/2115718/134311089-0185e927-ac0a-47c1-bbc7-a4a76e117c8f.png)

From the sound of it, you want to sign your emails and for that you need a Pkcs12 keystore which holds your certificate. Unfortunately, you have a different format (.pfx), from which you need to extract the .crt and .key files, so you can build a new Pkcs12 keystore.

- [Getting the .crt and .key out of your .pfx](https://www.ibm.com/docs/en/arl/9.7?topic=certification-extracting-certificate-keys-from-pfx-file)
-[Generating a new .pkcs12 keystore with a .crt and .key](https://stackoverflow.com/questions/22646533/unable-to-load-certificates-when-trying-to-generate-pfx-file/22647106#22647106)

This is a nasty process with a steep learning curve, but at least the objective is clear. Good luck.
