### ISSUE TITLE
How to limit number of emails per connection

### ISSUE THREAD

**Issue by kurtinaitis** [bbottema/simple-java-mail#348]
I am using batch-module and talking to SMTP server which limits number of messages I can send using a single connection.
How do I configure simple-java-mail so that the connection is closed after a 1000 of sent messages and a new one is opened to send more?
I see there is some expiration policy configurations deep down the implementation. But they mostly deal with timeouts. Is it possible to expire connection based on message number?

**Comment by bbottema** [comment]
This is an interesting question. Resource pooling is usually based on utilization in a certain time frame; that's what you throttle with these max connections and timeouts. What you are suggesting is a fixed resource budget no matter when or in what capacity you request it. This is generally not how resource providers like a SMTP server work.

Is this a real use case? How did you come up with the number 1000 and are you free to use those 1000 however you want or are there performance restrictions to take into account?

**Comment by kurtinaitis** [comment]
> Is this a real use case? How did you come up with the number 1000 and are you free to use those 1000 however you want or are there performance restrictions to take into account?

The use case is real, but maybe I misunderstood the limitation we are hitting.
After some (~thousand) of successful emails we start to get 
`450 4.7.1 <name@example.com>: Recipient address rejected: Policy Rejection- Quota Exceeded.`
I'm struggling to understand what quota is that. 
The server is postfix. Its admins hinted we probably hit `smtpd_recipient_limit`, which is set to 1000. I initially thought it is the number of emails per session. But probably it isn't. After reading docs, I think it is number of recipients in an email. But we always use a single recipient in all emails because the bodies are unique. So this probably is not the thing.
I think I have to make the ops look harder at their logs...

**Comment by bbottema** [comment]
So did you find out what was causing this limit? I'm closing this issue btw, I don't think there's anything I can do here... I'll happily reopen if that changes.
