### ISSUE TITLE
Attachment size is not right for attachment is eml or outlook item.

### ISSUE THREAD

**Issue by Jacobliu8** [bbottema/simple-java-mail#349]
when I use the nice library to get eml attachment  I found there are missed attachment when both attachment is eml or outlook msg. Could you pls check that?

here is my sample email eml file
[test_for_attachment.zip](https://github.com/bbottema/simple-java-mail/files/7451369/test_for_attachment.zip)

I try to get the eml attachement should be two but only get one.

![image](https://user-images.githubusercontent.com/8746083/139637088-48946591-da96-4c53-a8f5-d80b212cf656.png)

**Comment by Jacobliu8** [comment]
by reading your code seems the attachment used a map for store the attachmentList. if name is both "unnamed" will missed the attachment.  Can you help to fix the issue? thanks

**Comment by bbottema** [comment]
Which version are you on? I'm simply getting an error, so I'm not even able to read the eml file (not good either).

**Comment by bbottema** [comment]
Duplicate of #351

**Comment by bbottema** [comment]
This all should work fine now in 6.7.0, which was just released. Please give it a try.
