### ISSUE TITLE
emlToEmail() and mimeMessageToEmail() missing off attachments

### ISSUE THREAD

**Issue by atmcq** [bbottema/simple-java-mail#351]
See examples attached. All 3 email files have 2 attachments, however only outlookMsgToEmail() is picking up both of them, emlToEmail() and mimeMessageToEmail() only pick up one attachment. 

We will grab the source and try to debug but if there is any chance you know what this might be please let me know as we have a customer problem with this one.

[MimeProblem.zip](https://github.com/bbottema/simple-java-mail/files/7529231/MimeProblem.zip)

**Comment by bbottema** [comment]
Actually in the latest working code it even fails. It seems the filename is missing from the EML data and it simply leaves the name empty. I don't see any name information in the multipart data either, but somehow Thunderbird names both "ForwardedMessage".

**Comment by bbottema** [comment]
I figured out why (in the current code at least): the attachments are both named the same and currently attachments with same name are not allowed. I'll fix that and commit it to the _develop_ branch. But I don't think I can do a release any time soon as I'm in the middle of a bunch of changes for the 7.0.0 release.

**Comment by bbottema** [comment]
Hmm, oddly, I changed it to that for https://github.com/bbottema/simple-java-mail/issues/249 (MimeMessageParser doesn't handle multiple attachments with the same name correctly)

**Comment by bbottema** [comment]
Ok, fixed in develop. Thanks so much for your test data!

**Comment by atmcq** [comment]
Thanks for picking this up so quick. Is there any way you could add an option to use an Outlook style approach, e,g. to use Thread-Topic for the attachment name, rather than the Thunderbird style "ForwardedEmail.eml"? We have a few legal industry customers that really don't like the idea of an email that they send in to our app "changing" (in their words), as they are coming from using exclusively Outlook.

**Comment by bbottema** [comment]
That's tricky because the name is set before any nested messages are processed. The would need to be adjusted so that the name is updated after parsing its associated message and then only if it contained the header thread-topic (if that is indeed the canonical approach to handling Outlook messages). Not saying it can't be done, but I haven't looked into that.

**Comment by atmcq** [comment]
Is there any possibility of porting this fix into a 6.6.2 release? This is causing us some difficulties with some customers.

if that isn't possible, do you have a rough ETA for 7.0.0? Finally if you don't please let us know so we can look into branching and fixing ourselves for now (I assume [9d8dda88dc529f94c2ffaee42b86482936a70454](url) and [a20655acd6a9960fc8ec4a6a4167299ba452a54e](url) is what we'd need).

**Comment by atmcq** [comment]
FYI we have done a quick branch of simple-java-mail-6.6.1.jar for now, and will pick up 7.0.0 when it is released. Thanks for your help on this.

**Comment by bbottema** [comment]
Released in 6.7.0. Cheers!
