### ISSUE TITLE
EmailAddressValidator no longer available in v7.0

### ISSUE THREAD

**Issue by goodale** [bbottema/simple-java-mail#370]
after updating pom to use 7.0.0, I  am getting 'EmailAddressValidator' cannot be resolved.

**Comment by bbottema** [comment]
So `EmailAddressValidator` is from the old underlying validation [email-rfc2822-validator](https://github.com/bbottema/email-rfc2822-validator), which was replaced by the excellent [JMail](https://github.com/RohanNagar/jmail). So if you used `EmailAddressValidator` directly, instead you would do something like `JMail.isValid(email)`. Please see https://github.com/RohanNagar/jmail#usage for usage and examples.

However, I think I should get on some migration notes and I pretty much forgot to update the documentation website on this topic. So thanks for that reminder 👍

**Comment by goodale** [comment]
thanks for the quick resolution.  I figured it was just a documentation issue and adding JMail and using JMail.isValid works like a charm

**Comment by bbottema** [comment]
[Migration notes for 7.0.0](https://www.simplejavamail.org/migration-notes-7.0.0.html) are up!
