### ISSUE TITLE
Set Content-Transfer-Encoding to be quoted-printable

### ISSUE THREAD

**Issue by maheshwarigagan** [bbottema/simple-java-mail#374]
Is there a way for me to specify Content-Transfer-Encoding to be `quoted-printable` always for messages built using the library?

context: in order to comply with RFC 5322, where we shouldn’t have any line of content exceeding 78 characters.
https://datatracker.ietf.org/doc/html/rfc5322#section-2.1.1

**Comment by bbottema** [comment]
What problem does this solve?

You do realize this specification detail was written for big green monitors from the 80's, right? And it is merely a recommendation by the writers:

> The more conservative 78 character recommendation is to accommodate
>    the many implementations of user interfaces that display these
>    messages which may truncate, or disastrously wrap, the display of
>    more than 78 characters per line

This was specified in 2001, first drafted in 1996, which through a chain of succession replaced 1977's rfc733 which first mentions this.

So unless we're dealing with real world issues, I'm inclined to not acting on this.
