### ISSUE TITLE
Expose MailerException

### ISSUE THREAD

**Issue by proofrock** [bbottema/simple-java-mail#376]
Hi,
   first of all, thank you for this library, it works very well for me. One snag I have, I generally use it like this (Kotlin code, but should be very similar in Java):
   
```
try {
    mailer.sendMail(email)
    recSuccessOnDb(email)
} catch (me: Exception) {
    recFailureOnDb(email, me)
}
```

The logic is: I record in the DB the error message, and log separately in a file the stacktrace. But when a `Third party error` happens, the actual error is in the _cause_ exception, so I would like to do something like:

```
try {
    mailer.sendMail(email)
    recSuccessOnDb(email)
} catch (me: MailerException) {
    if (me.message == "Third party error") 
        throw me.cause
} catch (e: Exception) {
    recFailureOnDb(email, me)
}
```

Now, this fails because `MailerException` is package private, or at least Kotlin complains because of this. Is it possible to expose the class?

I am using 7.0.0.

Thanks a lot again,

-- Germano

**Comment by bbottema** [comment]
All the internal Exception types extend MailException which is exposed and can be caught. Does that help?

**Comment by proofrock** [comment]
It did! Thank you!
