### ISSUE TITLE
Issues after enabling Connection pooling, java.net.SocketException: Broken pipe and Connection closed by remote

### ISSUE THREAD

**Issue by thereader01** [bbottema/simple-java-mail#385]
We use batch-module:1.1.2 and the below properties for connection pooling,

simplejavamail.defaults.connectionpool.coresize=2
simplejavamail.defaults.connectionpool.maxsize=5
simplejavamail.defaults.connectionpool.claimtimeout.millis=60000
simplejavamail.defaults.connectionpool.expireafter.millis=900000

when is there more load on the server we see the below error's,
java.net.SocketException: Broken pipe 
java.net.SocketException: Connection closed by remote

@bbottema - Could you please suggest if can tune our connection pooling propeties in any other way.
We connect to to a single SMTP server, which has max consurrent connections from single IP as 300

**Comment by bbottema** [comment]
With these settings, you would have a maximum of 5 concurrent connections at any time, correct? Perhaps your server isn't too happy about long running connections, in which case you could reduce the _expireafter_ to keep the connections fresh. Also not that it should be an issue, but that's a very long _claimtimeout_, implying sending emails could take up to a minute before giving the connection to the next thread trying to claim it.
