### ISSUE TITLE
EmailBuilder is missing jakarta.mail.internet.MimeMessage

### ISSUE THREAD

**Issue by BrutalCSkakan** [bbottema/simple-java-mail#386]
Hello! I'm using the simple-java-mail and dkim-module maven packages, version 7.1.0.

However, when running this code:
```
EmailPopulatingBuilder emailPopulatingBuilder = EmailBuilder.startingBlank()
 .from(EMAIL_FROM)
 .to(EMAIL_TO)
 .withSubject(EMAIL_SUBJECT)
 .withHTMLText(html)
```

I get an error saying:
```
java: cannot access jakarta.mail.internet.InternetAddress
  class file for jakarta.mail.internet.InternetAddress not found
```

If I go into the EmailPopulatingBuilder class and EmailBuilder class I can see that no jakarta libraries are loaded. 
If I import jakarta core, I get other issues that breaks the code. 

Shouldn't the lastest 7.1.0 version be able to compile the code together with all the needed jakarta classes?

simple-java-mail is missing atleast these:

import jakarta.activation.DataSource;
import jakarta.mail.Message;
import jakarta.mail.internet.InternetAddress;
import jakarta.mail.internet.MimeMessage;
import jakarta.mail.util.ByteArrayDataSource;

**Comment by bbottema** [comment]
All the needed dependencies are names in the Maven dependencies and the library runs just fine. It seems you are missing Jakarta altogether on the class path. Are you manually managing dependencies, or excluding dependencies? Is it missing on your application server if you use one?

These dependencies are necessary: https://github.com/bbottema/simple-java-mail/blob/ac08444d60ece0f4c9349a3b5e5a638b8538ed66/modules/core-module/pom.xml#L26

**Comment by mkhl** [comment]
i just ran into this problem and in case anyone else does too and finds this issue:
spring-boot-starter-parent defines properties for these jakarta versions (and others) that are too old to work with simplejavamail. try upgrading the parent or overriding those properties, but the latter may break other spring dependencies.

- jakarta-mail.version
- jakarta-activation.version
