### ISSUE TITLE
EmailConverter NullPointerException getDate

### ISSUE THREAD

**Issue by fatjon-etemi** [bbottema/simple-java-mail#392]
Version: 7.1.1

Hi everyone,

I have got an error when trying to read the HTML Body of specific Outlook E-mails (.msg file)
I would upload the file but it's not possible here.

Code:
```java
email = EmailConverter.outlookMsgToEmail(new ByteArrayInputStream((byte[]) getValue("DOC_IMAGE")));
```

Stacktrace:
> java.lang.NullPointerException
> at org.simplejavamail.outlookmessageparser.model.OutlookMessage.getDate(OutlookMessage.java:865)
> at org.simplejavamail.internal.outlooksupport.converter.OutlookEmailConverter.buildEmailFromOutlookMessage(OutlookEmailConverter.java:102)
> at org.simplejavamail.internal.outlooksupport.converter.OutlookEmailConverter.outlookMsgToEmailBuilder(OutlookEmailConverter.java:85)
> at org.simplejavamail.converter.EmailConverter.outlookMsgToEmailBuilder(EmailConverter.java:239)
> at org.simplejavamail.converter.EmailConverter.outlookMsgToEmail(EmailConverter.java:221)
> at org.simplejavamail.converter.EmailConverter.outlookMsgToEmail(EmailConverter.java:213)

**Comment by bbottema** [comment]
Is it possible for you to share the email to me personally? I would like to investigate.

**Comment by bbottema** [comment]
Bump

**Comment by bbottema** [comment]
Any update on a sample I can investigate? Will close this soon otherwise as non-actionable.

**Comment by fatjon-etemi** [comment]
> Any update on a sample I can investigate? Will close this soon otherwise as non-actionable.

Hello, sorry for the late response. I need to search for the mail. What‘s your e-mail address?

**Comment by fatjon-etemi** [comment]
I found something and have sent it to you by mail.

**Comment by bbottema** [comment]
Hhm, I didn't receive anything yet. Can you please double check the address?

**Comment by fatjon-etemi** [comment]
Did you check your junk? Is this your e-mail: benny@bennybottema.com

**Comment by bbottema** [comment]
Thanks, I'll have a look.

**Comment by bbottema** [comment]
I just did a test with the .msg file you sent me, but that won't even open in Outlook itself, and it won't read in outlook-message-parser, the library used by Simple Java Mail, either:

![image](https://github.com/bbottema/simple-java-mail/assets/2115718/6824531e-f577-4766-b5ba-247e41f8311c)
