### ISSUE TITLE
Add HEIC and WEBP support

### ISSUE THREAD

**Issue by piu130** [bbottema/simple-java-mail#401]
Could you add support for the HEIC image format (`image/heic`)?
Would it be enough to just add it [here](https://github.com/bbottema/simple-java-mail/blob/6d2049387a4c31f08b879a34d657cab2c325942b/modules/core-module/src/main/java/org/simplejavamail/internal/util/ImageMimeType.java#L13)?

**Comment by bbottema** [comment]
Can you please tell me where the support is failing according to you? The source you are referring to is for dynamically resolving embedded images from classpath.

**Comment by piu130** [comment]
Sorry it seems like I had a version mismatch. It works now! Thanks for your fast response. It's a great project with great support :)

**Comment by bbottema** [comment]
Still, I've added .heic support for dynamically resolving embedded images from classpath  :)
