### ISSUE TITLE
S/MIME signing using environment variables

### ISSUE THREAD

**Issue by MakakWasTaken** [bbottema/simple-java-mail#406]
Hello,

I have recently started using this library and is a bit of a rookie when it comes to Java. 
I want to send a message that uses the S/MIME signing, but for the signing I need to use my private certificate. This has brought on some questions in regards to security. 

Is it safe to store my .pfx or .p12 file in the resources folder (This would then be stored on my github). My understanding is that it brings on problems, because the password of the certificate can be brute-forced.

Is it possible to load the certificate from either a KeyStore or an environment variable instead?

**Comment by bbottema** [comment]
Well that's really beyond the scope of the library. You control where and how you store and retrieve your key/pk12 store and subsequently use it (ie. invoke Simple Java Mail or do something else).
