### ISSUE TITLE
Add new feature Content-Description #404 to version 6

### ISSUE THREAD

**Issue by CrisVnait** [bbottema/simple-java-mail#408]
Thank you very much for the quick help and reactions in issue https://github.com/bbottema/simple-java-mail/issues/404 !
Unfortunately it seems, that we can't migrate to version 7.3.0 with Jakarta 2.0.1, because we use Spring Boot 2.x.x (see https://stackoverflow.com/questions/68955884/update-jakarta-mail-1-6-5-to-2-0-1). We can't wait for Spring Boot 3, which supports Jakarta 2.
Would it be possible, that you also provide the 'content description'-feature in version 6.x.x?

Sorry for the circumstances and thank you :)

**Comment by bbottema** [comment]
I would love to support for lines for updates like these, but the fact is 6.x.x and 7.x.x have deviated too far and adding a new feature like this translates all the way from the builder api, property and Spring property support, to the conversion and sending api, and then also Outlook/MimeMessage conversion support back to Email objects.

To support and test that in both streams is just too much for me alone. So unfortunately, I cannot help you here.
