### ISSUE TITLE
Sending message without (plain text) bodypart

### ISSUE THREAD

**Issue by MakakWasTaken** [bbottema/simple-java-mail#409]
I am currently trying to send a message where there is no body, only an attachment. I have not yet been able to work this out and wanted to ask if this was even possible with this library. I have mostly tried not supplying the withPlainText option to the EmailBuilder, but this does not seem to help my case. 

The idea is to send an email where the first item "Content-Type" is "application/..." instead of "multipart/mixed" and also an attachment as the first bodypart.

If any more information on my case is needed please feel free to write :)

**Comment by bbottema** [comment]
This should work without problem, but why are you concerned about the specific underlying mime structure? If you use the builder api to just set an attachment without any text/html content, it should work and show empty email in any client with just an attachment.

Which version are you using?

**Comment by MakakWasTaken** [comment]
It is a requirement for a system that I am sending the email to so it is not really because of visual representation. The system has the requirement that there is only one mimepart and that it for example has the `Content-Type: application/xml`, `Content-Transfer-Encoding: binary` and `Content-Disposition: attachment; filename=...`

I am currently using 7.4.0

**Comment by bbottema** [comment]
Well it's not so much about visual representation as it is about using a Mime structure that is parsed reliably by all email clients. Simple Java Mail is about providing an abstract layer on top of the low level Mime configuration api, and as such making it nice and easy to create and validate reliable emails, not shoehorn the result into a user-specific Mime structure.

Your use case is exactly the opposite; you don't particularly care about a reliable Mime structure, rather you need a very specific structure to suit your needs. You should do this by directly using Jakarta's SMTP mime library yourself.
