### ISSUE TITLE
 Emails contain "donotreply@unknown-from-address.net" in the "From" field when the original had no email address in the "From" field 

### ISSUE THREAD

**Issue by jigneshThakkar** [bbottema/simple-java-mail#414]
It is not able to retrieve the from email address.

**Comment by jigneshThakkar** [comment]
![image](https://user-images.githubusercontent.com/12814680/183378054-d64e45c4-21df-48af-a84f-ea3d736f35db.png)
Please find this attachment for the example

**Comment by bbottema** [comment]
When does this happen? If I'm not mistaken this is from converting Outlook messages and the problem is we have no way of knowing the from address is empty or problematic.

**Comment by jigneshThakkar** [comment]
Hey,

Yes it is happening when we convert from Outlook messages. We haven't any from email address. Also, as per my above attachment there are two field in outlook named as "email account" and "name" contains the value. Is there any way we can fetch those name ?

**Comment by bbottema** [comment]
They might have been parsed as headers, but I can't check that without the .msg

**Comment by jigneshThakkar** [comment]
[Untitled.zip](https://github.com/bbottema/simple-java-mail/files/9299722/Untitled.zip)

I have attached the msg file here. Please look at once . Let me know if you need more details

**Comment by jigneshThakkar** [comment]
Any Update?

**Comment by bbottema** [comment]
Can you make an example where the to-address is not the same? I'm not sure which Outlook field is the From if the To field has the same value. It's aq bit trial-and-error unfortunately with Outlook messages.

**Comment by bbottema** [comment]
Bump.

**Comment by bbottema** [comment]
Any update, @jigneshThakkar?

**Comment by atmcq** [comment]
Hi @bbottema attached is an example email behaving in this way
[Issue 1 - Sent mail.zip](https://github.com/bbottema/simple-java-mail/files/11704871/Issue.1.-.Sent.mail.zip)

**Comment by bbottema** [comment]
So I just did a test to double check. The results I see with outlook-message-parser, the library used by Simple Java Mail, contains exactly the same From: details that I see when opening the .msg directly with Outlook. I don't know what else to make of this.

![image](https://github.com/bbottema/simple-java-mail/assets/2115718/1421e7ef-9500-4b46-a361-213526ffd793)

![image](https://github.com/bbottema/simple-java-mail/assets/2115718/e39767b8-1042-470f-9f39-826f9fe94a6d)

I do see the email address you mentioned in the properties list, mapped to a bunch of numbers that don't mean anything to me:

![image](https://github.com/bbottema/simple-java-mail/assets/2115718/d8151f64-a576-4eb2-85b2-1b6ec8ce3189)
