### ISSUE TITLE
android studio build error when implmenting     implementation ('org.simplejavamail:simple-java-mail:7.5.0')

### ISSUE THREAD

**Issue by ckesho** [bbottema/simple-java-mail#423]
Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'LICENSE-2.0.txt' from inputs:
      - C:\Users\user\.gradle\caches\modules-2\files-2.1\org.simplejavamail\simple-java-mail\7.5.0\f54b03c0a7599223a1a227ae63d586339851df1d\simple-java-mail-7.5.0.jar
      - C:\Users\user\.gradle\caches\modules-2\files-2.1\org.simplejavamail\core-module\7.5.0\c631807582d189c86fe0f42f003305da1ffb1da4\core-module-7.5.0.jar
     Adding a packagingOptions block may help, please refer to
     https://developer.android.com/reference/tools/gradle-api/7.3/com/android/build/api/dsl/ResourcesPackagingOptions
     for more information

**Comment by ckesho** [comment]
Should be as simple as renaming the duplicate file

**Comment by ckesho** [comment]
No luck. This solution will allow it to sync but not build. I tried eliminating the module it was complaining about with no success.

![image](https://user-images.githubusercontent.com/12022464/205696679-f06e0e13-68ba-4a01-a2f5-18fe21cff93a.png)
![image](https://user-images.githubusercontent.com/12022464/205696788-4d0f65d7-30a8-49b7-a854-aa56b1500056.png)

**Comment by bbottema** [comment]
All of this means little to me, to be honest. I'm guessing it's a Gradle dependency management thing where you have to exclude jetbrains' own non-null annotations? At any rate, not really something I can fix on my end.

**Comment by ckesho** [comment]
Ok, thanks for checking it out!
