### ISSUE TITLE
Which dependencies to read an EML file ?

### ISSUE THREAD

**Issue by bnjdpn** [bbottema/simple-java-mail#431]
Hello,

I’m trying to use Simple Java Mail to read the content of an EML file but when doing `EmailConverter.emlToEmail()` I have a NoClassDefFoundError `jakarta/mail/MessagingException`. 

What am I missing ?

Thanks.

**Comment by bbottema** [comment]
Yes, in the documentation on the [architecture and modules](https://www.simplejavamail.org/modules.html#navigation), you can read the core dependencies. At the very least you need the core library on which Simple Java Mail builds: Jakarta Mail.

Here's the rest which are needed depending on which functions you use:

- org.slf4j:slf4j-api
- com.sun.mail:jakarta.mail
- com.sun.activation:jakarta.activation
- jakarta.xml.bind:jakarta.xml.bind-api
- jakarta.annotation:jakarta.annotation-api
- com.sanctionco.jmail:jmail (address validation)
