### ISSUE TITLE
issue converting bytearraydatasource to DataSource for attachments

### ISSUE THREAD

**Issue by goodale** [bbottema/simple-java-mail#433]
I'm trying to add an attachment that is coming as a bytearray from a database record.   This worked fine javax but 
after migrating to Jakararta I'm getting error, "class jakarta.mail.util.ByteArrayDataSource cannot be cast to class jakarta.activation.DataSource"

**Comment by bbottema** [comment]
Can you please provide an example that will fail?

**Comment by goodale** [comment]
any email with an attachment is failing.  This was working previously and I suspect there's some conflict with jakarta libraries. 

One item i found that may have been an issue is the following code.   I made the update but it didn't fix the issue.

```
/*relevant imports */
import jakarta.mail.util.ByteArrayDataSource;
import org.apache.tika.Tika;

Collection<Email_attachments> attachments = rec.getAttachments();
for (Email_attachments attachment : attachments) {
String fileType = defaultTika.detect(attachment.getAttachment());
DataSource ds = new ByteArrayDataSource(attachment.getAttachment(), fileType);  
 simpleAttachments.add(ar);
}
```
the above code worked fine in the javax days and even recently after upgrading to latest simplejavamail.   But even more recently started getting exceptions.   I've changed from the Interface for DataSource to the explicit ByteArrayDataSource but still get exceptions.

`**ByteArrayDataSource** ds = new ByteArrayDataSource(attachment.getAttachment(), fileType);  

`org.simplejavamail.mailer.internal.MailerException: Failed to send email [<server>], reason: Unknown error    at org.simplejavamail.mailer.internal.SendMailClosure.handleException(SendMailClosure.java:97)at org.simplejavamail.mailer.internal.SendMailClosure.executeClosure(SendMailClosure.java:91)    at org.simplejavamail.mailer.internal.AbstractProxyServerSyncingClosure.run(AbstractProxyServerSyncingClosure.java:56)         at org.simplejavamail.mailer.internal.MailerImpl.sendMail(MailerImpl.java:345)  at org.simplejavamail.mailer.internal.MailerImpl.sendMail(MailerImpl.java:331)  at com.regattacentral.cron.EmailQueueJob.sendEmail(EmailQueueJob.java:71)      at com.regattacentral.cron.EmailQueueJob.sendMessage(EmailQueueJob.java:142)    at com.regattacentral.cron.EmailQueueJob.execute(EmailQueueJob.java:128)       at org.quartz.core.JobRunShell.run(JobRunShell.java:202)        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) Caused by: java.lang.RuntimeException: Provider for jakarta.activation.spi.MailcapRegistryProvider cannot be found    at jakarta.activation.FactoryFinder.find(FactoryFinder.java:90)         at jakarta.activation.MailcapCommandMap.getImplementation(MailcapCommandMap.java:696)  at jakarta.activation.MailcapCommandMap.loadFile(MailcapCommandMap.java:284)    at jakarta.activation.MailcapCommandMap.<init>(MailcapCommandMap.java:154)     at jakarta.activation.CommandMap.getDefaultCommandMap(CommandMap.java:60)       at jakarta.activation.DataHandler.getCommandMap(DataHandler.java:128)   at jakarta.activation.DataHandler.getDataContentHandler(DataHandler.java:590)  at jakarta.activation.DataHandler.writeTo(DataHandler.java:290)         at jakarta.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1670)   at jakarta.mail.internet.MimeMessage.writeTo(MimeMessage.java:1888)    at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1300)         at org.simplejavamail.mailer.internal.util.TransportRunner.lambda$sendMessage$0(TransportRunner.java:48)       at org.simplejavamail.mailer.internal.util.TransportRunner.runOnSessionTransport(TransportRunner.java:68)`

**Comment by goodale** [comment]
note:   I was having issues with a new 'angus' jar and excluded that in the pom after seeing other reports of conflicts with it and jakarta

**Comment by goodale** [comment]
I reverted back to simplejavamail 7.1.0 and things are working again.   I'm running on Tomcat 9.x btw but had what i thought were the appropriate jakarta activation dependencies in the pom.

I plan to stick with 7.1.x until there's time to migrate the application fully to Jakarta and then will try 7.5.2

**Comment by bbottema** [comment]
Yeah this is not actionable for me at all. You didn't provide any code that demonstrates how you used Simple Java Mail, no dependency tree, I don't even know which version you are on.

Put yourself in my shoes and decide what you would need to know in order to go and investigate. At any rate, I think you're right in that there's some dependency clash, but how I can't tell from your report.

Closing until I'm convinced it's not a user error.

**Comment by BartBM** [comment]
@goodale If you will, try with these dependencies:
```
implementation 'com.sun.mail:jakarta.mail:2.0.1'
implementation 'com.sun.activation:jakarta.activation:2.0.1'
```

I had the same issue when I used these dependencies:
```
implementation 'jakarta.mail:jakarta.mail-api:2.1.1'
implementation 'jakarta.activation:jakarta.activation-api:2.1.1'
implementation 'org.eclipse.angus:jakarta.mail:1.1.0'
```

**Comment by goodale** [comment]
Thank you.  That appears to work for me as well.

As a side note, I found that another of our dependencies,  jaxws-ri :
4.0.0,   is pulling in jakarta.activation-api : 2.1.0 via jaxws-rt, which
also includes angus.
