### ISSUE TITLE
Allow different connection pool configuration per cluster? 

### ISSUE THREAD

**Issue by lopardo** [bbottema/simple-java-mail#437]
[The documentation](https://www.simplejavamail.org/configuration.html#section-clustering) states that:

> The Connection Pool defaults (core size, max size etc.) are set and fixed by the first Mailer instance in the cluster. Subsequent Mailer instances cannot change these global settings. If they provide different global defaults, a warning will be logged.

And yes, if I try to set different configuration for another Mailer instance I get this message:

```
o.s.internal.batchsupport.BatchSupport   : Global SMTP Connection pool is already configured with pool defaults from the first Mailer instance, ignoring relevant properties from OperationalConfigImpl(...)
```

However, it could be useful to have different settings per cluster. 

For example, I create two independent Mailer instances (programmatically) for different use cases, that could each use a different amount of connections (`connectionPoolMaxSize`) and timeouts (`connectionPoolExpireAfterMillis`).

Taking a look at the code, I found that [smtpConnectionPool.registerResourcePool()](https://github.com/bbottema/simple-java-mail/blob/7385c73945ebbe3ced03814c5151c196ef86a210/modules/batch-module/src/main/java/org/simplejavamail/internal/batchsupport/BatchSupport.java#L79) also accepts `expirationPolicy, corePoolSize, maxPoolSize`.

I tried cloning the project and modifying that line to pass those settings from `operationalConfig` and it seems to work as expected.

Maybe a setting could be added to honor those parameters, at least when creating a Mailer programmatically through a MailerBuilder?

Also, maybe the Javadoc for MailerBuilder methods like withConnectionPoolCoreSize/withConnectionPoolMaxSize could be improved to clarify that they will be ignored if configuring multiple mailers.

Thanks for the great work!

**Comment by bbottema** [comment]
> > However, it sounds like you have a different use case and perhaps you don't need a cluster, just two separate mailers not running in a cluster. The connection pool is used either way, one for each mailer in this scenario.
> 
> @bbottema can i configure mailers to be in different clusters (so they could have different connection pool settings)?

Absolutely. Just use a new cluster key and the first mailer to register it will be used to configure it. Subsequent mailers won't affect its configuration after that.
