### ISSUE TITLE
cli does not exit after successful execution

### ISSUE THREAD

**Issue by SCzfdf** [bbottema/simple-java-mail#439]
Here is the code
`./sjm send --email:startingBlank \
--email:from "Mr. Candy" "GitSendMail@163.com" \
--email:withSubject "About those tongue twisters" \
--email:to "Sweet Cheeks" "chen412235679@163.com" \
--email:withPlainText "I discovered a new flavor! (..)" \
--mailer:withSMTPServer smtp.163.com 25 GitSendMail@163.com xxxxxx \
--mailer:withTransportStrategy SMTP_TLS`

**Comment by bbottema** [comment]
That's probably because the batch-module is included. Try it without the batch-module JAR.

**Comment by SCzfdf** [comment]
> 这可能是因为包含[批处理模块](https://www.simplejavamail.org/modules.html)，它使连接池保持运行。在没有批处理模块 JAR 的情况下尝试它。

Thank you. 
I removed the batch-module-7.8.0.jar and it closed properly
