### ISSUE TITLE
Bug: `withEmailDefaults` and `withEmailOverrides` does not work with `CustomMailer`

### ISSUE THREAD

**Issue by morki** [bbottema/simple-java-mail#448]
It is simply ignored.

**Comment by bbottema** [comment]
Most defaults are set when creating the Email, but overrides happen during sending as well as the defaults for smime/dkim. Those will fail currently. 

However, I'm currently working on an overhaul regarding defaults and overrides. And this will be addressed.

**Comment by bbottema** [comment]
Btw, as a workaround you can disable the completeness validation using `mailerBuilder.disablingAllClientValidation(true)`.

I gotta ask though, why is From not relevant in your use case? For the purpose of sending emails, in whatever form, according to RFC 5322 From is mandatory.

**Comment by bbottema** [comment]
I see. In that case, does `disablingAllClientValidation` cover your use case appropriately?

**Comment by bbottema** [comment]
Ahh indeed, I just checked the code and the completeness check is always performed. I will disable this along with the other validations in case of `.disableAllClientValidation(true)`.

**Comment by bbottema** [comment]
I released 8.0.0, which now should always apply defaults and overrides in all scenarios.
