### ISSUE TITLE
EmailBuilder class isn't found in `simple-java-mail` v8.0 

### ISSUE THREAD

**Issue by messalas** [bbottema/simple-java-mail#454]
Great work guys! I am trying to use v8 and I have have downloaded  all jar dependencies. However, in the first line of the basic example :

    Email email = EmailBuilder.startingBlank()
        .from("lollypop", "lolly.pop@pretzelfun.com")
        .to("C. Cane", "candycane@candyshop.org")
        .cc("C. Bo <chocobo@candyshop.org>")
        .withSubject("hey")
        .withPlainText("We should meet up! ;)")
        .buildEmail();

I am getting that EmailBuilder wasn't found. I am trying to add these 3 imports

    import org.simplejavamail.converter.EmailConverter;
    import org.simplejavamail.email.EmailBuilder;
    import org.simplejavamail.mailer.MailerBuilder;

and they can't be resolved. Aren't they included in the `simple-java-mail-8.0.0.jar` file?

Previously, I was using v7.5 and I didn't have this error.

**Comment by bbottema** [comment]
I just checked the [published jar](https://repo1.maven.org/maven2/org/simplejavamail/simple-java-mail/8.0.0/), and it's fine. I think your workspace might need to be cleaned or something, like get rid of cache, trigger full rebuild or whatever.

![image](https://user-images.githubusercontent.com/2115718/226722317-918f85ef-da87-480f-84f7-a0ca1e550a55.png)
