### ISSUE TITLE
[Bug] Parsing lists from MSG

### ISSUE THREAD

**Issue by piu130** [bbottema/simple-java-mail#457]
When parsing lists in msgs, the resulting html (`.getHTMLText()`) contains the list tag as well as the bullet point in text. The browser renders a bullet point, because of the list tag and a second bullet point from the text.

Outlook:
![image](https://user-images.githubusercontent.com/12607663/231952431-fd855a36-6559-4da1-83f4-74c5b8bc5eaf.png)
Browser:
![image](https://user-images.githubusercontent.com/12607663/231952652-38e12072-e016-4b84-bc32-86248709de01.png)
HTML:
```html
<p class=MsoNormal>Stroke:<o:p></o:p></p>
<ul style='margin-top:0cm' type=disc>
  <li class=MsoListParagraph style='margin-left:0cm;mso-list:l1 level1 lfo1'>*	Stroke entry 1<o:p></o:p></li>
  <li class=MsoListParagraph style='margin-left:0cm;mso-list:l1 level1 lfo1'>*	Stroke entry 2<o:p></o:p></li>
</ul>
<p class=MsoNormal>Bullet:<o:p></o:p></p>
<ul style='margin-top:0cm' type=disc>
  <li class=MsoListParagraph style='margin-left:0cm;mso-list:l0 level1 lfo2'>*	Bullet entry 1<o:p></o:p></li>
  <li class=MsoListParagraph style='margin-left:0cm;mso-list:l0 level1 lfo2'>*	Bullet entry 2<o:p></o:p></li>
</ul>
<p class=MsoNormal>Number:<o:p></o:p></p>
<ol style='margin-top:0cm' start=1 type=1>
  <li class=MsoListParagraph style='margin-left:0cm;mso-list:l2 level1 lfo3'>1.	Number entry 1<o:p></o:p></li>
  <li class=MsoListParagraph style='margin-left:0cm;mso-list:l2 level1 lfo3'>2.	Number entry 2<o:p></o:p></li>
</ol>
```
We should remove the `*` and the `1.` (and tab?) from the html text.
Otherwise we can also fix this on our side by replacing `type=disc` with `type=none` or removing the first (two) char(s) in the list.

What do you think?

**Comment by bbottema** [comment]
This is an problem with the Outlook message parser and the issue lies in the conversion from RTF to HTML and, unfortunately, this has proven to be difficult to improve.

You can move this issue over to https://github.com/bbottema/outlook-message-parser, but I myself won't be able to fix this.

**Comment by piu130** [comment]
Thanks for the fast reply @bbottema . I moved the issue https://github.com/bbottema/outlook-message-parser/issues/64 .
