### ISSUE TITLE
Possible in an Android Project?

### ISSUE THREAD

**Issue by XanaRaquel** [bbottema/simple-java-mail#46]
**Hi,
I'm trying to use this in my Android project but so far no luck. I was previously using "com.sun.mail:android-*:1.5.5" which worked but not so well with Gmail's SMTP and that's why I'm trying Simple Java Mail now.
During build I get these warnings:**
`warning: Ignoring InnerClasses attribute for an anonymous inner class (javax.activation.DataHandler$1) that doesn't come with an associated EnclosingMethod attribute. This class was probably produced by a compiler that did not target the modern .class file format. The recommended solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring this warning is that reflective operations on this class will incorrectly indicate that it is *not* an inner class.

warning: Ignoring InnerClasses attribute for an anonymous inner class (javax.activation.SecuritySupport$1) that doesn't come with an associated EnclosingMethod attribute. This class was probably produced by a compiler that did not target the modern .class file format. The recommended solution is to recompile the class from source, using an up-to-date compiler and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly indicate that it is *not* an inner class.

warning: Ignoring InnerClasses attribute for an anonymous inner class (javax.activation.SecuritySupport$2) that doesn't come with an associated EnclosingMethod attribute. This class was probably produced by a compiler that did not target the modern .class file format. The recommended solution is to recompile the class from source, using an up-to-date compiler and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly indicate that it is *not* an inner class.

warning: Ignoring InnerClasses attribute for an anonymous inner class (javax.activation.SecuritySupport$3) that doesn't come with an associated EnclosingMethod attribute. This class was probably produced by a compiler that did not target the modern .class file format. The recommended solution is to recompile the class from source, using an up-to-date compiler and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly indicate that it is *not* an inner class.

warning: Ignoring InnerClasses attribute for an anonymous inner class (javax.activation.SecuritySupport$4) that doesn't come with an associated EnclosingMethod attribute. This class was probably produced by a compiler that did not target the modern .class file format. The recommended solution is to recompile the class from source, using an up-to-date compiler and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly indicate that it is *not* an inner class.

warning: Ignoring InnerClasses attribute for an anonymous inner class (javax.activation.SecuritySupport$5) that doesn't come with an associated EnclosingMethod attribute. This class was probably produced by a compiler that did not target the modern .class file format. The recommended solution is to recompile the class from source, using an up-to-date compiler and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly indicate that it is *not* an inner class.
`

The app runs fine until I get to the part of sending the actual mail:
`java.lang.NoClassDefFoundError: javax.activation.DataHandler
                                                                        at javax.mail.internet.MimeBodyPart.setContent(MimeBodyPart.java:789)
                                                                        at org.codemonkey.simplejavamail.Mailer$MimeEmailMessageWrapper.<init>(Mailer.java:549)
                                                                        at org.codemonkey.simplejavamail.Mailer.produceMimeMessage(Mailer.java:335)
                                                                        at org.codemonkey.simplejavamail.Mailer.sendMail(Mailer.java:239)
                                                                        at xx.xx.xx.MailJob$1.doInBackground(MailJob.java:142)`

**and in that line I have** `new Mailer(host, port, user, pass, TransportStrategy.SMTP_TLS).sendMail(email);`

**Any input would be helpful.**

**Comment by bbottema** [comment]
This is not a Simple Java Mail issue, but an issue with Android. More specifically, you are trying to use a class file against Java 6 or 7 in a JVM that runs Android's runtime Dalvik.

I have no idea if that can work out of the box.

It seems the best way is to checkout the Simple Java Mail source code, make it work using an [Android compatible Javax Mail distribution](https://java.net/projects/javamail/pages/Android) and compile that for Dalvik.

**Comment by bbottema** [comment]
I have no idea if it can possibly related, but the latest release has a java6 version as well. Might be worth a try.

```xml
<dependency>
    <groupId>org.simplejavamail</groupId>
    <artifactId>simple-java-mail</artifactId>
    <version>4.2.0-java6-release</version>
</dependency>
```

**Comment by reversecoder** [comment]
Getting same error for java6 release. No luck.
