### ISSUE TITLE
java.lang.ClassCastException: org.simplejavamail.email.internal.EmailStartingBuilderImpl cannot be cast to org.simplejavamail.api.email.EmailPopulatingBuilder

### ISSUE THREAD

**Issue by ac-tech-madcoz** [bbottema/simple-java-mail#464]
When using the standalone cli in windows in Java 8 environment using the command "sjm send", the following error pops up:

> Exception in thread "main" java.lang.ClassCastException: org.simplejavamail.email.internal.EmailStartingBuilderImpl cannot be cast to org.simplejavamail.api.email.EmailPopulatingBuilder
>         at org.simplejavamail.internal.clisupport.CliCommandLineConsumerResultHandler.processCliSend(CliCommandLineConsumerResultHandler.java:53)
>         at org.simplejavamail.internal.clisupport.CliCommandLineConsumerResultHandler.processCliResult(CliCommandLineConsumerResultHandler.java:45)
>         at org.simplejavamail.internal.clisupport.CliSupport.runCLI(CliSupport.java:68)
>         at org.simplejavamail.cli.SimpleJavaMail.main(SimpleJavaMail.java:31)

**Comment by bbottema** [comment]
Can you share the command you're trying to execute, please?
