### ISSUE TITLE
Maintenance: Let Mailer implement AutoCloseable, so it shuts down the connection pool automatically when disposed of by Spring

### ISSUE THREAD

**Issue by lburja** [bbottema/simple-java-mail#466]
When using the connection pool (batch-module enabled), the documentation suggests that the application should call  mailer.shutdownConnectionPool() to allow the JVM to shut down.

With Spring Boot (spring-module), beans that implement AutoClosable are normally automatically handled and their close() method is called by the Spring framework upon application shutdown (see Spring [documentation](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/factory/DisposableBean.html)).

Therefore, I would expect Mailer to implement AutoClosable, and shut down the connection pool in the close() method, so that shutdown can be automatically handled by Spring Boot (also try-with-resources)

**Comment by bbottema** [comment]
try-with resource would not be possible in combination with async emails. The connection pool might shut down, before the email was sent. However, for closing applications from Spring perspective, this is an interesting thought.

**Comment by bbottema** [comment]
Without too much testing this, I've added and released this in 8.1.3. Give it a spin!

**Comment by lburja** [comment]
Awesome! Seems to work as expected. Thank you very much!
