### ISSUE TITLE
Dependency problems around jakarta.mail

### ISSUE THREAD

**Issue by zhenchuan9r** [bbottema/simple-java-mail#468]
If I only declare dependency on simple-java-mail, the program does not run as expect.
```
<dependency>
    <groupId>org.simplejavamail</groupId>
    <artifactId>simple-java-mail</artifactId>
    <version>8.1.3</version>
</dependency>
```
It will throw ClassNotFoundExceptions like:
```
java.lang.ClassNotFoundException: jakarta.mail.MessagingException
```
```
java.lang.ClassNotFoundException: jakarta.activation.FileTypeMap
```
It can be resolved by adding additional dependencies but it should not be the right behaviour.

Suggestions for the [simple-java-mail] staff:
1. Add those dependencies on simple-java-mail-8.1.3.pom
2. Use flatten plugin to simplify the pom before uploading artifacts

**Comment by bbottema** [comment]
This can't be correct. I'll have a look later, but I'm highly skeptical. Are you sure your dependencies are not server-managed? Or that the transitive dependencies are not excluded somewhere?

**Comment by zhenchuan9r** [comment]
I saw a really simlar issue here [432](https://github.com/bbottema/simple-java-mail/issues/432).
Additionally, I did not define any exclusion around jakata email.
However, it is possible that this issue is related to JDK versions.
I'm using JDK 11.

**Comment by bbottema** [comment]
I just started an new empty Maven project, JDK 11, with just the simple java mail dependency. Here's the result of the dependency tree:

> [INFO] Scanning for projects...
> [INFO] 
> [INFO] -----------------< org.example:simple-java-mail-test >------------------
> [INFO] Building simple-java-mail-test 1.0-SNAPSHOT
> [INFO] --------------------------------[ jar ]---------------------------------
> [INFO] 
> [INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ simple-java-mail-test ---
> [INFO] org.example:simple-java-mail-test:jar:1.0-SNAPSHOT
> [INFO] \- org.simplejavamail:simple-java-mail:jar:8.1.3:compile
> [INFO]    +- org.simplejavamail:core-module:jar:8.1.3:compile
> [INFO]    |  +- com.sun.mail:jakarta.mail:jar:2.0.1:compile
> [INFO]    |  +- com.sun.activation:jakarta.activation:jar:2.0.1:compile
> [INFO]    |  \- com.sanctionco.jmail:jmail:jar:1.4.1:compile
> [INFO]    +- com.github.bbottema:jetbrains-runtime-annotations:jar:1.0.1:compile
> [INFO]    +- com.pivovarit:throwing-function:jar:1.5.1:compile
> [INFO]    \- org.slf4j:slf4j-api:jar:1.7.32:compile
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  0.543 s
> [INFO] Finished at: 2023-07-25T12:34:12+02:00
> [INFO] ------------------------------------------------------------------------

Looks fine to me. This is so basic, I cannot conclude anything other than a user error, somehow. Your dependencies are not loaded properly in your project for some reason.

**Comment by Osiris-Team** [comment]
I have the same problem, using it in a Spring Boot Vaadin application. Needed to add
```xml
        <dependency>
            <groupId>jakarta.mail</groupId>
            <artifactId>jakarta.mail-api</artifactId>
        </dependency>
```
to my dependencies.
This should be already included in simple-java-mail?

**Comment by bbottema** [comment]
Simple Java Mail works without the -api package, as it uses an implementation package directly (which includes all the same types).

```xml
<dependency>
    <groupId>com.sun.mail</groupId>
    <artifactId>jakarta.mail</artifactId>
    <version>2.0.1</version>
</dependency>
```

This library is used like this by thousands of people and I've recently tested this to double check it in a new clean project. If the -api dependency is needed, I can only guess it's because of Spring somehow.
