### ISSUE TITLE
Erros send mail with Subject in multiple lines

### ISSUE THREAD

**Issue by halimpuckjava** [bbottema/simple-java-mail#470]
hi

i try to send email with subject like this

```
val subject = """
                               line 1
                               line 2
                               line 3
                       """
```

error to send mail !!!!

**Comment by bbottema** [comment]
Which version, what's the error, stack trace, etc.

**Comment by halimpuckjava** [comment]
hi

that exception appear when send subject (multiple lines)

```
org.simplejavamail.mailer.MailSuspiciousCRLFValueException: Suspected of injection attack, field: email.subject with suspicious value
```

**Comment by bbottema** [comment]
Yes, this is intended behaviour. However, if you think you know what you're doing, then you can turn this behaviour off:
```java
currentMailerBuilder
    .disablingAllClientValidation(true)
```
Also see the [footnote under email address validation](https://www.simplejavamail.org/features.html#section-email-validation).
