### ISSUE TITLE
Convert EML to MSG format

### ISSUE THREAD

**Issue by zmotiwala** [bbottema/simple-java-mail#471]
Is there a way to convert the eml file back to a msg file? The api allows to read msg files but I don't see a way to see it. I did not see this listed anywhere in enhancements either.

**Comment by bbottema** [comment]
This is not possible. The Outlook msg format is a closed proprietary format and unless the actual SDK is used (.NET) as far as I know any attempt to do this in Java failed miserably. Even just reading messages back is limited.
