### ISSUE TITLE
Support sending e-mails directly to recipient SMTP server (MX)

### ISSUE THREAD

**Issue by morki** [bbottema/simple-java-mail#472]
It would be awesome if SimpleJavaMail could create `Mailer` instance which determinates hosts from recipient addresses,
check MX records for those and create temporal connection to those.

It would be awesome for demo and testing purposes of software to not have to configure SMTP relay. 
I know all the consequences and do not mean it for real production use, but for customer testing it would be really simplifying. 

I tried that manually and it seems at least Gmail does not mark those e-mails as spam, just displays warning icon next to them.

Another alternative is using local `sendmail` or something, but it is not as portable as MX solution.

**Comment by bbottema** [comment]
1. What would be the purpose of those connections? Address validation based on valid hosts?
1. Are you aware of other mailing libraries (not necessarily Java related) that do this?
1. Do you know of any well known (Java) libraries that facilitate embedded SMTP relay?

I might be interested in adding a new module for this, but right now it doesn't have much priority, especially if I have first have to dig into use cases and available libraries.

**Comment by morki** [comment]
Hi @bbottema, thank you for your reply, to participate with my use case:

Our clients can download our software as single binary produced with GraalVM native image tool.
We use only embedded SQLite database, so there is no need to install anything else and configure anything.
They can just run the native binary and server will start to listen on some port to start testing our software.

The only problem is that now they must configure some SMTP relay to test the system, because of some functionalities are heavily dependent on email sending. This is problematic for just evaluation purposes, so we implemented `CustomMailer` that is saving those emails to database and created some simple webmail client. But is is not intuitive and does not work good enough and make the system feel wierd.

From this point of view, it would be better to just use builtin SMTP relay as you name it, to send those emails directly.
We can document that those emails can end in spam or can be not delivered at all, but as I tested, it is not the case for Gmail and Outlook, at least when sender is `root@localhost`, which is sufficient for our evaluation use case.

When client is happy with our system, he can configure real SMTP relay to make emails delivery robust and reliable. 
It will be even required when using licenced version.

Does it make sense? If you see other solution to our use case, I would be happy to discuss.

For your questions, I don't know any other Java library doing this, if I would find one, I would use SimpleJavaMail to construct the email and `CustomMailer` to make this type of delivery.

**Comment by bbottema** [comment]
I don't think this can actually work. You need a dedicated SMTP server, because popular clients such as gMail check the domain the message is sent from, to match it to the from-address. These checks are called [SPF looks up](https://dmarcian.com/what-is-spf/).

I had a look at a popular Java based embedded SMTP server, [Aspirin](https://github.com/masukomi/aspirin) and they state the same (see [limitations](https://github.com/masukomi/aspirin#limitations)).

**Comment by morki** [comment]
I understand this, but as I stated, I works with e.g. Gmail, only marking this email as SPAM, but it is delivered.

But maybe we are solving the problem from wrong side, so feel free to close this issue. We will try to investigate how to make this "evaluation" flow simpler in different way. Any ideas are welcome :)

Thank you very much for your time and awesome library!

**Comment by bbottema** [comment]
Still, I find the ability to mail without SMTP server intriguing. When I have some time, I'll see how it works with Aspirin, for now I'm closing this issue.
