### ISSUE TITLE
[Bug] .msg inside .msg becomes .eml

### ISSUE THREAD

**Issue by piu130** [bbottema/simple-java-mail#474]
When using `EmailConverter.outlookMsgToEmail(msg)` with a .msg containing a .msg, the inner .msg becomes a .eml in the attachment list. The Attachment name changes to <original name>.eml the contnentType to message/rfc822.

[Here an example](https://github.com/bbottema/simple-java-mail/files/12813146/sample.zip).

**Comment by bbottema** [comment]
That is by design, the nested message is a standard MimeMessage and can be opened by any mail client or read back by Simple Java Mail. This is so you don't have to manually traverse a nested attachments when reading Outlook messages.

**Comment by piu130** [comment]
Thanks for the fast response :) If I understand it correctly, outlook converts the .msg to a MimeMessage for the attachment to send it and converts it back to .msg when I extract it?
And simple-java-mail does not do this conversion and directly reads the MimeMessage as .eml?

**Comment by bbottema** [comment]
No, The attachment is an Outlook .msg When you read and convert the parent Outlook .msg with Simple Java Mail, it will recursively also read and convert nested Outlook .msg attachments.

**Comment by piu130** [comment]
Ok. I think I understand it now. Most mail clients only supports .eml and this is why this library converts the .msg to .eml?
For us, it's kind of an information loss. But it's not critical, since we still have the original mail with the original attachments :)
Thank you very much for the great support!

**Comment by bbottema** [comment]
I had a look for you if I could preserve the original attachment for your use case. However, in [outlook-message-parser](https://github.com/bbottema/outlook-message-parser), this seems impossible, as the underlying Apache POI library already performed some conversion on a lower level, before I get access to the attachment. At this point, the .msg file source is already replaced by a Java data structure (which I take and convert into a MimeMessage structure and save as .eml file).

So unfortunately, this is not a viable path.
