### ISSUE TITLE
Enhancement: Support Exchange proprietary addresses (X.500 DAP)

### ISSUE THREAD

**Issue by dwlabcube** [bbottema/simple-java-mail#477]
When the recipient is a "strange" address in a .msg file the MiscUtil will throw.
java.lang.IllegalArgumentException: emailAddressList is required
	at org.simplejavamail.internal.util.Preconditions.verifyNonnullOrEmpty(Preconditions.java:49) ~[core-module-8.3.1.jar:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 

Please see the attachment in order to get an idea of how that address looks like.
Unfortunately i can not share the email with you since it holds sensitive data and I do not know how to reproduce it easily.

![emailListTo](https://github.com/bbottema/simple-java-mail/assets/46682038/f43f79aa-a85f-4b40-a42e-e9c11b3ae68e)

It seems to have it's root in handleNameAddressProperty in OutlookRecipient class
![AddressParser](https://github.com/bbottema/simple-java-mail/assets/46682038/afa9f68b-8bd8-4f20-b6b5-9b100d54f499)

Suggestion:
erase the null check in MiscUtil and just log a warning instead of throwing an exception.
Or add a check in handleNameAddressProperty that does not check only on @ but also has an OR with startsWith("/o")

**Comment by dwlabcube** [comment]
I created a Pull request in the outlookmessageparser repo:
dwlabcube:patch-X500-Outlook-Recipient

**Comment by bbottema** [comment]
Is that even a value Outlook/Exchange can resolve?

**Comment by dwlabcube** [comment]
Yes outlook was able to resolve it properly. It seems to be something with caching and resolving X500 Address or something like that. I have no clue about all that, but it seems to be valid stuff though.

if you google for "/o=exchangelabs/ou=exchange administrative group" you'll find some information. but honestly i didn't get it what exactly is going on.

if you don't mind just accepting empty email-address in the miscutil i am very fine with it as well.
maybe there is even a cleaner solution?
