### ISSUE TITLE
All the Emails are sending after restarting the tomcat container.

### ISSUE THREAD

**Issue by Elavarasansk** [bbottema/simple-java-mail#479]
Hi ,

i was using the simple java mail to send email for my application.The below are my application details

 Simple java mail version :  5.0.3
Spring version : 5.3.23
Java: 11
Tomcat : 9.0.54
Docker CE Engine : 18.09.0
Docker Compose : 1.23.2  or later
OS : Linux/Redhat

**Code used**
_// Email buileder

Mailer mailer = MailerBuilder
          .withSMTPServer("smtp.host.com", 587, "user@host.com", "password")
          .withTransportStrategy(TransportStrategy.SMTP_TLS)
          .withSessionTimeout(10 * 1000)
          .withProperty("mail.smtp.ssl.checkserveridentity","false")
          .buildMailer();

mailer.sendMail(email);_

**Error Scenario** 

After deployed the docker container , The application running was triggering mails and i was receiving the emails also after few minutes i'm not receiving any emails. After restarting the tomcat docker container the old emails and everything i was receiving.
 
Please look into this ASAP

Thanks.
Elavarasan S.

**Comment by bbottema** [comment]
Yeah this has nothing to do with Simple Java Mail, which doesn't maintain any state between application restarts. Simple Java Mail will only ever send anything if instructed to do so by the application using it.
