### ISSUE TITLE
Bug: Multiple attachments with same name get the same Content-ID, causing them to refer to the same file content

### ISSUE THREAD

**Issue by rkurman** [bbottema/simple-java-mail#480]
When I'm trying to send an email where multiple attachments with the same name, the receiver thinks that it is always the same attachment and shows the same content for all attached files.
I have tested this with versions 6.5.2 and 8.3.1.

In my opinion, the problem is the assignment of the BodyPart ID in `org.simplejavamail.converter.internal.mimemessage.MimeMessageHelper.getBodyPartFromDatasource(AttachmentResource, String)` (line 288) where the Content-ID header of the part is based solely on the filename of the attachment. I suggest to always add a UUID at the end to ensure uniqueness.

**Comment by bbottema** [comment]
Hmm, interesting. I'm not a fan of using UUID, that makes the filenames unwieldy, but a sequence number could work... I'll have a look.

**Comment by rkurman** [comment]
Isn't the filename determined by the filename parameter of the Content-Type header.  The Content-ID should not have any influence on the filename.

**Comment by bbottema** [comment]
This should now be fixed in 8.3.2. Can you please verify, if you get a chance?

**Comment by rkurman** [comment]
I can confirm that the problem is resolved now (I checked with version 8.6.2).
Thank you very much, sir.
