### ISSUE TITLE
Update to Angus Mail

### ISSUE THREAD

**Issue by PascalSchumacher** [bbottema/simple-java-mail#489]
The Jakarata Mail implementation was renamed to Angus Mail. With Angus Mail 2 the package names where changed from `com.sun.mail.*` to `org.eclipse.angus.mail.*`.

It would be nice if `simple-java-mail` was updated to use the latest Angus Mail release.

By the way: Thank you very much for providing `simple-java-mail`!

**Comment by vladimirfx** [comment]
I can provide a PR if needed.

**Comment by bbottema** [comment]
It's not that easy. You'd have to upgrade all upstream projects as well, like the smtp connection pool library. I'll deal with it.

**Comment by bbottema** [comment]
It seems Jakarta Mail 2.1.2 is not backwards compatible with 2.0.1. The class SMTPMessage is missing (or renamed, still looking into it).

**Comment by vladimirfx** [comment]
OK. Now it is so painful to use SJM with the actual Spring Boot version. Thaks

**Comment by bbottema** [comment]
Upgrade released in 8.6.0.

**Comment by PascalSchumacher** [comment]
Thank you very much!

**Comment by bbottema** [comment]
Good catch. I'll get on it.

**Comment by bbottema** [comment]
It's also in java-reflection and as a transitive of jakarta.xml.bind-api

**Comment by bbottema** [comment]
I got java-reflection sorted out, but jakarta.xml.bind-api 4.x.x -which internally updates to the Angus activation package- requires Java 11. Simple Java Mail is still on Java 8, since [in 2023, still a third of all Java usage is Java 8 LTS](https://newrelic.com/resources/report/2023-state-of-the-java-ecosystem).

**Comment by bbottema** [comment]
Everything sorted out. Update released in 8.6.1.
