### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by roy20021** [bbottema/simple-java-mail#490]
Hello,

I am trying to compile the project (_mvn clean install_) but it fails:
`[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.5:report-aggregate (report-aggregate) on project jacoco-aggregator-module: An error has occurred in JaCoCo Aggregate report generation.: Error while creating report: Error while analyzing C:\Users\AndreaEsposito\repositories\simple-java-mail\modules\authenticated-socks-module\target\classes\org\simplejavamail\internal\authenticatedsockssupport\AuthenticatedSocksHelper.class. Cannot process instrumented class org/simplejavamail/internal/authenticatedsockssupport/AuthenticatedSocksHelper. Please supply original non-instrumented classes. -> [Help 1]`

` mvn --version
Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)
Maven home: C:\Users\AndreaEsposito\opt\apache-maven-3.9.1
Java version: 1.8.0_382, vendor: Temurin, runtime: C:\Program Files\Eclipse Adoptium\jdk-8.0.382.5-hotspot\jre
Default locale: it_IT, platform encoding: Cp1252
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows`

`git status
HEAD detached at 8.6.1`

I haven't found any particular instructions on the repo. Can I have support, please?

**Comment by bbottema** [comment]
What Java and Maven version are you using? OS?

**Comment by roy20021** [comment]
@bbottema it is written in the comment above.

Java version: 1.8.0_382,
Apache Maven 3.9.1,
windows 11

Looking forward for your support

**Comment by bbottema** [comment]
Strange, I'm not able to reproduce the issue. However, you can just skip jacoco altogether and just provide `-Djacoco.skip=true` as command line option.
