### ISSUE TITLE
[bug] Attachment body parts should separately parse Content-Disposition and ContentID, possible resulting in an downloadable attachment that is also embedded

### ISSUE THREAD

**Issue by roy20021** [bbottema/simple-java-mail#491]
Hello,

I am trying to use _simple-java-mail_ for parsing and showing mails, however I am finding out an issue regards parts that should be treated as CID instead of Attachments.

More precisely, the library is not handling at all the different multipart subtype (mainly: mixed, alternative and related) and relies on the content-disposition header to determine if the part should be a CID or an attachment.
As per my trials, at least a message sent via gmail, the eml might be composed of multipart/related (https://www.ietf.org/rfc/rfc2387.txt ) and the CID parts declared with disposition 'attachment'.
As per https://www.ietf.org/rfc/rfc2183.txt (2.1, 2.2 paragraph) the disposition meaning is about automatic or manual actions from the user.

Example: 
[Example.zip](https://github.com/bbottema/simple-java-mail/files/14001352/Example.zip)

There is an image "doclife.jpg" that should appear in the cidMap (but it is not).

I propose to handle that more loosely: https://github.com/roy20021/simple-java-mail/commit/eed9bf99d20f93ef6b9bdb705f52fc292811ebf9

I haven't tested yet the change since https://github.com/bbottema/simple-java-mail/issues/490 is a blocker.
Please provide a formatter (I am using eclipse) I should use if necessary.

**Comment by bbottema** [comment]
Hello roy, thank you for contributing. I haven't had much time to dive into this, but it's difficult to see what you changed exactly, with all the formatting changes. Would it be possible to split out the formatting from the actual change?

**Comment by roy20021** [comment]
Can you apply a specific formatter to all the code and reference it into the repo? It will be extremely easier to contribute.
As an example: https://github.com/google/google-java-format

I describe below my changes:

1. made MimeDataSource implements DataSource 
2. at MimeMessageParser changed the parseMimePartTree method in order to assume every attachment as a CID
3. at MimeMessageParser renamed _moveInvalidEmbeddedResourcesToAttachments_ to _moveNonEmbeddedResourcesToAttachments_ changing its logic in order to iterate over all cids and move to attachment if not into the html content

**Comment by bbottema** [comment]
Thanks for the suggestion, but I don't want to format my whole code base right now.

I did a little bit of research, but it seems there is no clear behaviour for this. Sure, resources should be used as embedded based on CID. But it is not said these same resources should not _also_ be downloadable attachments. Meaning, a resource can both be an embedded image and a downloadable file.

I never realized this, but it seems this is the reason why I sometimes get emails in gmail where many of the embedded images are also listed as downloadable files. It seems gmail does this commonly, but this is not universal behaviour and the RFC's don't explicitly define this use case.

What are your thoughts on this?

**Comment by bbottema** [comment]
Did you have some time to think about this, @roy20021?

**Comment by bbottema** [comment]
Somewhat related to #179

**Comment by bbottema** [comment]
I'm going to treat the handling of Content-Disposition separate from any embedding/CID references. This means I'm going to assume the resource should both be embedded and and attachment which in the case of Simple Java Mail means, the resources occurs in two list at the same time (embeddedImages and attachments).

**Comment by roy20021** [comment]
Hello @bbottema , 

I think we can treat as attachment according to the disposition in order to keep the back-compatibility. Then, add to the CID map all the parts that appear to be in the html body.

What do you think? Would that suits you?

If yes, I can make the PR.

**Comment by bbottema** [comment]
I'm already having a crack at it 👍

**Comment by bbottema** [comment]
I'll release the fix tonight (my time)

**Comment by bbottema** [comment]
Released in 8.6.3. If you could verify it works as you expect, that would be very helpful.

**Comment by roy20021** [comment]
@bbottema I confirm it works as expected. Thank you!
