### ISSUE TITLE
Order of attachments is lost when converting a MimeMessage to an Email

### ISSUE THREAD

**Issue by timestudybuddy** [bbottema/simple-java-mail#497]
I'm writing a script that monitors an IMAP box, and clones bounce messages, adjusting the recipients so that they reach our customers' corresponding Administrators.   I'm using simple-java-mail to convert an IMAPMessage/MimeMessage into an Email, which we can then feed into our existing mail subsystem.  I've noticed that the order of attachments gets lost during this conversion.  Bounce messages follow a specific standard, and the order of these attachments matters.  

I traced it down to  org.simplejavamail.converter.internal.mimemessage.ParsedMimeMessageComponents.attachmentList being a SortedSet.  This effectively orders the attachments by their name.  Is there a reason this isn't simply an ArrayList?

**Comment by bbottema** [comment]
Hmm, I'm not sure, but the decision was made in the early days of this project, presumably due to testing challenges where the attachments were out of order otherwise. However, I replaced it _LinkedHashSet_ and everything tested fine still. Would that would for you?

**Comment by timestudybuddy** [comment]
Yes, I believe so.Brian GardnerOn Mar 14, 2024, at 3:10 AM, Benny Bottema ***@***.***> wrote:﻿
Hmm, I'm not sure, but the decision was made in the early days of this project, presumably due to testing challenges where the attachments were out of order otherwise. However, I replaced it LinkedHashSet and everything tested fine still. Would that would for you?

**Comment by bbottema** [comment]
Released in [8.7.1](https://github.com/bbottema/simple-java-mail/releases/tag/8.7.1), can you please verify?

**Comment by timestudybuddy** [comment]
I confirmed this is working as expected now!  Thanks you so much!
