### ISSUE TITLE
How to esclude embedded image in email

### ISSUE THREAD

**Issue by francescodiperna** [bbottema/simple-java-mail#525]
Hi, I need help to understand how to exclude embedded images in a message read from inputStream of an EML file.

Here the code used:

```
Email email = EmailConverter.emlToEmail(inputStream);
				
		List<AttachmentResource> attachments = email.getAttachments();
		for (AttachmentResource attachment : attachments) {
........
```

Thanks

Francesco

**Comment by bbottema** [comment]
I'm not sure what your code is about, but the embedded images are in `email.getEmbeddedImages();`
