### ISSUE TITLE
When reading .msg files the RTF converted to HTML is garbled in some cases where the appropriate charset is not detected properly

### ISSUE THREAD

**Issue by huangyz0801** [bbottema/simple-java-mail#526]
Using simple Java mail to read the exported msg file from Outlook, but the HTML data in it is garbled in Chinese. The version of simple Java mail used is 6.6.1.
![Uploading 1.png…]()

**Comment by bbottema** [comment]
Thank you for contacting, but there's not much for me to go on, here (your image won't load, either). Please also try with the latest version, since 6.6.1 is rather old and since then there have been developments in the underlying Outlook support. If that still fails for you, you could really help me help you by providing a problematic .msg that demonstrates this.

**Comment by huangyz0801** [comment]
There are error messages when using the lastest version.

Exception in thread "main" java.lang.NoClassDefFoundError: jakarta/mail/MessagingException
	at com.eagle.core.utils.DateUtils.main(DateUtils.java:209)
Caused by: java.lang.ClassNotFoundException: jakarta.mail.MessagingException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 1 more

**Comment by huangyz0801** [comment]
I am using the jdk11 version, and the springboot version is 2.7.18

**Comment by huangyz0801** [comment]
[msg.zip](https://github.com/bbottema/simple-java-mail/files/15372473/msg.zip)


The msg.zip contains two msg files. After the program is parsed, garbled.msg is garbled in Chinese, while un_garbled.msg is not garbled.

**Comment by huangyz0801** [comment]
I upgraded to 8.10.1, but the Chinese characters are still garbled. The JDK version is 11. The springboot version is 2.7.18.

**Comment by huangyz0801** [comment]
[msg.zip](https://github.com/bbottema/simple-java-mail/files/15431194/msg.zip)

Hi Bottema,
Thanks for replying me, above is the msg file. And I have upgraded to the new version. When I send the msg to users to test, the Chinese text showed as below, still garbled. Could u help to give some suggestion? Great thanks.
![image](https://github.com/bbottema/simple-java-mail/assets/40018251/9ee6644d-b168-47d6-846a-d1c3dacb98b9)

**Comment by bbottema** [comment]
Ok, I've looked into it and determined this is a bug in [rtf-to-html](https://github.com/bbottema/rtf-to-html), which is used in [outlook-message-parser](https://github.com/bbottema/outlook-message-parser), which is used by Simple Java Mail.

Please refer to https://github.com/bbottema/rtf-to-html/issues/13.

**Comment by bbottema** [comment]
Fix released in 8.11.0.
