### ISSUE TITLE
how to impl sent by xxx ?

### ISSUE THREAD

**Issue by ensean** [bbottema/simple-java-mail#53]
Suppose I have two mail accounts, a@mailservera.com, b@mailserverb.com, 

how to implement the sent by feature ?

**Comment by bbottema** [comment]
Hi @ensean, this is very easy. Please refer to the [basic usage examples](http://www.simplejavamail.org/#/features) on [simplejavamail.org](simplejavamail.org):

Normal approach:
```
Email email = new Email();
(...)
email.addRecipient("a" /* or null */, "a@mailservera.com", RecipientType.TO);
email.addRecipient("b" /* or null */, "b@mailserverb.com", RecipientType.TO /* or CC, BCC */);
```
Builder approach:
```
Email email = new EmailBuilder()
    .to("a" /* or null */, "a@mailservera.com")
    .to("b" /* or null */, "b@mailserverb.com")
    // or .cc(...), .bcc(...)
    (...)
    .build();
```

**Comment by ensean** [comment]
Sorry for the mis leading, I trying to impl the following _sent by_ feature...
![sendby](http://uat.appcn100.com/fileserver/f?f=/thumb/sentby.png)

**Comment by bbottema** [comment]
Simple: [Email.setReplyToAddress()](http://static.javadoc.io/org.simplejavamail/simple-java-mail/4.1.1/org/simplejavamail/email/Email.html#setReplyToAddress-java.lang.String-java.lang.String-) and [EmailBuilder.replyTo()](http://static.javadoc.io/org.simplejavamail/simple-java-mail/4.1.1/org/simplejavamail/email/EmailBuilder.html#replyTo-java.lang.String-java.lang.String-).

```java
email.setFromAddress("a" /* or null */, "a@mailservera.com")
email.setReplyToAddress("b" /* or null */, "b@mailservera.com")
```

```java
Email email = new EmailBuilder()
    .from("a" /* or null */, "a@mailservera.com")
    .replyTo("b" /* or null */, "b@mailserverb.com")
    (...)
    .build();
```
