### ISSUE TITLE
Is there a plan to add pop3 wrapper to this project ?

### ISSUE THREAD

**Issue by ensean** [bbottema/simple-java-mail#54]
As an smtp wrapper, this util is amazing. 
It will be great if  wrapper for pop3 be added too....

**Comment by ricardogobbo** [comment]
I agree with you! This feature would be great!

**Comment by bbottema** [comment]
Haha, I would love it, but POP3 is an entirely different beast from SMTP. I'm not even sure what problem a potential Simple Java Pop3Mail project would solve.

With SMTP it is very clear: there are so many specs for defining an email and so many clients that needs to understand your email, that Simple Java Mail simplifies the process of creating a fool-proof email. What problem does POP3 have?

**Comment by ensean** [comment]
To be honest, refering to the javamail api by Oracle, I can now sync the whole mails from my INBOX(such as gmail) to local, stored in a database, but I have encountered the following issues too:

1.  How to identified new files to be synced to local ( may be messageId & search func by pop3?)

2. Once the mail is synced to local, is it possible to impl the REPLY/FOWARD just as the users do on the web client provided by the mail vendor(gmail for example)

Any suggestion will be appreciated.
