### ISSUE TITLE
Simple java mail (Jakarta) and Apache James (javax)?

### ISSUE THREAD

**Issue by bbottema** [bbottema/simple-java-mail#542]
> Currently for a project we are working with mails using Apache James Server and your library Simple Java Mail, we are using it to work wit .eml but due to it been written using jakarta and Apache James Server being in javax, they are in conflict.  I have not been able to find a way to solve this conflict and i wanted to ask you if you have a version on Simple Java Mail that uses javax or a different method to work with .eml.
> 
> Thank you very much, we have seen that Simple Java Mail is a great and very complete work.

I'm not sure how they are in conflict. Apache James is a standalone server, yes? At any rate, javax has been legacy EOL for many years now (development stopped in 2018), having been superseded by Jakarta (and now also Angus as split up implementation). The last Simple Java Mail version that worked with javax should probably be [6.7.5](https://github.com/bbottema/simple-java-mail/releases/tag/6.7.5), almost 50 versions releases back.

**Comment by miguelmunoz2019** [comment]
They enter in conlfict when calling mailets since the mailets require javax
