### ISSUE TITLE
EmailConverter.emlToEmail exp

### ISSUE THREAD

**Issue by 8bm8** [bbottema/simple-java-mail#549]
when i do EmailConverter.emlToEmail getin this exp.

java.lang.ClassCastException: class com.sun.mail.handlers.multipart_mixed cannot be cast to class jakarta.activation.DataContentHandler

**Comment by bbottema** [comment]
It looks like you are mixing javax libraries with Jakarta/Angus libraries. Please only use Jakarta dependencies in your project, and Angus implementation starting from Simple Java Mail 8.6.1 up. Simple Java Mail defines its own dependencies, but you might be getting the wrong ones from your maven config. Or perhaps you are running in an application server that manages such libraries?
