### ISSUE TITLE
How to reply/forward an email by using simple-java-mail

### ISSUE THREAD

**Issue by ensean** [bbottema/simple-java-mail#55]
For now, I have get the emails from INBOX of my gmail acount, is it possible to reply/forward these emails when using simple-java-mail? 

I have searched the api docs, but no hits ....

**Comment by bbottema** [comment]
No, Simple Java Mail is a SMTP client. It can only connect to an SMTP server to send emails. To retrieve emails for further processing you need a POP3 / IMAP client.
