### ISSUE TITLE
Simple java mail with jre 6

### ISSUE THREAD

**Issue by Francks11** [bbottema/simple-java-mail#57]
Hello,

I use WebSphere Portal Server with JR6. We can't migrate now to jre7 or later.

How can we use simple java mail?

Is there a version for Java 6? Or an older version that support java 6?

Thanks

**Comment by bbottema** [comment]
[Simple Java Mail v3.1.1](http://search.maven.org/#artifactdetails%7Corg.codemonkey.simplejavamail%7Csimple-java-mail%7C3.1.1%7Cjar) is the last version that was still java 6. Still a good release.

**Comment by bbottema** [comment]
Starting with release 4.2.0, every release will now have an "x.y.z-java6-release" release as well.

```xml
<dependency>
    <groupId>org.simplejavamail</groupId>
    <artifactId>simple-java-mail</artifactId>
    <version>4.2.0-java6-release</version>
</dependency>
```
