### ISSUE TITLE
Debug mode that logs but doesn't send emails?

### ISSUE THREAD

**Issue by Addvilz** [bbottema/simple-java-mail#64]
Is it possible to configure mailer to only "pretend" that the mail is sent? TransportStrategy.VOID for example? 

Could be rather useful for testing, to not need a smtp server running somewhere.

**Comment by bbottema** [comment]
That doesn't make sense to me. You should probably be use a MailSender mock using something like EasyMock or Mockito. You don't want to test whether Simple Java Mail is working properly, right.

**Comment by Addvilz** [comment]
Sorry, it came out a little wrong. With testing I did not mean testing per-se, like JUnit tests, I meant, for example, in QA environment, it would be preferable to log messages instead of actually sending them. This is not limited to this example either, there are example use cases where "disabling" sending of the email is needed.

Our example use case is staging environment. We would like to log the emails instead of actually sending them, but there are two options then - every time sendMail is invoked, in every place check the current environment, or replace mailer with our own class, or use mock SMTP server. Checking for env in every usage of mailer is tedious task at best. Having a mock SMTP isn't a simple task either. Unfortunately sendMail is final and we can't override it. We could in theory create our own interface and two delegates to the mailer, but it introduces an abstraction I would rather avoid having.

**Comment by Addvilz** [comment]
@bbottema do you perhaps have something in mind on how you would prefer to see this in code? I can implement it and send a PR.

**Comment by bbottema** [comment]
I'm still not sure about the use case validity, because I would rather configure an actual SMTP server that doesn't relay, if you want to check environment configuration. However, due to popular demand I will add this feature.

I would probably create a Session subclass that overrides .getTransport() to return a dummy that only logs when transport strategy is TransportStrategy.LOGGING_ONLY. This way Simple Java Mail remains unchanged, while the actual transport becomes optional.

**Comment by bbottema** [comment]
Implemented, but not ready for release yet.

Solution is simple: I've added it as a config property. Either configure through properties file, or set directly on the Mailer). I'll update the documentation somewhere next week.

**Comment by bbottema** [comment]
```java
mailer.setTransportModeLoggingOnly(true);
```
Or set property

```properties
simplejavamail.transport.mode.logging.only=false
```

**Comment by bbottema** [comment]
Released in v4.2.0.

**Comment by Addvilz** [comment]
Absolutely amazing! Thanks!

**Comment by mordmord** [comment]
Is this feature possible in v5.0+?? Thanks!

**Comment by bbottema** [comment]
Current 9.x usage (verified against 9.3.2):

```java
Mailer mailer = MailerBuilder
    .withTransportModeLoggingOnly()
    .buildMailer();

mailer.sendMail(email); // logged, not sent
```

The mutable setter was replaced by the builder API in 5.0, and no SMTP server configuration is needed for this mode on the current line. See the [5.0 builder migration](https://www.simplejavamail.org/migration-notes-5.0.0.html#section-what-changed), [7.8.0 release note](https://github.com/bbottema/simple-java-mail/releases/tag/7.8.0), and [logging-only documentation](https://www.simplejavamail.org/debugging.html#section-debug-mode).
