### ISSUE TITLE
how to get mail sent result?

### ISSUE THREAD

**Issue by junfengren** [bbottema/simple-java-mail#75]
I want to know a mail sent result,how get it?

**Comment by bbottema** [comment]
You're not being very specific here. There are lots of ways to find out what was sent.

Do you need the Email's details that were sent or the MimeMessage? You can set `org.simplejavamail.mailer.internal.mailsender.MailSender` to TRACE or turn on logging-only mode, which logs the Email by default on INFO.

You can also turn on debugging mode and see what you can get out of the underlying native Java Mail framework.

If you just want to receive the emails on a test server, you can use [Wiser](https://github.com/voodoodyne/subethasmtp/blob/master/Wiser.md), which Simple Java Mail [also uses](https://github.com/bbottema/simple-java-mail/blob/master/src/test/java/org/simplejavamail/mailer/MailerLiveTest.java) with junit.
