### ISSUE TITLE
Eclipse can't recognize the class Message in Message.Recipient.TO 

### ISSUE THREAD

**Issue by moun3imy** [bbottema/simple-java-mail#76]
Eclipse is pointing to an error at the line : 

`email.addRecipient("mounaim", "m.zaryouhi@mymail.com",Message.Recipient.TO);`

it seems it can't point to any Message class inside the simple java mail jar. What could be the problem here ? I'm using java 1.7 and simple-java-mail-4.0.0 version

**Comment by bbottema** [comment]
Seems to be an issue with Eclipse. I have no idea. Have you tried IntelliJ?
