### ISSUE TITLE
Incompatible types with JDK 8

### ISSUE THREAD

**Issue by rvenson** [bbottema/simple-java-mail#78]
The basic use of the library informed by the site of simple mail would be this:

`Email email = new Email();

email.setFromAddress("Michel Baker", "m.baker@mbakery.com");
email.addRecipient("mom", "jean.baker@hotmail.com", RecipientType.TO);
email.addRecipient("dad", "StevenOakly1963@hotmail.com", RecipientType.TO);
email.setSubject("My Bakery is finally open!");
email.setText("Mom, Dad. We did the opening ceremony of our bakery!!!");

new Mailer("server", "25", "username", "password").sendMail(email);`

However, there are no more references from the RecipientType in JDK 8, and I could not find an alternative to this either.

**Comment by bbottema** [comment]
I'm a little confused by your report.

RecipientType is not part of the JDK, but JavaMail, which is stated as dependency of Simple Java Mail. Further, there are many more types used from JavaMail which are not in JDK, so you should get errors for those too.

```
        <dependency>
            <groupId>com.sun.mail</groupId>
            <artifactId>javax.mail</artifactId>
            <version>1.5.5</version>
        </dependency>
```
