### ISSUE TITLE
Need to document developer logging

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bbottema/simple-java-mail#8]
```
Need to document developer logging options, system properties, 
logging.properties, etc.

I could find no information on this on your page.  If there, please provide a 
link...

Thanks,
Jeff
```

Original issue reported on code.google.com by `trentj...@gmail.com` on 2 Nov 2012 at 12:07

**Comment by bbottema** [comment]
There is a way to get more logging out of this library:

- enable debug logging `mailer.setDebug(true)`
- increase log level of the native JavaMail framework using log4j config
