### ISSUE TITLE
Shade dependencies to different package

### ISSUE THREAD

**Issue by ben-manes** [bbottema/simple-java-mail#80]
The `emailaddress-rfc2822` validator is embedded into the jar and set to an older release. If that dependency is used as well, then which is chosen depends on the classpath ordering. Due to changes in the API (defaults) the behavior can be non-deterministic.

Ideally the dependency would be explicit so that the versions are managed by the build system. If that isn't acceptable, then shading to an internal package would avoid conflicts. (It may also be necessary in jigsaw, which I think disallows package collisions)

**Comment by bbottema** [comment]
Java 9 is released, so this is becoming more important now. Will see if I can include this in the upcoming 5.0.0 release.

**Comment by bbottema** [comment]
Will be in 5.0.0
