### ISSUE TITLE
Timeout for email

### ISSUE THREAD

**Issue by datmt** [bbottema/simple-java-mail#84]
Hello,

Thanks for the great library.

I'm developing a mail sending application. In normal condition, the app sends mails just fine. However, if there are problems with the emails (wrong format, not exists), the app did not stop but keep trying to send the mail. 

I wonder if there is a setting to set the maximum time to wait on one email so it can skip the one that takes too long to send.

Thanks

**Comment by bbottema** [comment]
Hi @datmt, it's up to your application design if you implement delays or not. This libraries just sends sends emails for you (it doesn't have retry functionality either).

There are just two modes of sending: 
1. **synchronous** (`mailer.send(yourEmail)`): which waits until a message has been accepted completely by the SMTP server
2. **asynchronous** (`mailer.send(yourEmail, true)`): which doesn't wait and returns right away for the next operation

It's up to you to design your application around these two options.

**Comment by bbottema** [comment]
@datmt can you please confirm that it was your app that kept retrying and not .send() that kept blocking indefinitely?

**Comment by bbottema** [comment]
Also see #85

**Comment by datmt** [comment]
Thanks!

I think it's best to set timeout on the thread in my case
