### ISSUE TITLE
Simple Java Mail Wishlist -- email.setMessagePriority

### ISSUE THREAD

**Issue by dormitionskete** [bbottema/simple-java-mail#92]
I recently became acquainted with SimpleJavaMail.  I've been testing it for a few days, and so far, I like it very much.  Thank you very much for making it, and sharing it with us!

On your website, you asked for suggestions for how it could be improved.  I have a few "wishlist" items for it.  I'll put them in separate tickets so you can evaluate and track them individually.

---

Please consider adding a setMessagePriority(int iMsgPriority) method: 

```
email.setMessagePriority(___);

msg.addHeader("X-Priority", ("" + iMsgPriority));  // 1 - 5

Values: 1 = High, 3 = Normal, 5 = Low

```
Yes, we could set it with a custom header, but it would be nice if we didn't have to program it ourselves -- especially so people don't need to learn the intricacies of mail headers.

**Comment by bbottema** [comment]
Is the priority a standardized field or otherwise defacto standard? I know Outlook maintains its own flag for example, I'm not aware of any standardization in this sense. I'd have to look through the RFC to be sure though.

If not, I'm not sure who the target audience would be with "X-Priority".

On a sidenote, `setReturnReceiptRequested` was a copy/paste mistake I assume?

**Comment by dormitionskete** [comment]
Thank you for considering this.  I believe the X-Priority values are standard, although it can be any number from 1 - 5, with 1 = High, 2 = Medium High, 3 = Normal, 4 = Medium Low, 5 = Low.  If I've ever read the RFC, it's been many years...

And yes, the "setReturnReceiptRequested" was a copy/paste mistake.  Please forgive me.

**Comment by bbottema** [comment]
This field is non-standard: https://people.dsv.su.se/~jpalme/ietf/mail-headers/mail-headers.html

I don't think it is a good idea to include this in the API. I think the nest best approach is by setting a header on the builder:

```
Email email = new EmailBuilder()
   .addHeader("X-Priority", 2)
   .build();
```
