### ISSUE TITLE
Add support native API for setting Disposition-Notification-To header

### ISSUE THREAD

**Issue by dormitionskete** [bbottema/simple-java-mail#93]
I recently became acquainted with SimpleJavaMail.  I've been testing it for a few days, and so far, I like it very much.  Thank you very much for making it, and sharing it with us!

On your website, you asked for suggestions for how it could be improved.  I have a few "wishlist" items for it.  I'll put them in separate tickets so you can evaluate and track them individually.

---

Please consider adding a method to set Return Receipt Requested information:

```
email.setReturnReceiptRequested(MsgFromAddress) // or other address

if (bReturnReceiptRequested) {
   msg.setHeader("Disposition-Notification-To", getMsgFrom());
}
```

Yes, we could set it with a custom header, but it would be nice if we didn't have to program it ourselves -- especially so people don't need to learn the intricacies of mail headers.

**Comment by bbottema** [comment]
Agreed.

What about a custom notification reply (https://stackoverflow.com/questions/25600405/how-to-create-a-return-receipt-email-javamail)? I haven't looked into this before though.

**Comment by dormitionskete** [comment]
I believe we're talking about the same thing here.  It's just a simple addition:

```
email.addHeader("Disposition-Notification-To", msgFromAddress;
```

**Comment by bbottema** [comment]
What I get from that stackoverflow answer is that you can have a custom return-body embedded.

> Create a MultipartReport object, populate it with a DispositionNotification object, the text to display to the user, and optionally the original message. Use the Message.setContent method to set the MultipartReport as the content of the new message that you send back as the read receipt notification.

I'm not sure I've ever encountered such a custom return-email. Perhaps for a follow-up feature lateron. For now we can focus on just the notification address.

**Comment by dormitionskete** [comment]
I think you're right.  I don't think I've ever encountered it, either...

And I agree.  I think I'd save it for another day, and see if someone requests it.  I think spending quality time with your little one(s) would probably be a better use of your time!

Thank you again.

**Comment by bbottema** [comment]
Release in 4.4.0. Please verify.

**Comment by bbottema** [comment]
Current 9.x usage (verified against 9.3.2):

```java
Email email = EmailBuilder.startingBlank()
    .withDispositionNotificationTo("Mail receipts", "receipts@example.com")
    .withReturnReceiptTo("Mail receipts", "receipts@example.com")
    .buildEmail();
```

These builder methods replace the old mutable setter/raw-header examples. They request disposition and return receipts respectively; receiving clients and servers may still decline them. See the [5.0 builder migration](https://www.simplejavamail.org/migration-notes-5.0.0.html#section-what-changed) and [current receipt documentation](https://www.simplejavamail.org/features.html#section-return-receipt).
