### ISSUE TITLE
Add support for compiling a group of emails into a single email

### ISSUE THREAD

**Issue by tucano2** [bbottema/simple-java-mail#99]
Hello,

I was wondering if you've ever considered a feature for grouping emails.  We have this in our homegrown email library, and it's really the only feature holding me back from fully switching to simple java mail.  We rely on this feature because we have certain events in our environment that will trigger inordinately high amounts of email.  

Basically a time interval is set for defining a fixed time window that emails should be grouped into.  If say 2 seconds and a blast of emails came inside the 2 second interval, they would be grouped together (currently by subject) and sent as digests at the end of the interval.  This greatly helps during times of system stress.

Let me know if you've ever considered such a feature.

Thanks.

**Comment by bbottema** [comment]
If I interpret you correctly, it's not so much about grouping as it is about spreading out the groups, right?

Or else I'm not sure what grouping exactly would mean. Like is it grouped in a single connection to the SMTP server or just send whatever came in after the 2 seconds like delayed bursts.

**Comment by tucano2** [comment]
It's more about combining similar emails into one email instead of multiple.  So in a simple example, during a 3 msg burst without this feature you might see in your inbox:

**9:30:01 am, Subject = New Signal Detected**
**9:30:01 am, Subject = New Signal Detected**
**9:30:02 am, Subject = New Signal Detected**

but with the feature you'd and a 2 second interval set you'd see:

**9:30:02 am, Subject = New Signal Detected  : (3) messages**

**Comment by bbottema** [comment]
Ahh, I see.

I'm not sure that's appropriate for Simple Java Mail. All it does is make mailing easy and straightforward (RFC compliant), but *what* you send with it is up you.

I'll give it some thought.

Since this is about performance though, have you considered using multiple SMTP servers and then have multiple `Mailer` instances, and Round Robin between them?

**Comment by tucano2** [comment]
Thanks Benny.  In a heavily email messaging dependent organization, this feature is a lot about ensuring the end user inboxes are overwhelmed.  I'll submit a PR.

**Comment by bbottema** [comment]
Closing as this is about a content/client specific Use Case about which Simple Java Mail has no opinions.
